package com.knight.emms.model;
// Generated 2017-7-28 9:54:00 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.google.gson.annotations.Expose;
import com.knight.core.model.BaseModel;
import com.knight.emms.constant.Constant;
import com.knight.emms.core.VetFlowMethod;

import lombok.Data;
import lombok.ToString;

/**
 * TFormReview generated by hbm2java
 */
@Data
@ToString(callSuper = false)
public class FormReview extends BaseModel implements VetFlowMethod {
	
	private static final long serialVersionUID = 1L;

	@Expose
	private Long reviewId;
	@Expose
	private Long relateId;
	@Expose
	private String relateModule;
	@Expose
	private Long reviewUserid;
	@Expose
	private String reviewUsername;
	@Expose
	private String reviewDep;
	@Expose
	private Date reviewTime;
	@Expose
	private String reviewOpinion;
	@Expose
	private String reviewRemark;
	@Expose
	private String warning;

	private String extendMessage;

	public Object getVetFlow() {
		return this;
	}

	public String getOpinion() {
		return this.reviewOpinion;
	}

	public void setOpinion(String opinion) {
		this.reviewOpinion = opinion;
	}

	public String getVetRemark() {
		return this.reviewRemark;
	}

	public void setVetRemark(String remark) {
		this.reviewRemark = remark;
	}

	public boolean isVetWarning() {
		return Constant.ENABLED.equals(this.warning);
	}

}