package com.knight.app.model;

import lombok.Data;
import lombok.ToString;

import com.google.gson.annotations.Expose;
import com.knight.core.model.BaseModel;

// Generated 2015-5-29 9:21:52 by Hibernate Tools 3.4.0.CR1

/**
 * TAppRepairCompon generated by hbm2java
 */
@Data
@ToString(callSuper = false, doNotUseGetters = true)
public class TAppRepairCompon extends BaseModel {

	private static final long serialVersionUID = 1L;
	@Expose
	private Long rcid;
	@Expose
	private Long repid;
	@Expose
	private String compName;
	@Expose
	private String compSpec;
	@Expose
	private String componSerial;
	@Expose
	private Long compNum;
	@Expose
	private Long storeCompNum;	
}
