package com.knight.emms.model;
// Generated 2017-9-6 14:06:02 by Hibernate Tools 3.6.0.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.Since;
import com.google.gson.reflect.TypeToken;
import com.knight.core.model.ExportModel;
import com.knight.core.table.CodeFieldDeclare;
import com.knight.core.table.PersistantDeclare;
import com.knight.core.util.GsonUtil;
import com.knight.emms.constant.Constant;
import com.knight.emms.core.BusinessModel;
import com.knight.emms.core.model.SerialNumberStrategy;

import lombok.Data;
import lombok.ToString;

/**
 * TSettleProject generated by hbm2java
 */
@Data
@ToString(callSuper = false, doNotUseGetters = true)
@PersistantDeclare
@SerialNumberStrategy(name = "settleSerial", strategy = "ZCJS{yyyyMMdd}", maxseq = 9999)
public class SettleMaterials extends BusinessModel implements ExportModel  {

	protected static final long serialVersionUID = 1L;

	@Expose
	private Long settleId;
	@Expose
	private String settleSerial;
	@Expose
	private String settleMan;
	@Expose
	private String settleDate;
	@Expose
	private String settleTitle;
	@Expose
	private String startDate;
	@Expose
	private String endDate;

	//租赁计价方式
	@Expose
	@CodeFieldDeclare(codeId = "TRANPORT_CACULATE_TYPE", valueField = "tranportCaculateTypeName")
	private String tranportCaculateType;
	
	@Expose
	private String tranportCaculateTypeName;
	//运费计价方式
	@Expose
	private String transFeeCaculateType;
	
	@Expose
	private String contractSerial;
	@Expose
	private Long contractmaId;
	@Expose
	private String contractTheme;
	@Expose
	private String projectName;
	//承租单位
	@Expose
	private String paEntName;
	//出租单位
	@Expose
	private String pbEntName;
	@Expose
	@CodeFieldDeclare(codeId = "contractCategory", valueField = "contractCategoryName")
	private String contractCategory;

	@Expose
	private String contractCategoryName;
	//税率
	@Expose
	private BigDecimal taxRate;
	//优惠税率
	@Expose
	private BigDecimal rentalRate;
	@Expose
	@CodeFieldDeclare(codeId = "TAX_CACULATE_TYPE", valueField = "taxCaculateTypeName")
	private String taxCaculateType;
	
	@Expose
	private String taxCaculateTypeName;
	//统计规则
	@Expose
	@CodeFieldDeclare(codeId = "CACULATE_RULE", valueField = "caculateRuleName")
	private String caculateRule;
	
	@Expose
	private String caculateRuleName;
	//合同金额
	@Expose
	private BigDecimal contractAmount;
	//已结算金额
	@Expose
	private BigDecimal finSettingAmount;
	//本次结算金额
	@Expose
	private BigDecimal settledAmount;
	//实际支付金额
	@Expose
	private BigDecimal handoverAmount;
	//冲减金额
	@Expose
	private BigDecimal writedownAmount;
	@Expose
	private String financiaType;
	@Expose
	private Long settleDepId;
	@Expose
	private String settleDepName;
	@Expose
	private BigDecimal transFeeAmount;
	@Expose
	private BigDecimal otherFeeAmount;
	
	//生效失效
	@Expose
	@CodeFieldDeclare(codeId = "EFFECTIVE_FLAG", valueField = "statusName")
	private String status;
	@Expose
	private String statusName;
	
	//倒扣租金
	@Expose
	private String backOff;
	
	private String delFlag = Constant.ENABLED;
	
	/**生效时间*/
	private String effectiveTime;
	
	/**失效时间*/
	private String loseEffectiveTime;
	
	/*
	 * 清单计算时间
	 * 用于查看周材结算费用清单
	 * */
	private String detailCaculateTime;
	
	private String settleFeeDetails = "";
	
	@Expose(deserialize = false, serialize = false)
	@Since(value = 2.0)
	private Set<SettleFee> settleFeeDetailSet = new HashSet<SettleFee>();
	
	public void setSubSettleFee() {
		Set<SettleFee> settleFeeDetailSet = GsonUtil.fromJson(this.getSettleFeeDetails(), new TypeToken<Set<SettleFee>>() {});
		if (settleFeeDetailSet != null) {
			for (SettleFee p : settleFeeDetailSet) {
				p.setRelateId(settleId);
				p.setRelateModule(Constant.SETTLE_MATERIALS);
			}
		}
		this.setSettleFeeDetailSet(settleFeeDetailSet);
	}
	
	@Override
	public void setModelSerial(String serial) {
		// TODO Auto-generated method stub
		
	}

}
