package com.knight.emms.model;
// Generated 2017-7-21 10:05:05 by Hibernate Tools 3.6.0.Final

import com.google.gson.annotations.Expose;
import com.knight.core.model.BaseModel;
import com.knight.core.table.CodeFieldDeclare;
import com.knight.core.table.PersistantDeclare;

import lombok.Data;
import lombok.ToString;

/**
 * TInstallDismantlePrice generated by hbm2java
 */
@Data
@ToString(callSuper = false, doNotUseGetters = true)
@PersistantDeclare
public class InstallDismantlePrice  extends BaseModel {
	private static final long serialVersionUID = 1L;

	@Expose
	private Long priceId;
	
	@Expose
    @CodeFieldDeclare(codeId = "belongToArea", valueField = "belongToAreaName")
	private String belongToArea;

    @Expose
    private String belongToAreaName;
	
	
	@Expose
	@CodeFieldDeclare(codeId = "equipSpecific", valueField = "equipSpecificName")
	private String equipSpecific;
	
	@Expose
    private String equipSpecificName;
	
	@Expose
	@CodeFieldDeclare(codeId = "INSTALL_DISMANTLE_TYPE", valueField = "installDismantleTypeName")
	private String installDismantleType;
	
	@Expose
	private String measurementUnit;
	
	@Expose
	private String installDismantleTypeName;
	
	@Expose
	private Long projectPrice;
	
	@Expose
	private Long teamPrice;
	
	
	private String delFlag;

	
}
