package com.knight.emms.model;
// Generated 2017-9-6 14:06:02 by Hibernate Tools 3.6.0.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.Since;
import com.google.gson.reflect.TypeToken;
import com.knight.core.model.ExportModel;
import com.knight.core.table.CodeFieldDeclare;
import com.knight.core.table.PersistantDeclare;
import com.knight.core.util.GsonUtil;
import com.knight.emms.constant.Constant;
import com.knight.emms.core.BusinessModel;
import com.knight.emms.core.model.SerialNumberStrategy;

import lombok.Data;
import lombok.ToString;

/**
 * TSettleProject generated by hbm2java
 */
@Data
@ToString(callSuper = false, doNotUseGetters = true)
@PersistantDeclare
@SerialNumberStrategy(name = "settleSerial", strategy = "JS{yyyyMMdd}", maxseq = 999)
public class SettleProject extends BusinessModel implements ExportModel  {

	protected static final long serialVersionUID = 1L;

	@Expose
	private Long settleId;
	@Expose
	private String settleSerial;
	@Expose
	private String settleMan;
	@Expose
	private String settleDate;
	@Expose
	private String settleTitle;
	@Expose
	private String startDate;
	@Expose
	private String endDate;
	@Expose
	private String contractSerial;
	@Expose
	private Long contractId;
	@Expose
	@CodeFieldDeclare(codeId = "contractCategory", valueField = "contractCategoryName")
	private String contractCategory;

	@Expose
	private String contractCategoryName;

	@Expose
	private String projectName;
	
	@Expose
	@CodeFieldDeclare(codeId = "EFFECTIVE_FLAG", valueField = "settleProjectStateName")
	private String settleProjectState;
	@Expose
	private String settleProjectStateName;
	
	
	//计税方式
	@Expose
	@CodeFieldDeclare(codeId = "TAX_MODE", valueField = "taxModeName")
	private String taxMode;
	
	
	@Expose
	private String taxModeName;
	@Expose
	private BigDecimal taxRate;
	@Expose
	private BigDecimal rentalRate;
	@Expose
	private BigDecimal rentalPrice;
	@Expose
	private Long depId;
	@Expose
	private String depName;
	@Expose
	private BigDecimal initialSettleAmount;
	@Expose
	private BigDecimal currentSettleAmount;
	@Expose
	private BigDecimal totalSettleAmount;
	@Expose
	private String backOff;
	
	/*
	 * 清单计算时间
	 * 用于查看项目结算费用清单
	 * */
	private String detailCaculateTime;
	
	private String settleProjectDetails = "";
	
	@Expose(deserialize = false, serialize = false)
	@Since(value = 2.0)
	private Set<SettleFee> settleProjectDetailsSet = new HashSet<SettleFee>();

	// ==============================================================================//
		public void setSubSettleFee() {
			Set<SettleFee> settleProjectDetailsSet = GsonUtil.fromJson(this.getSettleProjectDetails(), new TypeToken<Set<SettleFee>>() {});
			if (settleProjectDetailsSet != null) {
				for (SettleFee p : settleProjectDetailsSet) {
					p.setRelateId(settleId);
					p.setRelateModule(Constant.SETTLE_PROJECT);
				}
			}
			this.setSettleProjectDetailsSet(settleProjectDetailsSet);
		}
		
	@Override
	public void setModelSerial(String serial) {
		// TODO Auto-generated method stub
		
	}

}
