package com.knight.emms.model;
// Generated 2017-7-27 16:26:42 by Hibernate Tools 3.6.0.Final

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.google.gson.annotations.Expose;
import com.knight.core.model.BaseModel;
import com.knight.core.table.PersistantDeclare;
import com.knight.emms.core.model.SerialNumberStrategy;

import lombok.Data;
import lombok.ToString;

/**
 * TFlowDefineReview generated by hbm2java
 */
@Data
@ToString(callSuper = false, doNotUseGetters = true)
@PersistantDeclare
public class TFlowDefineReview extends BaseModel {

	private static final long serialVersionUID = 1L;

	private Long defineId;
	
	private Long flowId;
	
	private Long nid;
	
	private Long seq;
	
	private Long relateId;
	
	private String relateModule;
	
	private String state;


}
