--内置代码词典
CREATE TABLE BM_BUILTIN_STORAGE
(
  ALIAS VARCHAR(64) NOT NULL,
  CODE  VARCHAR(6) NOT NULL,
  VALUE VARCHAR(64) NOT NULL,
  NAME  VARCHAR(30) NOT NULL
);
--省份名称 province
CREATE TABLE BM_PROVINCE
(
  CODE        VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE       VARCHAR(64) NOT NULL,
  NAME        VARCHAR(30) NOT NULL,
  LONGITUDE   VARCHAR(16) NULL,               --经度
  LATITUDE    VARCHAR(16) NULL                --纬度
);
--市名称 city
CREATE TABLE BM_CITY
(
  CODE  VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE VARCHAR(64) NOT NULL,
  NAME  VARCHAR(30) NULL,
  LONGITUDE   VARCHAR(16) NULL,               --经度
  LATITUDE    VARCHAR(16) NULL                --纬度
);
--区名称 county
CREATE TABLE BM_COUNTY 
(
  CODE  VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE VARCHAR(64) NOT NULL,
  NAME  VARCHAR(30) NULL,
  LONGITUDE   VARCHAR(16) NULL,               --经度
  LATITUDE    VARCHAR(16) NULL                --纬度
);
--企业类型 corpType
CREATE TABLE BM_CORP_TYPE
(
  CODE  CHAR(2) NOT NULL PRIMARY KEY,
  VALUE VARCHAR(64) NOT NULL
);
--企业工商登记类型 econType
CREATE TABLE BM_ECON_TYPE
(
  CODE   VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE  VARCHAR(64) NOT NULL,
  PARENT VARCHAR(6) NULL
);
--资质类型 aptitudekind
CREATE TABLE BM_APTITUDEKIND
(
  CODE  VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE VARCHAR(64) NOT NULL
);
--资质序列 tradetype
CREATE TABLE BM_TRADETYPE
(
  CODE  VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE VARCHAR(64) NOT NULL
);
--专业类别 tradetypebound
CREATE TABLE BM_TRADETYPEBOUND
(
  CODE  VARCHAR(8) NOT NULL PRIMARY KEY,
  VALUE VARCHAR(64) NOT NULL
);
--资质等级 certLevel
CREATE TABLE BM_CERT_LEVEL
(
  CODE  VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE VARCHAR(64) NOT NULL
);
--民族 nation
CREATE TABLE BM_NATION
(
  CODE  VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE VARCHAR(64) NOT NULL
);
--学位 degree
CREATE TABLE BM_DEGREE
(
  CODE  VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE VARCHAR(64) NOT NULL
);
--学历 edulevel
CREATE TABLE BM_EDULEVEL
(
  CODE  VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE VARCHAR(64) NOT NULL
);
--人员注册类型及等级 specialtyType
CREATE TABLE BM_SPECIALTY_TYPE
(
  CODE  VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE VARCHAR(64) NOT NULL
);
--从业工种 kindWork
CREATE TABLE BM_KIND_WORK
(
  CODE  VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE VARCHAR(64) NOT NULL
);
--联系人类别 linkerType
CREATE TABLE BM_LINKER_TYPE
(
  CODE  VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE VARCHAR(64) NOT NULL
);
--工程项目类别 projectType
CREATE TABLE BM_PROJECT_TYPE
(
  CODE  VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE VARCHAR(64) NOT NULL
);
--工程项目规模 projectScale
CREATE TABLE BM_PROJECT_SCALE
(
  CODE  VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE VARCHAR(64) NOT NULL
);
--零配件/设备类别 repertoryCategory
CREATE TABLE BM_REPERTORY_CATEGORY
(
  CODE  VARCHAR(12) NOT NULL PRIMARY KEY,
  VALUE VARCHAR(64) NOT NULL,
  PARENT VARCHAR(12) NULL,
  NAME  VARCHAR(30) NOT NULL
);
--零配件名称 componGeneric
CREATE TABLE BM_COMPONENT_GENERIC
(
  CODE  VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE VARCHAR(64) NOT NULL,
  NAME  VARCHAR(30) NULL
);
--零配件规格型号 componSpecific
CREATE TABLE BM_COMPONENT_SPECIFIC
(
  CODE  VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE VARCHAR(64) NOT NULL
);
--设备名称 equipGeneric
CREATE TABLE BM_EQUIP_GENERIC
(
  CODE  VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE VARCHAR(64) NOT NULL
);
--设备规格型号 equipSpecific
CREATE TABLE BM_EQUIP_SPECIFIC
(
  CODE  VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE VARCHAR(64) NOT NULL,
  NAME  VARCHAR(30) NULL
);
--设备来源 equipSource
CREATE TABLE BM_EQUIP_SOURCE
(
  CODE  VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE VARCHAR(64) NOT NULL
);
--设备厂家 equipVender
CREATE TABLE BM_EQUIP_VENDER
(
  CODE  VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE VARCHAR(64) NOT NULL
);
--制造许可证号 licenseNumber
CREATE TABLE BM_LICENSE_NUMBER
(
  CODE  VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE VARCHAR(64) NOT NULL
);
--合同类别 contractCategory
CREATE TABLE BM_CONTRACT_CATEGORY
(
  CODE  VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE VARCHAR(64) NOT NULL
);
--租金标准 rentStandard
CREATE TABLE BM_RENT_STANDARD
(
  CODE  VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE VARCHAR(64) NOT NULL
);
--票据类型 invoiceType
CREATE TABLE BM_INVOICE_TYPE
(
  CODE  VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE VARCHAR(64) NOT NULL
);
--租金单位类型 measurement
CREATE TABLE BM_MEASUREMENT
(
  CODE  VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE VARCHAR(64) NOT NULL
);
--保险项目 insureProgram
CREATE TABLE BM_INSURE_PROGRAM
(
  CODE  VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE VARCHAR(64) NOT NULL
);
--支付方式 paymentType
CREATE TABLE BM_PAYMENT_TYPE
(
  CODE  VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE VARCHAR(64) NOT NULL
);
--费用类别 reimburseType
CREATE TABLE BM_REIMBURSE_TYPE
(
  CODE  VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE VARCHAR(64) NOT NULL,
  PARENT VARCHAR(6) NULL
);
--事件类型 incidentType
CREATE TABLE BM_INCIDENT_TYPE
(
  CODE  VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE VARCHAR(64) NOT NULL
);
--故障诊断 faultDiagnosis
CREATE TABLE BM_FAULT_DIAGNOSIS
(
  CODE  VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE VARCHAR(64) NOT NULL
);
--故障部位 faultLocation
CREATE TABLE BM_FAULT_LOCATION
(
  CODE  VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE VARCHAR(64) NOT NULL
);
--模块类型表
CREATE TABLE BM_RELATE_MODULE
(
  CODE  VARCHAR(32) NOT NULL PRIMARY KEY,
  VALUE VARCHAR(64) NOT NULL
);
--星期
CREATE TABLE BM_WEEK_DAY
(
  WEEK_DAY         NVARCHAR(15) NOT NULL,
  DAY_OF_WEEK      SMALLINT NOT NULL,
  ISWEEKDAY        SMALLINT NOT NULL DEFAULT 1
);
--巡检结果
CREATE TABLE BM_INSPECT_RESULT
(
  CODE  VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE VARCHAR(64) NOT NULL,
  NAME  VARCHAR(30) NULL
);
--检测验收类型
CREATE TABLE BM_VITEM_TYPE
(
  CODE  VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE VARCHAR(64) NOT NULL
);
--保养类型
CREATE TABLE BM_MAINT_TYPE
(
  CODE  VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE VARCHAR(64) NOT NULL
);
--税率
CREATE TABLE BM_TAX_RATE
(
  CODE  VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE VARCHAR(64) NOT NULL
);
--汽车吊所属单位
CREATE TABLE BM_AUTOCRANE_DEPEND
(
  CODE  VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE VARCHAR(64) NOT NULL
);
--合同项目费用
CREATE TABLE BM_CONTRACT_COSTITEM
(
  CODE  VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE VARCHAR(64) NOT NULL
);
--任务内容 constructTask
CREATE TABLE BM_CONSTRUCT_TASK
(
  CODE        VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE       VARCHAR(64) NOT NULL
);
--资产属性
CREATE TABLE BM_ASSETS_PROPERTY
(
  CODE        VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE       VARCHAR(64) NOT NULL
);
--工程类型
CREATE TABLE BM_ENGINEERING_TYPE
(
  CODE        VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE       VARCHAR(64) NOT NULL
);
--计划类型
CREATE TABLE BM_PLAN_TYPE
(
  CODE        VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE       VARCHAR(64) NOT NULL
);
--汽吊类型
CREATE TABLE BM_TRUCK_CRANE_SPECIFIC
(
  CODE        VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE       VARCHAR(64) NOT NULL
);
--回收类型
CREATE TABLE BM_RECYCLE_TYPE
(
  CODE        VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE       VARCHAR(64) NOT NULL
);
--安装费用
CREATE TABLE BM_INSTALL_FEE_TYPE
(
  CODE        VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE       VARCHAR(64) NOT NULL
);
--周材改型类别
CREATE TABLE BM_REMODEL_TYPE
(
  CODE        VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE       VARCHAR(64) NOT NULL
);
--泵车类型
CREATE TABLE BM_PUMP_TYPE
(
  CODE        VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE       VARCHAR(64) NOT NULL
);
--泵车型号
CREATE TABLE BM_PUMP_NUMBER
(
  CODE        VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE       VARCHAR(64) NOT NULL
);