package com.knight.emms.model;
// Generated 2017-7-18 13:57:11 by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.Since;
import com.google.gson.reflect.TypeToken;
import com.knight.core.model.ExportModel;
import com.knight.core.table.CodeFieldDeclare;
import com.knight.core.table.PersistantDeclare;
import com.knight.core.util.GsonUtil;
import com.knight.emms.constant.Constant;
import com.knight.emms.core.BusinessModel;
import com.knight.emms.core.model.SerialNumberStrategy;

import lombok.Data;
import lombok.ToString;

/**
 * TCeaseReport generated by hbm2java
 */
@Data
@ToString(callSuper = false, doNotUseGetters = true)
@PersistantDeclare(isExportable = true, exportName = "报停管理", sheetName = "报停管理信息")
@SerialNumberStrategy(name = "blockSerial", strategy = "ZJBT{yyyyMMdd}", maxseq = 999)
public class LeaseBlockUp extends BusinessModel implements ExportModel{

	private static final long serialVersionUID = 1L;

	@Expose
	private Long blockId;
	
	@Expose
	private String blockSerial;
	
	@Expose
	private Long userId;
	
	@Expose
	private String userName;
	
	//生效失效
	@Expose
	@CodeFieldDeclare(codeId = "EFFECTIVE_FLAG", valueField = "statusName")
	private String status;
	
	@Expose
	private String statusName;
	
	@Expose
	private LeaseContract leaseContract;
	
	@Expose
	private String blockTitle;
	
	@Expose
	private String startDate;
	
	@Expose
	private String endDate;
	
	@Expose
	private String applyDate;
	
	/**本次结算金额*/
	@Expose
	private String settledAmount;
	
	/**内部结算金额*/
	@Expose
	private String insideAmount;
	
	@Expose
	private String finishAmount;
	
	@Expose
	private String backOff;

	@Expose
	@CodeFieldDeclare(codeId = "TRANPORT_CACULATE_TYPE", valueField = "tranportCaculateTypeName")
	private String tranportCaculateType;
	
	@Expose
	private String tranportCaculateTypeName;
	
	//统计规则
	@Expose
	@CodeFieldDeclare(codeId = "CACULATE_RULE", valueField = "caculateRuleName")
	private String caculateRule;
	
	@Expose
	private String caculateRuleName;
	
	/**周材合同编号*/
	@Expose
	private String contractSerial;
	
	/**停用天数*/
	@Expose
	private Integer blockupDays;
		
	private String delFlag = Constant.ENABLED;
	

	public void setModelSerial(String serial) {
		this.blockSerial = serial;
	}
	
	public String leaseBlockUpDetails ="";
	
	@Expose(deserialize = false, serialize = false)
	@Since(value = 2.0)
	public Set<LeaseBlockUpDetail> leaseBlockUpDetailSet = new HashSet<LeaseBlockUpDetail>();
	
	public String insideBlockUpDetails ="";
	
	@Expose(deserialize = false, serialize = false)
	@Since(value = 2.0)
	public Set<InsideBlockUpDetail> insideBlockUpDetailSet = new HashSet<InsideBlockUpDetail>();

	public void setSubLeaseBlockUp() {
		Set<LeaseBlockUpDetail> leaseBlockUpDetailSet = GsonUtil.fromJson(this.getLeaseBlockUpDetails(), new TypeToken<Set<LeaseBlockUpDetail>>() {});
		if (leaseBlockUpDetailSet != null) {
			for (LeaseBlockUpDetail p : leaseBlockUpDetailSet) {
				p.setBlockId(this.getBlockId());
			}
		}
		this.setLeaseBlockUpDetailSet(leaseBlockUpDetailSet);
		
		Set<InsideBlockUpDetail> insideBlockUpDetailSet = GsonUtil.fromJson(this.getInsideBlockUpDetails(), new TypeToken<Set<InsideBlockUpDetail>>() {});
		if (insideBlockUpDetailSet != null) {
			for (InsideBlockUpDetail p : insideBlockUpDetailSet) {
				p.setBlockId(this.getBlockId());
			}
		}
		this.setInsideBlockUpDetailSet(insideBlockUpDetailSet);
	}
}