--2015-01-30
ALTER TABLE T_PRACTITIONER ADD TEAMS VARCHAR(32) NULL;
ALTER TABLE T_COMPONENT_DIARY ADD JACKING_TEAMS VARCHAR(32) NULL;
ALTER TABLE T_COMPONENT_DIARY ADD JACKING_PRACTI_ID BIGINT NULL;
ALTER TABLE T_COMPONENT_DIARY ADD JACKING_PRACTI_NAME VARCHAR(32) NULL;
ALTER TABLE T_COMPONENT_DIARY ADD JACKING_STAUTS CHAR(1) NOT NULL DEFAULT '1';
ALTER TABLE T_COMPONENT_DIARY ADD JACKING_DATE SMALLDATETIME NULL;
ALTER TABLE T_COMPONENT_DIARY ADD DISMANTLE_TEAMS VARCHAR(32) NULL;
ALTER TABLE T_COMPONENT_DIARY ADD DISMANTLE_PRACTI_ID BIGINT NULL;
ALTER TABLE T_COMPONENT_DIARY ADD DISMANTLE_PRACTI_NAME VARCHAR(32) NULL;
ALTER TABLE T_COMPONENT_DIARY ADD DISMANTLE_STAUTS CHAR(1) NOT NULL DEFAULT '1';
ALTER TABLE T_COMPONENT_DIARY ADD DISMANTLE_DATE SMALLDATETIME NULL;
ALTER TABLE T_COMPONENT_DIARY ADD JACKING_ACCOUNT_ID BIGINT NULL;
ALTER TABLE T_COMPONENT_DIARY ADD DISMANTLE_ACCOUNT_ID BIGINT NULL;

ALTER TABLE T_COMPONENT ADD WALL_ATTACHE_FLAG CHAR(1) NOT NULL DEFAULT '0';
ALTER TABLE T_COMPONENT ADD KNOT_FLAG CHAR(1) NOT NULL DEFAULT '0';

ALTER TABLE T_AMOUNT_PAYMENT ALTER COLUMN PAYMENT_DATE CHAR(10) NULL;
ALTER TABLE T_AMOUNT_RECEIVE ALTER COLUMN RECEIVE_DATE CHAR(10) NULL;

ALTER TABLE T_LOGISTICS_TRANSPORT ADD DELIVERY_ENT_ID BIGINT NULL;
ALTER TABLE T_LOGISTICS_TRANSPORT ADD DELIVERY_ENT_NAME VARCHAR(64) NULL;
ALTER TABLE T_LOGISTICS_TRANSPORT ADD RECEIVE_ENT_ID BIGINT NULL;
ALTER TABLE T_LOGISTICS_TRANSPORT ADD RECEIVE_ENT_NAME VARCHAR(64) NULL;

ALTER TABLE T_EQUIPMENT_ACTIVATE ADD ACCEPTANCE_DATE CHAR(10) NULL;
ALTER TABLE T_EQUIPMENT_ACTIVATE ADD CONTRACT_SERIAL VARCHAR(64) NULL;

ALTER TABLE T_SETTLE_COMPON_BRIEF ADD EQUIP_ID BIGINT NULL;
ALTER TABLE T_SETTLE_COMPON_BRIEF ADD RECORD_ID VARCHAR(24) NULL;
ALTER TABLE T_SETTLE_ITEM_BRIEF ADD EQUIP_ID BIGINT NULL;
ALTER TABLE T_SETTLE_ITEM_BRIEF ADD RECORD_ID VARCHAR(24) NULL;

ALTER TABLE T_SETTLE_CONTRACT ADD FINISHED_AMOUNT NUMERIC(12, 2) NOT NULL DEFAULT 0;
--�������
CREATE TABLE T_DISPATCH_AUTOCRANE
(
  DISPATCH_AUTOCRANE_ID      BIGINT IDENTITY PRIMARY KEY,
  DISPATCH_ID                BIGINT NOT NULL,                --����ID
  SPECIFIC_NAME              VARCHAR(64) NULL,               --�ͺ�
  RENT_STANDARD              NUMERIC(12, 2) NOT NULL,        --����
  QUANTITY                   SMALLINT NOT NULL,              --����
  MACHINE_TEAM               VARCHAR(64) NULL,               --̨��
  SUMMARY                    NUMERIC(12, 2) NOT NULL,        --�ϼ�
  ACCOUNT_ID                 BIGINT NULL,                    --�����ʶ
  REMARK                     VARCHAR(256) NULL               --��ע
);

ALTER TABLE T_DISPATCH ADD TEAMS VARCHAR(32) NULL;
ALTER TABLE T_DISPATCH ADD PRACTI_ID BIGINT NULL;
ALTER TABLE T_DISPATCH ADD PRACTI_NAME VARCHAR(32) NULL;
ALTER TABLE T_DISPATCH ADD DELIVERY_ENT_ID BIGINT NULL;
ALTER TABLE T_DISPATCH ADD DELIVERY_ENT_NAME VARCHAR(64) NULL;
ALTER TABLE T_DISPATCH ADD DELIVERY_ADDRESS VARCHAR(128) NULL;
ALTER TABLE T_DISPATCH ADD RECEIVE_ENT_ID BIGINT NULL;
ALTER TABLE T_DISPATCH ADD RECEIVE_ENT_NAME VARCHAR(64) NULL;
ALTER TABLE T_DISPATCH ADD RECEIVE_ADDRESS VARCHAR(128) NULL;
ALTER TABLE T_DISPATCH ADD AUTOCRANE_AMOUNT NUMERIC(12, 2) NOT NULL DEFAULT 0;

ALTER TABLE T_REIMBURSE ADD RECEIVE_BANK VARCHAR(64) NULL;
ALTER TABLE T_REIMBURSE ADD RECEIVE_ACCOUNT VARCHAR(32) NULL;

ALTER TABLE T_EQUIPMENT ADD FLOW_ID BIGINT NULL;
ALTER TABLE T_EQUIPMENT ADD PROJECT_NAME VARCHAR(64) NULL;
--ά�޹���-����
CREATE TABLE T_EQUIPMENT_REPAIR_LOCATION
(
  REPAIR_LOCATION_ID         BIGINT IDENTITY PRIMARY KEY,
  REPAIR_ID                  BIGINT NULL,                    --ά����ϢID
  FAULT_LOCATION             VARCHAR(64) NULL,               --���ϲ�λ(���� BM_FAULT_LOCATION)
  SPEND_DATE                 DATETIME NULL,                  --���Ϸ���ʱ��(��ȷ������)
  PHENOMENON                 VARCHAR(512) NULL,              --��������(300������)
  DIAGNOSIS                  VARCHAR(64) NULL,               --�������(���� BM_FAULT_DIAGNOSIS)
  TROUBLESHOOT_DATE          DATETIME NULL,                  --�����ų�ʱ��(��ȷ������)
  REPAIR_TIME                SMALLINT NULL,                  --ά�޺�ʱ(Сʱ)
  CUMULATIVE_DOWNTIME        SMALLINT NULL                   --�ۼ�ͣ��ʱ��(�����ų�ʱ��-���Ϸ���ʱ��/���ֶ��޸�)
); 

ALTER TABLE T_EQUIPMENT_DETECT ADD DETECT_AMOUNT NUMERIC(12, 2) NOT NULL DEFAULT 0;
ALTER TABLE T_EQUIPMENT_DETECT ALTER COLUMN DETECT_RESULT VARCHAR(128) NULL;
ALTER TABLE T_EQUIPMENT_DETECT ALTER COLUMN DETECTOR VARCHAR(32) NULL;
ALTER TABLE T_EQUIPMENT_DETECT ALTER COLUMN DETECT_DATE CHAR(10) NULL;

--�����Ϣ(�����ϸ)
CREATE TABLE T_EQUIPMENT_DETECT_STATEMENT
(
  DETECT_STATEMENT_ID        BIGINT IDENTITY PRIMARY KEY,
  DETECT_ID                  BIGINT NULL,                    --���ID
  DETECT_TYPE                VARCHAR(128) NOT NULL,          --�������
  DETECT_RESULT              VARCHAR(128) NOT NULL,          --������
  DETECT_DATE                CHAR(10) NULL,                  --�������
  DETECTOR                   VARCHAR(32) NOT NULL,           --�����Ա
  STATEMENT_AMOUNT           NUMERIC(12, 2) NULL             --������
);
--�������
CREATE TABLE T_TEAMS_ACCOUNT
(
  TEAMS_ACCOUNT_ID           BIGINT IDENTITY PRIMARY KEY,
  TEAMS_ACCOUNT_SERIAL       VARCHAR(64) NOT NULL,           --���㵥��
  PROJECT_ID                 BIGINT NULL,                    --��ĿID(��Ŀ����)
  PROJECT_NAME               VARCHAR(64) NULL,               --��Ŀ���
  PRACTI_ID                  BIGINT NULL,                    --���鸺����ID
  PRACTI_NAME                VARCHAR(32) NULL,               --���鸺����
  TEAMS                      VARCHAR(32) NULL,               --�������
  ACCOUNT_START_DATE         SMALLDATETIME NOT NULL,         --���㿪ʼʱ��
  ACCOUNT_END_DATE           SMALLDATETIME NOT NULL,         --�������ʱ��
  KNOT_PRICE                 NUMERIC(12, 2) NULL,            --��׼�ڵ���
  WALL_ATTACHE_PRICE         NUMERIC(12, 2) NULL,            --��ǽ����(Ԫ)
  DEDUCT_AMOUNT              NUMERIC(12, 2) NOT NULL,        --Ӧ���ܶ�(Ԫ)
  PAYMENT_AMOUNT             NUMERIC(12, 2) NOT NULL,        --Ӧ�����(Ԫ)
  FINISHED_AMOUNT            NUMERIC(12, 2) NOT NULL,        --�Ѹ����(Ԫ)
  KNOT_AMOUNT                NUMERIC(12, 2) NOT NULL,        --��׼�ڽ��(Ԫ)
  WALL_AMOUNT                NUMERIC(12, 2) NOT NULL,        --��ǽ���(Ԫ)
  AUTOCRANE_AMOUNT           NUMERIC(12, 2) NOT NULL,        --������(Ԫ)
  LGISTICS_AMOUNT            NUMERIC(12, 2) NOT NULL,        --����ѽ��(Ԫ)
  OTHER_AMOUNT               NUMERIC(12, 2) NOT NULL,        --������(Ԫ)
  PRACTI_AMOUNT              NUMERIC(12, 2) NOT NULL,        --��Ա���(Ԫ)
  FUND_STATUS                CHAR(1) NULL,                   --����״̬(����ֵ 0:���,1:������,2:�Ѹ���)
  EFFECTIVE                  CHAR(1) NOT NULL,               --��Ч��ʶ(����ֵ 0:δ��Ч,1:��Ч)
  USER_ID                    BIGINT NOT NULL,                --�Ǽ���ID
  USER_NAME                  VARCHAR(64) NOT NULL,           --�Ǽ���
  PROVIDED_DATE              CHAR(10) NOT NULL,              --�Ǽ�ʱ��
);
--�������-��׼��
CREATE TABLE T_TEAMS_ACCOUNT_KNOT
(
  ACCOUNT_KNOT_ID            BIGINT IDENTITY PRIMARY KEY,
  TEAMS_ACCOUNT_ID           BIGINT NULL,                    --�������ID
  ACCOUNT_DATE               CHAR(10) NULL,                  --����(�״ΰ�װ��ʼ����/��������/��ж����)
  KNOT_TYPE                  VARCHAR(64) NULL,               --����(�״ΰ�װ/����/��ж)
  RECORD_ID                  VARCHAR(24) NULL,               --�������
  BUILDING_NUM               VARCHAR(64) NULL,               --¥��
  COMPON_GENERIC             VARCHAR(6) NOT NULL,            --��������(���� BM_COMPONENT_GENERIC)
  COMPON_SPECIFIC            VARCHAR(6) NULL,                --����ͺ�(���� BM_COMPONENT_SPECIFIC)
  QUANTITY                   SMALLINT NOT NULL,              --����
  MEASUREMENT                VARCHAR(64) NOT NULL,           --��λ(��/��/̨)
  ACCOUNT_PRICE              NUMERIC(12, 2) NOT NULL,        --����
  DEDUCT_QUANTITY            SMALLINT NOT NULL,              --Ӧ������
  COUNTS                     SMALLINT NOT NULL,              --ԭʼ����
  KNOT_METRIC                NUMERIC(12, 2) NULL,            --��׼�ڳ���
  SUMMARY                    NUMERIC(12, 2) NOT NULL         --С��((����-Ӧ������)*����)
);
--�������-��ǽ
CREATE TABLE T_TEAMS_ACCOUNT_WALL
(
  ACCOUNT_WALL_ID            BIGINT IDENTITY PRIMARY KEY,
  TEAMS_ACCOUNT_ID           BIGINT NULL,                    --�������ID
  ACCOUNT_DATE               CHAR(10) NULL,                  --����(�״ΰ�װ��ʼ����/��������/��ж����)
  WALL_TYPE                  VARCHAR(64) NULL,               --����(�״ΰ�װ/����/��ж)
  RECORD_ID                  VARCHAR(24) NULL,               --�������
  BUILDING_NUM               VARCHAR(64) NULL,               --¥��
  COMPON_GENERIC             VARCHAR(6) NOT NULL,            --��������(���� BM_COMPONENT_GENERIC)
  COMPON_SPECIFIC            VARCHAR(6) NULL,                --����ͺ�(���� BM_COMPONENT_SPECIFIC)
  QUANTITY                   SMALLINT NOT NULL,              --����
  MEASUREMENT                VARCHAR(64) NOT NULL,           --��λ(��/��)
  ACCOUNT_PRICE              NUMERIC(12, 2) NOT NULL,        --����
  DEDUCT_QUANTITY            SMALLINT NOT NULL,              --Ӧ������
  SUMMARY                    NUMERIC(12, 2) NOT NULL         --С��((����-Ӧ������)*����)
);
--�������-���
CREATE TABLE T_TEAMS_ACCOUNT_AUTOCRANE
(
  ACCOUNT_AUTOCRANE_ID       BIGINT IDENTITY PRIMARY KEY,
  TEAMS_ACCOUNT_ID           BIGINT NULL,                    --�������ID
  ACCOUNT_DATE               CHAR(10) NULL,                  --����
  AMOUNT_TYPE                VARCHAR(128) NULL,              --�������
  SPECIFIC_NAME              VARCHAR(64) NULL,               --����ͺ�
  QUANTITY                   SMALLINT NOT NULL,              --����
  MEASUREMENT                VARCHAR(64) NOT NULL,           --��λ(̨)
  MACHINE_TEAM               VARCHAR(64) NULL,               --̨��
  ACCOUNT_PRICE              NUMERIC(12, 2) NOT NULL,        --����
  DEDUCT_QUANTITY            SMALLINT NOT NULL,              --Ӧ������
  SUMMARY                    NUMERIC(12, 2) NOT NULL         --С��((����-Ӧ������)*����)
);
--�������-�����
CREATE TABLE T_TEAMS_ACCOUNT_LOGISTICS
(
  ACCOUNT_LOGISTICSE_ID      BIGINT IDENTITY PRIMARY KEY,
  TEAMS_ACCOUNT_ID           BIGINT NULL,                    --�������ID
  AMOUNT_TYPE                VARCHAR(128) NULL,              --�������
  SPECIFIC_NAME              VARCHAR(64) NULL,               --����ͺ�
  QUANTITY                   SMALLINT NOT NULL,              --����
  MEASUREMENT                VARCHAR(64) NOT NULL,           --��λ(��)
  ACCOUNT_PRICE              NUMERIC(12, 2) NOT NULL,        --����
  SUMMARY                    NUMERIC(12, 2) NOT NULL         --С��
);
--�������-����
CREATE TABLE T_TEAMS_ACCOUNT_OTHER
(
  ACCOUNT_OTHERE_ID          BIGINT IDENTITY PRIMARY KEY,
  TEAMS_ACCOUNT_ID           BIGINT NULL,                    --�������ID
  OTHER_NAME                 VARCHAR(128) NULL,              --���
  SPECIFIC_NAME              VARCHAR(64) NULL,               --����ͺ�
  QUANTITY                   SMALLINT NOT NULL,              --����
  MEASUREMENT                VARCHAR(64) NOT NULL,           --��λ
  ACCOUNT_PRICE              NUMERIC(12, 2) NOT NULL,        --����
  SUMMARY                    NUMERIC(12, 2) NOT NULL         --С��
);
--�������-Ա��
CREATE TABLE T_TEAMS_ACCOUNT_PRACTI
(
  ACCOUNT_PRACTIE_ID         BIGINT IDENTITY PRIMARY KEY,
  TEAMS_ACCOUNT_ID           BIGINT NULL,                    --�������ID
  PRACTI_ID                  BIGINT NULL,                    --��Ա(��Դ��ҵ��Ա����)
  PRACTI_NAME                VARCHAR(32) NULL,               --��Ա����
  REMARK                     VARCHAR(256) NULL,              --��������
  BASE_SALARY                NUMERIC(12, 2) NOT NULL,        --��н
  PRESENT_AMOUNT             NUMERIC(12, 2) NOT NULL,        --��̯����
  DEDUCT_AMOUNT              SMALLINT NOT NULL,              --Ӧ�۽��
  SUMMARY                    NUMERIC(12, 2) NOT NULL         --�ϼ�(�ϼ�=��н+��̯����-Ӧ�۽��)
);
--�߿
CREATE TABLE T_OVERDUE_PAYMENT
(
  OVERDUE_PAYMENT_ID         BIGINT IDENTITY PRIMARY KEY,
  OVERDUE_PAYMENT_SERIAL     VARCHAR(64) NOT NULL,           --�߿���(CK+������+3λ��ˮ��)
  CUSTOMER_ID                BIGINT NULL,                    --���ⵥλ(��Դ�ͻ�����)
  CUSTOMER_NAME              VARCHAR(64) NULL,               --���ⵥλ
  CORP_ID                    BIGINT NULL,                    --���ⵥλ(��Դ��ҵ����)
  CORP_NAME                  VARCHAR(64) NULL,               --���ⵥλ
  CONTENTS                   TEXT NULL                       --�߿�����
);

INSERT INTO SYS_CONFIG (CONFIGKEY, FIELDSET, CONFIGNAME, CONFIGDESC, TYPENAME, DATATYPE, DATAVALUE, DELFLAG)
VALUES ('overdue.payment', '�߿ģ���ַ', '�߿ģ���ַ', '�߿ģ���ַ', 'TEXT', 0, '/overdue/payment.ftl', '0');
--2015-04-03
ALTER TABLE T_PRACTITIONER ADD CERT_FLAG CHAR(1) NOT NULL DEFAULT '1';
--ҵ������
CREATE TABLE T_CONTRACT_APPLICATION
(
  APPLICATION_ID             BIGINT IDENTITY PRIMARY KEY,
  APPLICATION_SERIAL         VARCHAR(64) NOT NULL,           --ҵ��������(YW+������+3λ��ˮ��)
  PROVINCE                   VARCHAR(6) NULL,                --����ʡ��(�����ֵ�����)
  CUSTOMER_ID                BIGINT NULL,                    --���ⵥλ(��Դ�ͻ�����)
  CUSTOMER_NAME              VARCHAR(64) NULL,               --���ⵥλ
  CUSTOMER_ADDRESS           VARCHAR(128) NULL,              --���ⵥλ��ַ
  LINKER                     VARCHAR(32) NULL,               --�ͻ���ϵ��
  LINKER_TEL                 VARCHAR(16) NULL,               --��ϵ�绰
  CORP_ID                    BIGINT NULL,                    --������˾(��Դ��ҵ����)
  CORP_NAME                  VARCHAR(64) NULL,               --������˾
  DUTYMAN                    VARCHAR(32) NULL,               --��˾������
  EQUIP_CATEGORY             VARCHAR(12) NULL,               --�豸���(���� BM_REPERTORY_CATEGORY)
  QUANTITY                   SMALLINT NULL,                  --����
  PROJECT_ID                 BIGINT NULL,                    --��ĿID(��Ŀ����)
  PROJECT_NAME               VARCHAR(64) NULL,               --��Ŀ���
  PROJECT_ADDRESS            VARCHAR(256) NULL,              --��Ŀ������(ʡ+��+��+�ֵ�)
  PROJECT_time_limit         VARCHAR(64) NULL,               --��Ŀ����
  OVERALL_HEIGHT             NUMERIC(12, 2) NULL,            --������߶�(m)
  PROJECT_STATUS             VARCHAR(64) NULL,               --������״
  START_DATE                 CHAR(10) NULL,                  --Ԥ�ƽ�ʱ��
  USER_ID                    BIGINT NOT NULL,                --�Ǽ���ID
  USER_NAME                  VARCHAR(64) NOT NULL,           --�Ǽ���
  APPLYFOR_STATE             CHAR(1) NOT NULL,               --����״̬(����ֵ 0:���ύ,1:������,2:������,3:���)
  PROVIDED_DATE              CHAR(10) NOT NULL               --��������
);
--ҵ�������豸
CREATE TABLE T_CONTRACT_APPLICATION_EQUIPMENT
(
  APPLICATION_EQUIP_ID       BIGINT IDENTITY PRIMARY KEY,
  APPLICATION_ID             BIGINT NULL,
  EQUIP_GENERIC_NAME         VARCHAR(64) NULL,               --�豸���
  EQUIP_VENDER               VARCHAR(128) NULL,              --����
  EQUIP_SPECIFIC_NAME        VARCHAR(64) NULL,               --�豸�ͺ�
  QUANTITY                   SMALLINT NULL,                  --����(̨)
  OVERALL_HEIGHT             NUMERIC(12, 2) NULL,            --����߶�(��)
  APPEARANCE_COST            NUMERIC(12, 2) NULL,            --���˳���(Ԫ/̨)
  EMBEDDED_COST              NUMERIC(12, 2) NULL,            --��Ԥ���(Ԫ/��)
  SETTLE_METHOD              VARCHAR(64) NULL                --���㷽ʽ
);
UPDATE E SET E.FLOW_ID = ED.FLOW_ID, E.PROJECT_NAME = ED.PROJECT_NAME
  FROM T_EQUIPMENT_FLOW EF, T_EQUIPMENT_DIARY ED, T_EQUIPMENT E
 WHERE EF.FLOW_ID = ED.FLOW_ID
   AND EF.FLOW_STATE > '0'
   AND EF.FLOW_STATE < '8'
   AND E.EQUIP_ID = ED.EQUIP_ID
--2015-04-08
ALTER TABLE T_COMPONENT_DIARY ALTER COLUMN DISMANTLE_STAUTS CHAR(1) NULL;
ALTER TABLE T_COMPONENT_DIARY ALTER COLUMN JACKING_STAUTS CHAR(1) NULL;
--2015-04-11
ALTER TABLE T_SETTLE_CONTRACT ADD TAX_AMOUNT NUMERIC(12, 2) NULL;
ALTER TABLE T_SETTLE_CONTRACT ADD TAX_RATE NUMERIC(12, 2) NULL;
--˰��
CREATE TABLE BM_TAX_RATE
(
  CODE  VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE VARCHAR(64) NOT NULL
);
INSERT INTO INIT_LOAD_TABLE VALUES('taxRate', 'BM_TAX_RATE', 1, 1, 1, 'CODE', 'VALUE', 0, NULL, NULL, NULL, '˰��');
--�������
CREATE TABLE T_RENT_CONTRACT
(
  RENT_ID                    BIGINT IDENTITY PRIMARY KEY,
  RENT_SERIAL                VARCHAR(64) NOT NULL,           --���㵥��
  RENT_THEME                 VARCHAR(96) NOT NULL,           --��������
  CONTRACT_ID                BIGINT NOT NULL,                --��ͬID
  CONTRACT_SERIAL            VARCHAR(64) NOT NULL,           --��ͬ���
  CONTRACT_THEME             VARCHAR(96) NOT NULL,           --��ͬ����
  PA_ENT                     BIGINT NOT NULL,                --����/�׷���λ(��ҵ����/�ͻ�����)
  PA_MODULE                  VARCHAR(32) NOT NULL,           --����/�׷�ģ��
  PA_ENT_NAME                VARCHAR(64) NOT NULL,           --����/�׷���λ���
  PB_ENT                     BIGINT NOT NULL,                --����/�ҷ���λ(��ҵ����/�ͻ�����)
  PB_MODULE                  VARCHAR(32) NOT NULL,           --����/�ҷ�ģ��
  PB_ENT_NAME                VARCHAR(64) NOT NULL,           --����/�ҷ���λ���
  PROJECT_ID                 BIGINT NULL,                    --��ĿID(��Ŀ����)
  PROJECT_SERIAL             VARCHAR(64) NULL,               --��Ŀ���
  PROJECT_NAME               VARCHAR(64) NOT NULL,           --��Ŀ���
  ADDRESS                    VARCHAR(256) NULL,              --��Ŀ������(ʡ+��+��+�ֵ�)
  START_RENT_DATE            CHAR(10) NOT NULL,              --������ʼʱ��
  END_RENT_DATE              CHAR(10) NOT NULL,              --�������ʱ��
  RENT_AMOUNT                NUMERIC(12, 2) NOT NULL,        --��������ܽ��
  DEDUCT_AMOUNT              NUMERIC(12, 2) NOT NULL,        --Ӧ���ܽ��
  PAYMENT_AMOUNT             NUMERIC(12, 2) NOT NULL,        --Ӧ���ܽ��
  FINISHED_AMOUNT            NUMERIC(12, 2) NOT NULL,        --��ɽ��
  FUND_STATUS                CHAR(1) NOT NULL,               --����״̬(����ֵ 0:���,1:������,2:�Ѹ���)
  EFFECTIVE                  CHAR(1) NOT NULL,               --��Ч��ʶ(����ֵ 0:δ��Ч,1:��Ч)
  REMARK                     VARCHAR(256) NULL,              --��ע
  USER_ID                    BIGINT NOT NULL,                --�Ǽ���ID
  USER_NAME                  VARCHAR(32) NOT NULL,           --�Ǽ���
  DEP_ID                     BIGINT NOT NULL,                --�������ܲ���
  PROVIDED_DATE              CHAR(10) NOT NULL               --�ʱ��
);
--��������豸�嵥
CREATE TABLE T_RENT_EQUIP_BRIEF
(
  RENT_EQUIP_BRIEF_ID        BIGINT IDENTITY PRIMARY KEY,
  RENT_ID                    BIGINT NULL,                    --����ID
  EQUIP_ID                   BIGINT NULL,                    --�����豸(�豸����)
  RECORD_SERIAL              VARCHAR(64) NULL,               --�豸���
  RECORD_ID                  VARCHAR(24) NULL,               --�������
  EXW_SERIAL                 VARCHAR(64) NULL,               --�������
  EQUIP_CATEGORY_NAME        VARCHAR(64) NOT NULL,           --�豸���/Ʒ��(���ñ��� BM_REPERTORY_CATEGORY)
  EQUIP_SPECIFIC_NAME        VARCHAR(64) NOT NULL,           --����ͺ�(���ñ��� BM_EQUIP_SPECIFIC)
  BUILDING_NUM               VARCHAR(64) NULL,               --¥��
  UNIT                       VARCHAR(16) NOT NULL,           --��λ
  START_RENT_DATE            CHAR(10) NOT NULL,              --������
  END_RENT_DATE              CHAR(10) NOT NULL,              --��ֹ��
  RENT_DAYS                  SMALLINT NOT NULL,              --�Ʒ�����
  RENT_STANDARD              NUMERIC(12, 2) NOT NULL,        --����׼
  MEASUREMENT                VARCHAR(6) NOT NULL,            --���λ
  QUANTITY                   SMALLINT NOT NULL,              --��������
  DAYS_RENT                  NUMERIC(12, 2) NOT NULL,        --�����
  DEDUCT_RENT                NUMERIC(12, 2) NOT NULL,        --Ӧ�����
  SUMMARY                    NUMERIC(12, 2) NOT NULL,        --����ۼ�
  REMARK                     VARCHAR(256) NULL               --��ע
);
--�������������嵥
CREATE TABLE T_RENT_COMPON_BRIEF
(
  RENT_COMPON_BRIEF_ID       BIGINT IDENTITY PRIMARY KEY,
  RENT_ID                    BIGINT NULL,                    --����ID
  COMPON_ID                  BIGINT NULL,                    --���������(���������)
  COMPON_CATEGORY_NAME       VARCHAR(64) NOT NULL,           --�豸���/Ʒ��(���ñ��� BM_REPERTORY_CATEGORY)
  COMPON_SPECIFIC_NAME       VARCHAR(64) NULL,               --�豸�ͺ�(���ñ��� BM_COMPONENT_SPECIFIC)
  UNIT                       VARCHAR(16) NOT NULL,           --��λ
  START_RENT_DATE            CHAR(10) NOT NULL,              --������
  END_RENT_DATE              CHAR(10) NOT NULL,              --��ֹ��
  RENT_DAYS                  SMALLINT NOT NULL,              --�Ʒ�����
  RENT_STANDARD              NUMERIC(12, 2) NOT NULL,        --����׼
  MEASUREMENT                VARCHAR(6) NOT NULL,            --���λ
  QUANTITY                   SMALLINT NOT NULL,              --��������
  DAYS_RENT                  NUMERIC(12, 2) NOT NULL,        --�����
  DEDUCT_RENT                NUMERIC(12, 2) NOT NULL,        --Ӧ�����
  SUMMARY                    NUMERIC(12, 2) NOT NULL,        --����ۼ�
  EQUIP_ID                   BIGINT NULL,                    --�����豸(�豸����)
  RECORD_ID                  VARCHAR(24) NULL,               --�������
  REMARK                     VARCHAR(256) NULL               --��ע
);
--���������������嵥
CREATE TABLE T_RENT_ITEM_BRIEF
(
  RENT_ITEM_BRIEF_ID         BIGINT IDENTITY PRIMARY KEY,
  RENT_ID                    BIGINT NULL,                    --����ID
  RENT_ITEM_NAME             VARCHAR(64) NOT NULL,           --������Ŀ
  QUANTITY                   SMALLINT NOT NULL,              --����
  UNITPRICE                  NUMERIC(12, 2) NOT NULL,        --���õ���
  MEASUREMENT                VARCHAR(16) NOT NULL,           --��������λ(���� BM_MEASUREMENT)
  DEDUCT_RENT                NUMERIC(12, 2) NOT NULL,        --Ӧ�����
  ITEM_CUMULATE              NUMERIC(12, 2) NOT NULL,        --�����ۼ�
  SUMMARY                    NUMERIC(12, 2) NOT NULL,        --����ۼ�
  EQUIP_ID                   BIGINT NULL,                    --�����豸(�豸����)
  RECORD_ID                  VARCHAR(24) NULL,               --�������
  REMARK                     VARCHAR(256) NULL               --��ע
);
--�������۷��嵥
CREATE TABLE T_RENT_DEDUCT_BRIEF
(
  RENT_DEDUCT_BRIEF_ID       BIGINT IDENTITY PRIMARY KEY,
  RENT_ID                    BIGINT NULL,                    --����ID
  EQUIP_ID                   BIGINT NULL,                    --�����豸(�豸����)
  EQUIP_CATEGORY_NAME        VARCHAR(64) NOT NULL,           --�豸���/Ʒ��(���ñ��� BM_REPERTORY_CATEGORY)
  EQUIP_SPECIFIC_NAME        VARCHAR(64) NOT NULL,           --����ͺ�(���ñ��� BM_EQUIP_SPECIFIC)
  RECORD_ID                  VARCHAR(24) NULL,               --�������
  QUANTITY                   SMALLINT NOT NULL,              --����
  UNITPRICE                  NUMERIC(12, 2) NOT NULL,        --����
  MEASUREMENT                VARCHAR(16) NOT NULL,           --������λ(���� BM_MEASUREMENT)
  SUMMARY                    NUMERIC(12, 2) NOT NULL,        --Ӧ���ۼ�
  REMARK                     VARCHAR(256) NULL               --�۷�˵��
);
ALTER TABLE T_PRACTITIONER ALTER COLUMN DEP_ID BIGINT NULL;
ALTER TABLE T_PRACTITIONER ALTER COLUMN SEX CHAR(1) NULL;
ALTER TABLE T_PRACTITIONER ALTER COLUMN ID_CARD VARCHAR(18) NULL;
ALTER TABLE T_PRACTITIONER ALTER COLUMN STATION VARCHAR(32) NULL;
ALTER TABLE T_PRACTITIONER ALTER COLUMN KIND_WORK VARCHAR(6) NULL;
ALTER TABLE T_PRACTITIONER ALTER COLUMN BASE_SALARY NUMERIC(12, 2) NULL;
ALTER TABLE T_PRACTITIONER ALTER COLUMN CERT_FLAG CHAR(1) NULL;

ALTER TABLE T_EQUIPMENT ALTER COLUMN DEPRECIATE_RATE NUMERIC(5, 2) NOT NULL;
ALTER TABLE T_EQUIPMENT ALTER COLUMN TOTAL_RATE NUMERIC(5, 2) NOT NULL;
ALTER TABLE T_COMPONENT ALTER COLUMN DEPRECIATE_RATE NUMERIC(5, 2) NOT NULL;
ALTER TABLE T_COMPONENT ALTER COLUMN TOTAL_RATE NUMERIC(5, 2) NOT NULL;

ALTER TABLE T_COMPONENT_DIARY ADD CONSUME_FLAG CHAR(1) NOT NULL DEFAULT '0';
ALTER TABLE T_COMPONENT_DIARY ADD PARACHUTE_FLAG CHAR(1) NOT NULL DEFAULT '0';
ALTER TABLE T_COMPONENT_DIARY ADD WALL_ATTACHE_FLAG CHAR(1) NOT NULL DEFAULT '0';
ALTER TABLE T_COMPONENT_DIARY ADD KNOT_FLAG CHAR(1) NOT NULL DEFAULT '0';
ALTER TABLE T_COMPONENT_DIARY ADD KNOT_METRIC NUMERIC(12, 2) NULL;
ALTER TABLE T_COMPONENT_DIARY ADD BRACHIUM NUMERIC(12, 2) NULL;
UPDATE CD SET CD.CONSUME_FLAG = C.CONSUME_FLAG, CD.PARACHUTE_FLAG = C.PARACHUTE_FLAG, CD.WALL_ATTACHE_FLAG = C.WALL_ATTACHE_FLAG, CD.KNOT_FLAG = C.KNOT_FLAG, CD.KNOT_METRIC = C.KNOT_METRIC, CD.BRACHIUM = C.BRACHIUM FROM T_COMPONENT_DIARY CD, T_COMPONENT C WHERE CD.COMPON_ID = C.COMPON_ID;

EXEC SP_RENAME 'T_STORE_EQUIP_STOCK.[STOCK_ID]','EQUIP_STOCK_ID','COLUMN';
--����������Ϣ
CREATE TABLE T_STORE_COMPON_STOCK
(
  COMPON_STOCK_ID            BIGINT IDENTITY PRIMARY KEY,
  STORE_ID                   BIGINT NULL,                    --�ֿ�ID
  COMPON_ID                  BIGINT NOT NULL,                --�����Ϣ(�������)
  PROJECT_ID                 BIGINT NULL,                    --��ĿID(��Ŀ����)
  COUNTS                     SMALLINT NOT NULL,              --��������
  BOUND_DATE                 CHAR(10) NULL,                  --�����ʱ��
  STOCK_TYPE                 CHAR(1) NOT NULL                --���������(����ֵ 2:����,5:���)
);
ALTER TABLE T_EQUIPMENT_WAREHOUSE_COMPON ALTER COLUMN WAREHOUSE_ID BIGINT NULL;

ALTER TABLE T_COMPONENT ADD LEFTCAGE_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_COMPONENT ADD LEFTCAGE_CHECK_DATE CHAR(10) NULL;
ALTER TABLE T_COMPONENT ADD RIGHTCAGE_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_COMPONENT ADD RIGHTCAGE_CHECK_DATE CHAR(10) NULL;

ALTER TABLE T_STORE_COMPON_STOCK ALTER COLUMN STORE_ID BIGINT NULL;
--2015-05-06
ALTER TABLE T_TEAMS_ACCOUNT ALTER COLUMN ACCOUNT_START_DATE SMALLDATETIME NULL;
ALTER TABLE T_TEAMS_ACCOUNT ALTER COLUMN ACCOUNT_END_DATE SMALLDATETIME NULL;

ALTER TABLE T_TEAMS_ACCOUNT_KNOT ADD PROJECT_ID BIGINT NULL;
ALTER TABLE T_TEAMS_ACCOUNT_KNOT ADD PROJECT_NAME VARCHAR(64) NULL;
ALTER TABLE T_TEAMS_ACCOUNT_KNOT ADD PRACTI_ID BIGINT NULL;
ALTER TABLE T_TEAMS_ACCOUNT_KNOT ADD PRACTI_NAME VARCHAR(32) NULL;

ALTER TABLE T_TEAMS_ACCOUNT_WALL ADD PROJECT_ID BIGINT NULL;
ALTER TABLE T_TEAMS_ACCOUNT_WALL ADD PROJECT_NAME VARCHAR(64) NULL;
ALTER TABLE T_TEAMS_ACCOUNT_WALL ADD PRACTI_ID BIGINT NULL;
ALTER TABLE T_TEAMS_ACCOUNT_WALL ADD PRACTI_NAME VARCHAR(32) NULL;

ALTER TABLE T_TEAMS_ACCOUNT_AUTOCRANE ADD PROJECT_ID BIGINT NULL;
ALTER TABLE T_TEAMS_ACCOUNT_AUTOCRANE ADD PROJECT_NAME VARCHAR(64) NULL;
ALTER TABLE T_TEAMS_ACCOUNT_AUTOCRANE ADD PRACTI_ID BIGINT NULL;
ALTER TABLE T_TEAMS_ACCOUNT_AUTOCRANE ADD PRACTI_NAME VARCHAR(32) NULL;

ALTER TABLE T_TEAMS_ACCOUNT_LOGISTICS ADD PROJECT_ID BIGINT NULL;
ALTER TABLE T_TEAMS_ACCOUNT_LOGISTICS ADD PROJECT_NAME VARCHAR(64) NULL;
ALTER TABLE T_TEAMS_ACCOUNT_LOGISTICS ADD PRACTI_ID BIGINT NULL;
ALTER TABLE T_TEAMS_ACCOUNT_LOGISTICS ADD PRACTI_NAME VARCHAR(32) NULL;

ALTER TABLE T_TEAMS_ACCOUNT_OTHER ADD PROJECT_ID BIGINT NULL;
ALTER TABLE T_TEAMS_ACCOUNT_OTHER ADD PROJECT_NAME VARCHAR(64) NULL;
ALTER TABLE T_TEAMS_ACCOUNT_OTHER ADD PRACTI_ID BIGINT NULL;
ALTER TABLE T_TEAMS_ACCOUNT_OTHER ADD PRACTI_NAME VARCHAR(32) NULL;

ALTER TABLE T_TEAMS_ACCOUNT_PRACTI ADD PROJECT_ID BIGINT NULL;
ALTER TABLE T_TEAMS_ACCOUNT_PRACTI ADD PROJECT_NAME VARCHAR(64) NULL;
--2015-05-10
ALTER TABLE T_EQUIPMENT_REPAIR ALTER COLUMN REPAIR_MAN VARCHAR(256) NULL;
ALTER TABLE T_EQUIPMENT_ACTIVATE ALTER COLUMN ACTIVATE_DATE SMALLDATETIME NOT NULL;
ALTER TABLE T_EQUIPMENT_BLOCKUP ALTER COLUMN BLOCKUP_DATE SMALLDATETIME NOT NULL;

ALTER TABLE T_PRACTITIONER ADD DIVISION_DATE CHAR(10) NULL;
ALTER TABLE T_PRACTITIONER ADD SEPARATION_DATE CHAR(10) NULL;
ALTER TABLE T_PRACTITIONER ADD INCUMBENT CHAR(1) NULL;

ALTER TABLE BM_EQUIP_SPECIFIC ADD NAME VARCHAR(30) NULL;
DELETE FROM INIT_LOAD_TABLE WHERE TABLE_ALIAS = 'equipSpecific';
INSERT INTO INIT_LOAD_TABLE VALUES('equipSpecific', 'BM_EQUIP_SPECIFIC', 1, 1, 1, 'CODE', 'VALUE', 0, NULL, 'NAME', 'ʹ������', '�豸����ͺ�');

ALTER TABLE T_EQUIPMENT_REPAIR ADD BUILDING_NUM VARCHAR(64) NULL;
ALTER TABLE T_EQUIPMENT_REPAIR ALTER COLUMN SCHEMA_NAME VARCHAR(4000) NULL;

ALTER TABLE T_EQUIPMENT_EMPLOY DROP COLUMN KNOT_COUNTS;
ALTER TABLE T_EQUIPMENT_EMPLOY DROP COLUMN WALL_ATTACHE_QTY;
ALTER TABLE T_EQUIPMENT_EMPLOY DROP COLUMN INSTALL_HEIGHT;
--2015-05-12
--����/�����
CREATE TABLE T_CONTRACT_APPLICATION_PLAN
(
  PLAN_ID                    BIGINT IDENTITY PRIMARY KEY,
  APPLICATION_ID             BIGINT NULL,
  PLAN_TYPE                  CHAR(1) NOT NULL,               --����(����ֵ 0:����,1:���)
  RECEIVE_ENT_NAME           VARCHAR(64) NULL,               --���ⵥλ
  PROJECT_NAME               VARCHAR(64) NULL,               --��Ŀ���
  DEMAND                     VARCHAR(64) NULL,               --��ĿҪ��
  INSTALL_HEIGHT             NUMERIC(12, 2) NULL,            --��װ�߶�
  DURATION                   NUMERIC(12, 2) NULL,            --��װʱ��(��)
  EQUIP_SPECIFIC_NAME        VARCHAR(64) NULL,               --�豸�ͺ�
  BASE_DESCRIBE              VARCHAR(256) NULL,              --��
  PROPERTY_NAME              VARCHAR(64) NULL,               --��Ȩ
  EQUIP_SOURCE               VARCHAR(6) NULL,                --�豸��Դ
  EQUIP_VENDER               VARCHAR(128) NULL,              --�豸Ʒ��
  IC_SERIAL                  VARCHAR(64) NULL,               --IC���
  REMARK                     VARCHAR(256) NULL               --��ע
);
--2015-05-13
ALTER TABLE SHORT_MESSAGE ALTER COLUMN CONTENT TEXT NOT NULL;
ALTER TABLE T_PURCHASE_BRIEF ADD COMPON_ID BIGINT NULL;
ALTER TABLE T_PURCHASE ADD APPLICANT VARCHAR(64) NULL;
--�豸��ע������Ϣ
CREATE TABLE T_EQUIPMENT_AFFILIATED
(
  EQUIP_AFFILIATED_ID        BIGINT IDENTITY PRIMARY KEY,
  EQUIP_ID                   BIGINT NULL,                    --�豸��ʶ
  COMPON_CATEGORY_NAME       VARCHAR(64) NULL,               --������
  COMPON_GENERIC_NAME        VARCHAR(64) NULL,               --������
  COMPON_SPECIFIC_NAME       VARCHAR(64) NULL,               --����ͺ�
  REMARK                     VARCHAR(256) NULL               --��ע
);
--2015-05-14
ALTER TABLE T_LOGISTICS_TRANDETAIL ALTER COLUMN TRANSPORT_ID BIGINT NULL;
ALTER TABLE T_EQUIPMENT_REPAIR ALTER COLUMN PROVIDED_DATE SMALLDATETIME NOT NULL;
ALTER TABLE T_EQUIPMENT_REPAIR ADD PHENOMENON VARCHAR(512) NULL;
ALTER TABLE T_EQUIPMENT_REPAIR ADD RUNNING_STATE CHAR(1) NULL;
ALTER TABLE T_EQUIPMENT_REPAIR ADD LICENSE_PLATE VARCHAR(16) NULL;

ALTER TABLE T_EQUIPMENT_REPAIR_LOCATION ADD LABOUR_CHARGES NUMERIC(12, 2) NULL;
ALTER TABLE T_EQUIPMENT_REPAIR_LOCATION ADD REMARK VARCHAR(256) NULL;

ALTER TABLE T_EQUIPMENT_REPAIR_COMPON ADD UNIT_PRICE NUMERIC(12, 2) NOT NULL DEFAULT 0;
ALTER TABLE T_EQUIPMENT_REPAIR_COMPON ADD SUMMARY NUMERIC(12, 2) NOT NULL DEFAULT 0;

ALTER TABLE T_DISPATCH ADD ENT_MANAGER VARCHAR(32) NULL;
ALTER TABLE T_DISPATCH_EQUIP ADD INSTALL_HEIGHT NUMERIC(12, 2) NULL;
ALTER TABLE T_LOGISTICS_TRANDETAIL ADD SIGN_COUNTS SMALLINT NOT NULL DEFAULT 0;

ALTER TABLE T_EQUIPMENT_INSPECT_DETAIL ADD POSITION VARCHAR(128) NULL;
ALTER TABLE T_EQUIPMENT_INSPECT_DETAIL ALTER COLUMN SUBSTANCE VARCHAR(512) NULL;
INSERT INTO BM_VITEM_TYPE VALUES('SEV', '������չ���');
INSERT INTO BM_VITEM_TYPE VALUES('TEV', '�������չ���');
INSERT INTO BM_VITEM_TYPE VALUES('SEI', '���Ѳ�����');
INSERT INTO BM_VITEM_TYPE VALUES('TEI', '����Ѳ�����');
--����嵥
CREATE TABLE T_DISPATCH_ALLOCATE
(
  DISPATCH_ALLOCATE_ID       BIGINT IDENTITY PRIMARY KEY,
  DISPATCH_ID                BIGINT NULL,                    --����ID
  ALLOCATE_TYPE              CHAR(1) NOT NULL,               --����(����ֵ T:����,S:���)
  COMPON_GENERIC_NAME        VARCHAR(64) NULL,               --������
  CALCULATE                  VARCHAR(8) NULL,                --��λ
  QUANTITY                   SMALLINT NULL,                  --����
  REMARK                     VARCHAR(256) NULL               --��ע
);
INSERT INTO INIT_LOAD_TABLE VALUES('autocraneDepend', 'BM_AUTOCRANE_DEPEND', 1, 1, 1, 'CODE', 'VALUE', 0, NULL, NULL, NULL, '���������λ');
--���������λ
CREATE TABLE BM_AUTOCRANE_DEPEND
(
  CODE  VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE VARCHAR(64) NOT NULL
);
ALTER TABLE T_DISPATCH ADD AUTOCRANE_DEPEND VARCHAR(6) NULL;
ALTER TABLE T_INDIS_PROTOCOL_EQUIP ADD HEIGHT NUMERIC(12, 2) NULL;
ALTER TABLE T_COMPONENT_DIARY ADD BACKSPORT_COUNTS SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE T_COMPONENT_DIARY ADD BACKSPORT_STATUS CHAR(1) NOT NULL DEFAULT '0';
--2015-05-23
ALTER TABLE T_LOGISTICS_TRANSPORT ALTER COLUMN TRANSPORT_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_LOGISTICS_TRANSPORT ADD SUMMARY NUMERIC(12, 2) NULL;
ALTER TABLE T_LOGISTICS_BACKSPORT ALTER COLUMN BACKSPORT_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_LOGISTICS_BACKSPORT ADD SUMMARY NUMERIC(12, 2) NULL;

ALTER TABLE T_LOGISTICS_TRANSPORT ADD AUTOCRANE_DEPEND VARCHAR(6) NULL;
ALTER TABLE T_LOGISTICS_TRANSPORT ADD KILOMETERS VARCHAR(16) NULL;
ALTER TABLE T_LOGISTICS_BACKSPORT ADD AUTOCRANE_DEPEND VARCHAR(6) NULL;
ALTER TABLE T_LOGISTICS_BACKSPORT ADD KILOMETERS VARCHAR(16) NULL;

--��������������嵥
CREATE TABLE T_LOGISTICS_TRANCARFEE
(
  TRANCARFEE_ID              BIGINT IDENTITY PRIMARY KEY,
  TRANSPORT_ID               BIGINT NULL,                    --��������ID
  CAR_ID                     BIGINT NULL,                    --���䳵��
  LICENSE_PLATE              VARCHAR(16) NULL,               --����(��Դ��������,�û�Ҳ���ֶ�����)
  SEDAN                      VARCHAR(32) NULL,               --����
  PROPERTY_NAME              VARCHAR(64) NULL,               --��Ȩ����
  AMOUNT                     NUMERIC(12, 2) NOT NULL,        --����
  REMARK                     VARCHAR(512) NULL               --��ע
);
--�����س�������嵥
CREATE TABLE T_LOGISTICS_BACKCARFEE
(
  BACKCARFEE_ID              BIGINT IDENTITY PRIMARY KEY,
  BACKSPORT_ID               BIGINT NULL,                    --�����س�ID
  CAR_ID                     BIGINT NULL,                    --���䳵��
  LICENSE_PLATE              VARCHAR(16) NULL,               --����(��Դ��������,�û�Ҳ���ֶ�����)
  SEDAN                      VARCHAR(32) NULL,               --����
  PROPERTY_NAME              VARCHAR(64) NULL,               --��Ȩ����
  AMOUNT                     NUMERIC(12, 2) NOT NULL,        --����
  REMARK                     VARCHAR(512) NULL               --��ע
);
--2015-06-04
ALTER TABLE T_SETTLE_COMPON_BRIEF ADD BUILDING_NUM VARCHAR(64) NULL;
ALTER TABLE T_SETTLE_ITEM_BRIEF ADD BUILDING_NUM VARCHAR(64) NULL;
--2015-06-05
ALTER TABLE T_EQUIPMENT_REPAIR_LOCATION ALTER COLUMN REPAIR_ID BIGINT NULL;
--2015-06-06
--ʩ����ҵ��
CREATE TABLE T_CONSTRUCT_OPERATION
(
  CONSTRUCT_ID               BIGINT IDENTITY PRIMARY KEY,
  CONSTRUCT_SERIAL           VARCHAR(64) NOT NULL,           --���(SG+������+2λ��ˮ��)
  USER_NAME                  VARCHAR(32) NOT NULL,           --���
  PROVIDED_DATE              CHAR(10) NOT NULL,              --�����
  PROJECT_ID                 BIGINT NULL,                    --��ĿID(��ͬ��Ϣ��Ŀ)
  BUILDING_NUM               VARCHAR(64) NULL,               --¥��
  EQUIP_ID                   BIGINT NULL,                    --�������(�����豸����)
  PA_ENT_NAME                VARCHAR(64) NULL,               --ʹ�õ�λ(Ĭ�Ϻ�ͬ���ⷽ-��Դ�ͻ�����)
  PB_ENT_NAME                VARCHAR(64) NULL,               --��װ��λ(Ĭ�Ϻ�ͬ���ⷽ-��Դ��ҵ��Ϣ)
  PRACTI_NAMES               VARCHAR(512) NULL,              --��ҵ��Ա(��ԴԱ������ ��ѡ)
  SUMMARY                    NUMERIC(12, 2) NULL,            --���úϼ�(���񵥺ϼ�֮��)
  REMARK                     VARCHAR(256) NULL               --��ע
);
--ʩ����ҵ������
CREATE TABLE T_CONSTRUCT_OPERATION_TASK
(
  CONSTRUCT_TASK_ID          BIGINT IDENTITY PRIMARY KEY,
  CONSTRUCT_ID               BIGINT NULL,                    --ʩ����ҵ��ID
  CONTENTS                   VARCHAR(1024) NULL,             --��������
  UNIT                       VARCHAR(32) NULL,               --��λ
  QUANTITY                   SMALLINT NOT NULL,              --����
  UNIT_PRICE                 NUMERIC(12, 2) NOT NULL,        --����
  SUMMARY                    NUMERIC(12, 2) NOT NULL,        --�ϼ�(����*����)
  REMARK                     VARCHAR(256) NULL               --��ע  
);
ALTER TABLE T_PURCHASE_BRIEF ADD BRAND VARCHAR(128) NULL;
ALTER TABLE T_PICKUP ADD EQUIP_ID BIGINT NULL;

ALTER TABLE T_PICKUP_COMPONENT ADD UNIT VARCHAR(32) NULL;
ALTER TABLE T_PICKUP_COMPONENT ADD QUANTITY SMALLINT NULL;
ALTER TABLE T_PICKUP_COMPONENT ADD UNIT_PRICE NUMERIC(12, 2) NULL;
ALTER TABLE T_PICKUP_COMPONENT ADD SUMMARY NUMERIC(12, 2) NULL;

ALTER TABLE T_AMOUNT_PAYMENT ADD RECORD_ID VARCHAR(24) NULL;

ALTER TABLE T_RENT_CONTRACT ADD CONTRACTOR VARCHAR(64) NULL;
ALTER TABLE T_RENT_CONTRACT ADD PROPERTY_NAME VARCHAR(64) NULL;

ALTER TABLE T_EQUIPMENT_INSTALL ADD PARTAKE VARCHAR(512) NULL;
ALTER TABLE T_EQUIPMENT_EMPLOY ADD PARTAKE VARCHAR(512) NULL;
ALTER TABLE T_EQUIPMENT_DISMANTLE ADD PARTAKE VARCHAR(512) NULL;

ALTER TABLE T_PROJECT ALTER COLUMN OVERALL_HEIGHT NUMERIC(12, 2) NOT NULL;
--2015-06-19
ALTER TABLE T_EQUIPMENT_EMPLOY ALTER COLUMN END_PLAN_DATE SMALLDATETIME NULL;
ALTER TABLE T_EQUIPMENT_EMPLOY ALTER COLUMN EMPLOY_DATE SMALLDATETIME NULL;

ALTER TABLE T_SETTLE_EQUIP_BRIEF ALTER COLUMN DAYS_RENT NUMERIC(12, 3) NOT NULL;
ALTER TABLE T_SETTLE_COMPON_BRIEF ALTER COLUMN DAYS_RENT NUMERIC(12, 3) NOT NULL;
ALTER TABLE T_SETTLE_ITEM_BRIEF ALTER COLUMN UNITPRICE NUMERIC(12, 3) NOT NULL;
--2015-06-25
ALTER TABLE T_COMPONENT_DIARY ADD RECORD_ID VARCHAR(24) NULL;
ALTER TABLE T_COMPONENT_DIARY ADD DISPATCH_USER_NAME VARCHAR(32) NULL;

ALTER TABLE T_COMPONENT ADD UNITPRICE NUMERIC(12, 2) NULL;
--2015-06-27
CREATE TABLE BM_CONTRACT_COSTITEM
(
  CODE  VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE VARCHAR(64) NOT NULL
);
INSERT INTO INIT_LOAD_TABLE VALUES('contractCostitem', 'BM_CONTRACT_COSTITEM', 1, 1, 1, 'CODE', 'VALUE', 0, NULL, NULL, NULL, '��ͬ��Ŀ����');
ALTER TABLE T_EQUIPMENT_FLOW ADD EMPLOY_INSPECT_SCHEMA_ID BIGINT NULL;

ALTER TABLE T_DISPATCH ADD RECORD_ID VARCHAR(24) NULL;
ALTER TABLE T_DISPATCH ADD EXW_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_EQUIPMENT_INSPECT ADD LICENSE_PLATE VARCHAR(16) NULL;

EXEC SP_RENAME 'T_EQUIPMENT_INSTALL.[MANAGER_ID]','PRINCIPAL_ID','COLUMN';
EXEC SP_RENAME 'T_EQUIPMENT_INSTALL.[MANAGER]','PRINCIPAL','COLUMN';
EXEC SP_RENAME 'T_EQUIPMENT_INSTALL.[MANAGER_TEL]','PRINCIPAL_TEL','COLUMN';
EXEC SP_RENAME 'T_EQUIPMENT_EMPLOY.[MANAGER_ID]','PRINCIPAL_ID','COLUMN';
EXEC SP_RENAME 'T_EQUIPMENT_EMPLOY.[MANAGER]','PRINCIPAL','COLUMN';
EXEC SP_RENAME 'T_EQUIPMENT_EMPLOY.[MANAGER_TEL]','PRINCIPAL_TEL','COLUMN';
EXEC SP_RENAME 'T_EQUIPMENT_DISMANTLE.[MANAGER_ID]','PRINCIPAL_ID','COLUMN';
EXEC SP_RENAME 'T_EQUIPMENT_DISMANTLE.[MANAGER]','PRINCIPAL','COLUMN';
EXEC SP_RENAME 'T_EQUIPMENT_WAREHOUSE.[MANAGER]','PRINCIPAL','COLUMN';
EXEC SP_RENAME 'T_EQUIPMENT_WAREHOUSE.[MANAGER_TEL]','PRINCIPAL_TEL','COLUMN';
--2015-06-29
ALTER TABLE T_DISPATCH ADD FUND_STATUS CHAR(1) NOT NULL DEFAULT '0';
ALTER TABLE T_AMOUNT_PAYMENT ALTER COLUMN RECEIVE_ID BIGINT NULL;
--����쳣
CREATE TABLE T_EQUIPMENT_WAREHOUSE_ABNORMAL
(
  ABNORMAL_ID                BIGINT IDENTITY PRIMARY KEY,
  WAREHOUSE_ID               BIGINT NULL,        
  PROJECT_NAME               VARCHAR(64) NULL,               --��Ŀ���
  ADDRESS                    VARCHAR(256) NULL,              --��Ŀ������
  PRINCIPAL                  VARCHAR(32) NULL,               --������
  RECORD_ID                  VARCHAR(24) NULL,               --�������
  EQUIP_GENERIC_NAME         VARCHAR(64) NULL,               --�豸���
  EQUIP_SPECIFIC_NAME        VARCHAR(64) NULL,               --����ͺ�
  EXW_SERIAL                 VARCHAR(64) NULL                --�������
);
--����쳣��ϸ
CREATE TABLE T_EQUIPMENT_WAREHOUSE_ABNORMAL_COMPON
(
  ABNORMAL_COMPON_ID         BIGINT IDENTITY PRIMARY KEY,
  ABNORMAL_ID                BIGINT NULL,
  COMPON_GENERIC_NAME        VARCHAR(64) NOT NULL,           --��������
  COMPON_SPECIFIC_NAME       VARCHAR(64) NULL,               --�豸�ͺ�
  DIMENSIONS                 VARCHAR(64) NULL,               --�������
  CALCULATE                  VARCHAR(8) NOT NULL,            --������λ  
  DISPATCH_COUNTS            SMALLINT NOT NULL,              --��������
  WAREHOUSE_WAIT_COUNTS      SMALLINT NOT NULL,              --���������
  WAREHOUSE_COUNTS           SMALLINT NOT NULL,              --�������
  WAREHOUSE_RESULT_NAME      VARCHAR(64) NOT NULL,           --���ս��
  STATUS_NAME                VARCHAR(64) NOT NULL            --���״̬
);
ALTER TABLE T_PRACTI_CREDIT ALTER COLUMN DESCRIPTION VARCHAR(4000) NULL;
ALTER TABLE T_AMOUNT_RECEIVE ALTER COLUMN RECEIVE_ENT_ACCOUNT_ID BIGINT NULL;
--2015-07-03
ALTER TABLE T_INVOICE_ISSUE ALTER COLUMN INVOICE_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_AMOUNT_RECEIVE ALTER COLUMN AMOUNT_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_INVOICE_COLLECT ALTER COLUMN INVOICE_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_AMOUNT_PAYMENT ALTER COLUMN AMOUNT_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_DISPATCH ALTER COLUMN PROJECT_MANAGER VARCHAR(32) NULL;
ALTER TABLE T_PROJECT ALTER COLUMN OVERALL_HEIGHT NUMERIC(12, 2) NULL;
ALTER TABLE T_CAR ADD ID_CARD VARCHAR(18) NULL;

ALTER TABLE T_EQUIPMENT_INSPECT ADD REPAIR_STATUS CHAR(1) NOT NULL DEFAULT '0';
ALTER TABLE T_EQUIPMENT_MAINT ADD REPAIR_STATUS CHAR(1) NOT NULL DEFAULT '0';
--2015-07-09
ALTER TABLE T_AMOUNT_RECEIVE ALTER COLUMN RECEIVE_BANK VARCHAR(64) NULL;
ALTER TABLE T_AMOUNT_RECEIVE ALTER COLUMN RECEIVE_ACCOUNT VARCHAR(32) NULL;

ALTER TABLE T_COMPONENT_DIARY ADD JACKING_COUNTS SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE T_COMPONENT_DIARY ADD DISMANTLE_COUNTS SMALLINT NOT NULL DEFAULT 0;
--2015-07-18
ALTER TABLE T_COMPONENT ALTER COLUMN PURCHASE_DATE SMALLDATETIME NULL;
ALTER TABLE T_COMPONENT ALTER COLUMN DEPRECIATE_DATE CHAR(10) NULL;
ALTER TABLE T_COMPONENT ADD COMPON_CODE VARCHAR(64) NULL;
ALTER TABLE T_COMPONENT ADD PERIOD_RESERVE SMALLINT NULL;

ALTER TABLE T_DISPATCH_ALLOCATE ADD DEFECTIVE VARCHAR(16) NULL;
ALTER TABLE T_DISPATCH_ALLOCATE ADD REISSUE VARCHAR(16) NULL;
ALTER TABLE T_DISPATCH_ALLOCATE ADD VERIFY VARCHAR(16) NULL;
ALTER TABLE T_DISPATCH_ALLOCATE ADD SPECIFICATION VARCHAR(16) NULL;

ALTER TABLE T_BORROW_COMPONENT ADD BORROW_COUNTS SMALLINT NULL;
ALTER TABLE T_BORROW_COMPONENT ADD CONSUME_COUNTS SMALLINT NULL;

ALTER TABLE T_EQUIPMENT ALTER COLUMN LICENSE_NUMBER VARCHAR(24) NULL;

ALTER TABLE T_CONTRACT_LEASE ADD COLLECTION_RATIO VARCHAR(2) NULL;
ALTER TABLE T_SETTLE_CONTRACT ADD COLLECTION_RATIO VARCHAR(2) NULL;
--2015-07-20
ALTER TABLE T_TECHNICAL_DISCLOSURE ADD PROJECT_ID BIGINT NULL;
ALTER TABLE T_TECHNICAL_DISCLOSURE ADD EQUIP_ID BIGINT NULL;
UPDATE TD SET TD.PROJECT_ID = ED.PROJECT_ID, TD.EQUIP_ID = ED.EQUIP_ID FROM T_TECHNICAL_DISCLOSURE TD, T_EQUIPMENT_DIARY ED WHERE TD.FLOW_ID = ED.FLOW_ID;
ALTER TABLE T_TECHNICAL_DISCLOSURE ALTER COLUMN PROJECT_ID BIGINT NOT NULL;
ALTER TABLE T_TECHNICAL_DISCLOSURE ALTER COLUMN EQUIP_ID BIGINT NOT NULL;
ALTER TABLE T_TECHNICAL_DISCLOSURE DROP COLUMN FLOW_ID;

--2015-08-08
ALTER TABLE T_PRACTITIONER ADD BANK_DEPOSIT VARCHAR(64) NULL;
ALTER TABLE T_PRACTITIONER ADD ACCOUNT VARCHAR(32) NULL;
ALTER TABLE T_COMPONENT ALTER COLUMN CONSUME_COUNTS INT NOT NULL;

ALTER TABLE T_EQUIPMENT_BLOCKUP ADD EFFECTIVE CHAR(1) NOT NULL DEFAULT '1';
ALTER TABLE T_SETTLE_CONTRACT ADD SITES_PRINCIPAL VARCHAR(64) NULL;

ALTER TABLE T_INVOICE_ISSUE DROP CONSTRAINT  UQ_T_INVOICE_ISSUE1
ALTER TABLE T_AMOUNT_RECEIVE DROP CONSTRAINT  UQ_T_AMOUNT_RECEIVE1
ALTER TABLE T_INVOICE_COLLECT DROP CONSTRAINT  UQ_T_INVOICE_COLLECT1
ALTER TABLE T_AMOUNT_PAYMENT DROP CONSTRAINT  UQ_T_AMOUNT_PAYMENT1
--2015-08-12
ALTER TABLE T_REIMBURSE ALTER COLUMN DESCRIPTION VARCHAR(1024) NULL;
ALTER TABLE T_AMOUNT_PAYMENT ADD FEES_TYPE VARCHAR(6) NULL;
ALTER TABLE T_AMOUNT_PAYMENT ADD PAYMENT_CONTENT VARCHAR(512) NULL;
--2015-08-16
ALTER TABLE T_PRACTI_DIARY ALTER COLUMN STATION VARCHAR(32) NULL;
EXEC SP_RENAME 'T_COMPONENT_DIARY.[ACCEPT_COUNTS]','WAREHOUSE_COUNTS','COLUMN';
ALTER TABLE T_AMOUNT_PAYMENT ALTER COLUMN PAYMENT_ENT_ACCOUNT_ID BIGINT NULL;
ALTER TABLE T_PURCHASE ADD PAYMENT_AMOUNT NUMERIC(12, 2) NOT NULL DEFAULT 0;

ALTER TABLE T_EQUIPMENT_DETECT ADD PAYMENT_AMOUNT NUMERIC(12, 2) NOT NULL DEFAULT 0;
UPDATE T_EQUIPMENT_DETECT SET DETECT_AMOUNT = 0 WHERE DETECT_AMOUNT IS NULL;
ALTER TABLE T_EQUIPMENT_DETECT ALTER COLUMN DETECT_AMOUNT NUMERIC(12, 2) NOT NULL;

ALTER TABLE T_EQUIPMENT_HITCH ADD LOCATION VARCHAR(128) NULL;
ALTER TABLE T_EQUIPMENT_HITCH ADD CONTENT VARCHAR(512) NULL;

ALTER TABLE T_CONSTRUCT_OPERATION ADD CONSTRUCT_THEME VARCHAR(96) NULL;
ALTER TABLE T_CONSTRUCT_OPERATION ADD EFFECTIVE CHAR(1) NULL;
ALTER TABLE T_CONSTRUCT_OPERATION ADD CONSTRUCT_DATE CHAR(10) NULL;
GO
UPDATE T_CONSTRUCT_OPERATION SET CONSTRUCT_THEME = '', EFFECTIVE = '1';
ALTER TABLE T_CONSTRUCT_OPERATION ALTER COLUMN CONSTRUCT_THEME VARCHAR(96) NOT NULL;
ALTER TABLE T_CONSTRUCT_OPERATION ALTER COLUMN EFFECTIVE CHAR(1) NOT NULL;
--2015-08-18
ALTER TABLE T_CAR_EXPENSE ADD MILEAGE VARCHAR(64) NULL;
ALTER TABLE T_CAR_EXPENSE ADD OIL_WEAR VARCHAR(64) NULL;

ALTER TABLE T_EQUIPMENT_REPAIR ADD DAMAGE_DATE CHAR(10) NULL;
ALTER TABLE T_EQUIPMENT_REPAIR ADD REPAIR_DATE CHAR(10) NULL;
--2015-08-29
ALTER TABLE T_PRACTI_DIARY ALTER COLUMN STATION VARCHAR(32) NULL;

ALTER TABLE T_LOGISTICS_TRANSPORT ADD TRANSPORT_ENT_NAME VARCHAR(64) NULL;
ALTER TABLE T_LOGISTICS_TRANSPORT ADD TRANSPORT_CONTACT_TEL VARCHAR(16) NULL;
ALTER TABLE T_LOGISTICS_TRANSPORT ADD TRANSPORT_BANK_DEPOSIT VARCHAR(64) NULL;
ALTER TABLE T_LOGISTICS_TRANSPORT ADD TRANSPORT_BANK_ACCOUNT VARCHAR(32) NULL;

ALTER TABLE T_LOGISTICS_BACKSPORT ADD BACKSPORT_ENT_NAME VARCHAR(64) NULL;
ALTER TABLE T_LOGISTICS_BACKSPORT ADD BACKSPORT_CONTACT_TEL VARCHAR(16) NULL;
ALTER TABLE T_LOGISTICS_BACKSPORT ADD BACKSPORT_BANK_DEPOSIT VARCHAR(64) NULL;
ALTER TABLE T_LOGISTICS_BACKSPORT ADD BACKSPORT_BANK_ACCOUNT VARCHAR(32) NULL;

ALTER TABLE T_EQUIPMENT_REPAIR ADD RENEWAL_DATE CHAR(10) NULL;
ALTER TABLE T_EQUIPMENT ADD PAYMENT_TYPE VARCHAR(6) NULL;
  
--2015-09-27
ALTER TABLE BM_PROVINCE ADD LONGITUDE VARCHAR(16) NULL; --����
ALTER TABLE BM_PROVINCE ADD LATITUDE  VARCHAR(16) NULL; --γ��
ALTER TABLE BM_CITY ADD LONGITUDE VARCHAR(16) NULL; --����
ALTER TABLE BM_CITY ADD LATITUDE  VARCHAR(16) NULL; --γ��
ALTER TABLE BM_COUNTY ADD LONGITUDE VARCHAR(16) NULL; --����
ALTER TABLE BM_COUNTY ADD LATITUDE  VARCHAR(16) NULL; --γ��

ALTER TABLE T_EQUIPMENT_REPAIR_LOCATION ADD UNIT_PRICE NUMERIC(12, 2) NULL;
ALTER TABLE T_EQUIPMENT_REPAIR_LOCATION ADD LABOUR SMALLINT NULL;
GO
UPDATE T_EQUIPMENT_REPAIR_LOCATION SET UNIT_PRICE = 0, LABOUR = 0;
ALTER TABLE T_EQUIPMENT_REPAIR_LOCATION ALTER COLUMN UNIT_PRICE NUMERIC(12, 2) NOT NULL;
ALTER TABLE T_EQUIPMENT_REPAIR_LOCATION ALTER COLUMN LABOUR SMALLINT NOT NULL;

ALTER TABLE T_EQUIPMENT_REPAIR DROP COLUMN LICENSE_PLATE;
--ά�޹���-����
CREATE TABLE T_EQUIPMENT_REPAIR_VEHICLE
(
  REPAIR_VEHICLE_ID          BIGINT IDENTITY PRIMARY KEY,
  REPAIR_ID                  BIGINT NULL,                    --ά�޵�(����ɾ�����)
  LICENSE_PLATE              VARCHAR(16) NULL,               --���ƺ�
  VEHICLE_MODEL              VARCHAR(32) NULL,               --�����ͺ�
  VEHICLE_AMOUNT             NUMERIC(12, 2) NOT NULL,        --����
  REMARK                     VARCHAR(256) NULL               --��ע(��ѡ��)
);
ALTER TABLE T_EQUIPMENT_REPAIR ALTER COLUMN PROJECT_ID BIGINT NULL;

ALTER TABLE T_CONSTRUCT_OPERATION ADD PROJECT_PRINCIPAL VARCHAR(64) NULL;
ALTER TABLE T_CONSTRUCT_OPERATION ADD TEAMS VARCHAR(32) NULL;
ALTER TABLE T_CONSTRUCT_OPERATION ADD FINISHED_AMOUNT NUMERIC(12, 2) NULL;
ALTER TABLE T_CONSTRUCT_OPERATION ADD REMAINDER_AMOUNT NUMERIC(12, 2) NULL;
ALTER TABLE T_CONSTRUCT_OPERATION ADD FUND_STATUS CHAR(1) NULL;
ALTER TABLE T_CONSTRUCT_OPERATION ADD PLAN_HEIGHT VARCHAR(16) NULL;
ALTER TABLE T_CONSTRUCT_OPERATION ADD REAL_HEIGHT VARCHAR(16) NULL;
GO
UPDATE T_CONSTRUCT_OPERATION SET FINISHED_AMOUNT = 0, REMAINDER_AMOUNT = 0, FUND_STATUS = '0';
ALTER TABLE T_CONSTRUCT_OPERATION ALTER COLUMN FINISHED_AMOUNT NUMERIC(12, 2) NOT NULL;
ALTER TABLE T_CONSTRUCT_OPERATION ALTER COLUMN REMAINDER_AMOUNT NUMERIC(12, 2) NOT NULL;
ALTER TABLE T_CONSTRUCT_OPERATION ALTER COLUMN FUND_STATUS CHAR(1) NOT NULL;

ALTER TABLE T_CONSTRUCT_OPERATION_TASK ADD TASK_TYPE CHAR(1) NULL;
GO
UPDATE T_CONSTRUCT_OPERATION_TASK SET TASK_TYPE = '0';
ALTER TABLE T_CONSTRUCT_OPERATION_TASK ALTER COLUMN TASK_TYPE CHAR(1) NOT NULL;

ALTER TABLE T_LOGISTICS_TRANSPORT ADD EQUIP_ID BIGINT NULL;
ALTER TABLE T_LOGISTICS_TRANSPORT ADD KNOT_COUNTS SMALLINT NULL;
ALTER TABLE T_LOGISTICS_TRANSPORT ADD STRENGTHEN_COUNTS SMALLINT NULL;
ALTER TABLE T_LOGISTICS_TRANSPORT ADD KNOT_BOLT_COUNTS SMALLINT NULL;
ALTER TABLE T_LOGISTICS_TRANSPORT ADD WALL_ATTACHE_QTY SMALLINT NULL;
ALTER TABLE T_LOGISTICS_TRANSPORT ADD PROJECT_PRINCIPAL VARCHAR(64) NULL;
ALTER TABLE T_LOGISTICS_TRANSPORT ADD FINISHED_AMOUNT NUMERIC(12, 2) NULL;
ALTER TABLE T_LOGISTICS_TRANSPORT ADD REMAINDER_AMOUNT NUMERIC(12, 2) NULL;
GO
UPDATE T_LOGISTICS_TRANSPORT SET FINISHED_AMOUNT = 0, REMAINDER_AMOUNT = 0;
ALTER TABLE T_LOGISTICS_TRANSPORT ALTER COLUMN FINISHED_AMOUNT NUMERIC(12, 2) NOT NULL;
ALTER TABLE T_LOGISTICS_TRANSPORT ALTER COLUMN REMAINDER_AMOUNT NUMERIC(12, 2) NOT NULL;

ALTER TABLE T_LOGISTICS_TRANCARFEE ADD MOTORCOACH VARCHAR(32) NULL;
ALTER TABLE T_LOGISTICS_TRANCARFEE ADD UNIT_PRICE NUMERIC(12, 2) NULL;

ALTER TABLE T_LOGISTICS_BACKSPORT ADD EQUIP_ID BIGINT NULL;
ALTER TABLE T_LOGISTICS_BACKSPORT ADD KNOT_COUNTS SMALLINT NULL;
ALTER TABLE T_LOGISTICS_BACKSPORT ADD STRENGTHEN_COUNTS SMALLINT NULL;
ALTER TABLE T_LOGISTICS_BACKSPORT ADD KNOT_BOLT_COUNTS SMALLINT NULL;
ALTER TABLE T_LOGISTICS_BACKSPORT ADD WALL_ATTACHE_QTY SMALLINT NULL;
ALTER TABLE T_LOGISTICS_BACKSPORT ADD PROJECT_PRINCIPAL VARCHAR(64) NULL;
ALTER TABLE T_LOGISTICS_BACKSPORT ADD FINISHED_AMOUNT NUMERIC(12, 2) NULL;
ALTER TABLE T_LOGISTICS_BACKSPORT ADD REMAINDER_AMOUNT NUMERIC(12, 2) NULL;
GO
UPDATE T_LOGISTICS_BACKSPORT SET FINISHED_AMOUNT = 0, REMAINDER_AMOUNT = 0;
ALTER TABLE T_LOGISTICS_BACKSPORT ALTER COLUMN FINISHED_AMOUNT NUMERIC(12, 2) NOT NULL;
ALTER TABLE T_LOGISTICS_BACKSPORT ALTER COLUMN REMAINDER_AMOUNT NUMERIC(12, 2) NOT NULL;

ALTER TABLE T_LOGISTICS_BACKCARFEE ADD MOTORCOACH VARCHAR(32) NULL;
ALTER TABLE T_LOGISTICS_BACKCARFEE ADD UNIT_PRICE NUMERIC(12, 2) NULL;

ALTER TABLE T_EQUIPMENT_DETECT ADD EM_ENT_NAME VARCHAR(64) NULL;
ALTER TABLE T_EQUIPMENT_DETECT ADD SUP_ENT_NAME VARCHAR(64) NULL;
ALTER TABLE T_EQUIPMENT_DETECT ADD LICENSE_NUMBER VARCHAR(24) NULL;
ALTER TABLE T_EQUIPMENT_DETECT ADD INSTALL_PRINCIPAL VARCHAR(64) NULL;
ALTER TABLE T_EQUIPMENT_DETECT ADD INSTALL_CERT_NUM VARCHAR(32) NULL;
ALTER TABLE T_EQUIPMENT_DETECT ADD PROJECT_PRINCIPAL VARCHAR(64) NULL;
ALTER TABLE T_EQUIPMENT_DETECT ADD PROJECT_CERT_NUM VARCHAR(32) NULL;
ALTER TABLE T_EQUIPMENT_DETECT ADD SAFETY_PRINCIPAL VARCHAR(64) NULL;
ALTER TABLE T_EQUIPMENT_DETECT ADD SAFETY_CERT_NUM VARCHAR(32) NULL;

ALTER TABLE T_EQUIPMENT_DIARY ADD LAST_BLOCKUP_DATE CHAR(10) NULL;

ALTER TABLE T_SETTLE_CONTRACT ALTER COLUMN TAX_RATE NUMERIC(12, 3) NULL;

ALTER TABLE T_EQUIPMENT_EMPLOY ADD CAPTAIN_ID BIGINT NULL;
ALTER TABLE T_EQUIPMENT_EMPLOY ADD CAPTAIN VARCHAR(32) NULL;
ALTER TABLE T_EQUIPMENT_EMPLOY ADD CAPTAIN_TEL VARCHAR(16) NULL;

ALTER TABLE T_REIMBURSE_TICKET ADD SPECIFIC_NAME VARCHAR(64) NULL;
ALTER TABLE T_REIMBURSE_TICKET ADD MODEL_NAME VARCHAR(64) NULL;
ALTER TABLE T_REIMBURSE_TICKET ADD UNIT_PRICE NUMERIC(12, 2) NULL;
ALTER TABLE T_REIMBURSE_TICKET ADD TICKET_QUANTITY SMALLINT NULL;
GO
UPDATE T_REIMBURSE_TICKET SET UNIT_PRICE = 0, TICKET_QUANTITY = 0;
ALTER TABLE T_REIMBURSE_TICKET ALTER COLUMN UNIT_PRICE NUMERIC(12, 2) NOT NULL;
ALTER TABLE T_REIMBURSE_TICKET ALTER COLUMN TICKET_QUANTITY SMALLINT NOT NULL;

ALTER TABLE T_COMPONENT ADD BOLT_FLAG CHAR(1) NOT NULL DEFAULT '0';

ALTER TABLE T_EQUIPMENT ADD LATEST_REPAIR_DATE SMALLDATETIME NULL;
ALTER TABLE T_EQUIPMENT ADD LATEST_INSPECT_DATE DATETIME NULL;
ALTER TABLE T_EQUIPMENT ADD PROJECT_ID BIGINT NULL;
ALTER TABLE T_EQUIPMENT ADD PROJECT_ADDRESS VARCHAR(256) NULL;
GO
UPDATE E SET E.PROJECT_ID = ED.PROJECT_ID, E.PROJECT_ADDRESS = ED.ADDRESS FROM T_EQUIPMENT E, T_EQUIPMENT_DIARY ED WHERE E.FLOW_ID = ED.FLOW_ID;

ALTER TABLE T_EQUIPMENT_DIARY ADD PA_ENT_NAME VARCHAR(64) NULL;
GO
UPDATE ED SET ED.PA_ENT_NAME = CL.PA_ENT_NAME FROM T_EQUIPMENT_DIARY ED, T_CONTRACT_LEASE CL WHERE ED.CONTRACT_ID = CL.CONTRACT_ID;

ALTER TABLE T_EQUIPMENT ADD FINISHED_AMOUNT NUMERIC(12, 2) NOT NULL DEFAULT 0;
ALTER TABLE T_EQUIPMENT ADD REMAINDER_AMOUNT NUMERIC(12, 2) NOT NULL DEFAULT 0;

ALTER TABLE T_EQUIPMENT_ACTIVATE ADD APPOINTMENT_DATE CHAR(10) NULL;
ALTER TABLE T_PRACTITIONER ADD PROJECT_ID BIGINT NULL;
ALTER TABLE T_PRACTITIONER ADD PROJECT_NAME VARCHAR(64) NULL;

--2015-10-12
ALTER TABLE T_INVOICE_ISSUE ADD TAX_RATE NUMERIC(12, 2) NOT NULL DEFAULT 0;
ALTER TABLE T_INVOICE_ISSUE ADD TAX_AMOUNT NUMERIC(12, 3) NOT NULL DEFAULT 0;
ALTER TABLE T_INVOICE_ISSUE DROP UQ_T_INVOICE_ISSUE1;
GO

ALTER TABLE T_EQUIPMENT ADD EQUIP_DIARY_ID BIGINT NULL;
GO
UPDATE E SET E.EQUIP_DIARY_ID = ED.EQUIP_DIARY_ID FROM T_EQUIPMENT E, T_EQUIPMENT_DIARY ED WHERE E.FLOW_ID = ED.FLOW_ID;

--2015-12-15
ALTER TABLE T_AMOUNT_PAYMENT ALTER COLUMN PAYMENT_CONTENT VARCHAR(4000) NULL;
ALTER TABLE T_AMOUNT_PAYMENT ALTER COLUMN PAYMENT_BANK VARCHAR(64) NULL;
ALTER TABLE T_AMOUNT_PAYMENT ALTER COLUMN PAYMENT_ACCOUNT VARCHAR(32) NULL;

ALTER TABLE BM_REIMBURSE_TYPE ADD PARENT VARCHAR(6) NULL;
UPDATE INIT_LOAD_TABLE SET PARENT_FIELD_NAME = 'PARENT' WHERE TABLE_ALIAS = 'reimburseType';

ALTER TABLE T_REIMBURSE_TICKET ADD CAR_ID BIGINT NULL;
ALTER TABLE T_REIMBURSE_TICKET ADD LICENSE_PLATE VARCHAR(16) NULL;

--2016-01-05
EXEC SP_RENAME 'T_CONTRACT_APPLICATION','T_CONTRACT_ARRANGE';
EXEC SP_RENAME 'T_CONTRACT_APPLICATION_EQUIPMENT','T_CONTRACT_ARRANGE_EQUIPMENT';
EXEC SP_RENAME 'T_CONTRACT_APPLICATION_PLAN','T_CONTRACT_ARRANGE_SITUATION';
GO
EXEC SP_RENAME 'T_CONTRACT_ARRANGE.[APPLICATION_ID]','ARRANGE_ID','COLUMN';
EXEC SP_RENAME 'T_CONTRACT_ARRANGE.[APPLICATION_SERIAL]','ARRANGE_SERIAL','COLUMN';
ALTER TABLE T_CONTRACT_ARRANGE ADD ARRANGE_TYPE CHAR(1) NOT NULL DEFAULT '0';
GO
EXEC SP_RENAME 'T_CONTRACT_ARRANGE_EQUIPMENT.[APPLICATION_EQUIP_ID]','ARRANGE_EQUIP_ID','COLUMN';
EXEC SP_RENAME 'T_CONTRACT_ARRANGE_EQUIPMENT.[APPLICATION_ID]','ARRANGE_ID','COLUMN';
GO
EXEC SP_RENAME 'T_CONTRACT_ARRANGE_SITUATION.[PLAN_ID]','ARRANGE_SITUATION_ID','COLUMN';
EXEC SP_RENAME 'T_CONTRACT_ARRANGE_SITUATION.[APPLICATION_ID]','ARRANGE_ID','COLUMN';
EXEC SP_RENAME 'T_CONTRACT_ARRANGE_SITUATION.[PLAN_TYPE]','EQUIP_CATEGORY','COLUMN';
GO
UPDATE T_CONTRACT_ARRANGE_SITUATION SET EQUIP_CATEGORY = 'T' WHERE EQUIP_CATEGORY = '0';
UPDATE T_CONTRACT_ARRANGE_SITUATION SET EQUIP_CATEGORY = 'S' WHERE EQUIP_CATEGORY = '1';
UPDATE T_FORM_ACCEPT SET RELATE_MODULE = 'CONTRACT_ARRANGE' WHERE RELATE_MODULE = 'CONTRACT_APPLICATION';
UPDATE T_FORM_APPROVE SET RELATE_MODULE = 'CONTRACT_ARRANGE' WHERE RELATE_MODULE = 'CONTRACT_APPLICATION';

--2016-01-12
ALTER TABLE T_EQUIPMENT_DETECT ADD BALANCE_AMOUNT NUMERIC(12, 2) NOT NULL DEFAULT '0';
UPDATE T_EQUIPMENT_DETECT SET BALANCE_AMOUNT = DETECT_AMOUNT - PAYMENT_AMOUNT;

UPDATE T_COMPONENT SET UNITPRICE = 0 WHERE UNITPRICE IS NULL;
ALTER TABLE T_COMPONENT ALTER COLUMN UNITPRICE NUMERIC(12, 3) NOT NULL;
UPDATE T_COMPONENT SET ASSET_VALUE = 0 WHERE ASSET_VALUE IS NULL;
ALTER TABLE T_COMPONENT ALTER COLUMN ASSET_VALUE NUMERIC(12, 3) NOT NULL;

DELETE FROM T_DEDUCT_SCALE WHERE DEDUCT_SCALE_ID = 1;
GO
SET IDENTITY_INSERT T_DEDUCT_SCALE ON
INSERT T_DEDUCT_SCALE (DEDUCT_SCALE_ID, SCALE_START, SCALE_END, SCALE_PERCENT, SCALE_TYPE) VALUES (1, CAST(0.00 AS Numeric(12, 2)), CAST(9999999999.00 AS Numeric(12, 2)), CAST(5.00 AS Numeric(5, 2)), N'0')
SET IDENTITY_INSERT T_DEDUCT_SCALE OFF
GO

ALTER TABLE T_PICKUP ADD PICKUP_AMOUNT NUMERIC(12, 2) NOT NULL DEFAULT 0;
ALTER TABLE T_PURCHASE_BRIEF ADD DIMENSIONS VARCHAR(64) NULL;
--�������
CREATE TABLE T_AUTOCRANE
(
  AUTOCRANE_ID               BIGINT IDENTITY PRIMARY KEY,
  AUTOCRANE_SERIAL           VARCHAR(64) NOT NULL,           --���(QD+������+2λ��ˮ��)
  PROJECT_ID                 BIGINT NULL,                    --��Ŀ���(��Դ��Ŀ����,Ĭ�� ���޺�ͬ ����Ŀ��Ϣ)
  EM_ENT_NAME                VARCHAR(62) NULL,               --ʹ�õ�λ(��Դ�ͻ�����,Ĭ�ϡ����޺�ͬ���еġ����ⷽ��)
  IN_ENT_NAME                VARCHAR(64) NULL,               --��װ��λ(��Դ��ҵ��Ϣ,Ĭ�ϡ����޺�ͬ���еġ����ⷽ��)
  AUTOCRANE_DEPEND           VARCHAR(6) NULL,                --���������λ(���� BM_AUTOCRANE_DEPEND)
  AUTOCRANE_AMOUNT           NUMERIC(11, 2) NOT NULL,        --���úϼ�
  PAYMENT_AMOUNT             NUMERIC(12, 2) NOT NULL,        --�Ѹ�����
  BALANCE_AMOUNT             NUMERIC(12, 2) NOT NULL,        --���
  REMARK                     VARCHAR(256) NULL,              --��ע
  EFFECTIVE                  CHAR(1) NOT NULL,               --��Ч��ʶ(����ֵ 0:δ��Ч,1:��Ч)
  FUND_STATUS                CHAR(1) NULL,                   --����״̬(����ֵ 0:���,1:������,2:�Ѹ���)
  USER_ID                    BIGINT NOT NULL,                --�Ǽ���ID
  USER_NAME                  VARCHAR(32) NOT NULL,           --�Ǽ���
  PROVIDED_DATE              CHAR(10) NOT NULL               --�ʱ��
);
--�����������嵥
CREATE TABLE T_AUTOCRANE_EXPENSE
(
  AUTOCRANE_EXPENSE_ID       BIGINT IDENTITY PRIMARY KEY,
  AUTOCRANE_ID               BIGINT NULL,
  SPECIFIC_NAME              VARCHAR(64) NULL,               --����ͺ�
  ACCOUNT_PRICE              NUMERIC(12, 2) NOT NULL,        --����
  QUANTITY                   SMALLINT NOT NULL,              --����
  MACHINE_TEAM               SMALLINT NOT NULL,              --̨��
  SUMMARY                    NUMERIC(12, 2) NOT NULL,        --�ϼ�(����*����*̨��)
  REMARK                     VARCHAR(256) NULL               --��ע
);
ALTER TABLE T_AMOUNT_PAYMENT ALTER COLUMN RELATE_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_AMOUNT_EQUIP_SHARE ALTER COLUMN RELATE_SERIAL VARCHAR(64) NULL;
--2016-02-04
ALTER TABLE T_PICKUP_COMPONENT ADD DIMENSIONS VARCHAR(64) NULL;
GO;
UPDATE PC SET PC.DIMENSIONS = C.DIMENSIONS FROM T_PICKUP_COMPONENT PC, T_COMPONENT C WHERE C.COMPON_ID = PC.COMPON_ID;
ALTER TABLE T_SETTLE_CONTRACT ADD BALANCE_AMOUNT NUMERIC(12, 2) NOT NULL DEFAULT 0;
GO
UPDATE T_SETTLE_CONTRACT SET BALANCE_AMOUNT = SETTLE_AMOUNT - FINISHED_AMOUNT;
ALTER TABLE T_AUTOCRANE ADD EQUIP_ID BIGINT NULL;

--2016-06-17
ALTER TABLE T_EQUIPMENT_DETECT ADD DETECT_DATE CHAR(10) NULL;
ALTER TABLE T_EQUIPMENT_DETECT ADD REDETECT_DATE CHAR(10) NULL;
ALTER TABLE T_COMPONENT ADD PICKUP_DATE CHAR(10) NULL;

--2016-06-23
INSERT INTO INIT_LOAD_TABLE VALUES('constructTask', 'BM_CONSTRUCT_TASK', 1, 1, 1, 'CODE', 'VALUE', 0, NULL, NULL, NULL, '��������');
--�������� constructTask
CREATE TABLE BM_CONSTRUCT_TASK
(
  CODE        VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE       VARCHAR(64) NOT NULL
);



ALTER TABLE T_EQUIPMENT_FLOW ADD EMPLOY_MAINT_SCHEMA_ID BIGINT NULL;

--2017-3-10
ALTER TABLE T_BUSINESS_MESSAGE ADD READ_FLAG char(1) NULL COMMENT '阅读状态 0未读，1已读';


--2017-3-14
Alter   Table   dbo.T_ATTENDAMCE   ALTER   column   SGOU_TIME   VARCHAR(50)
Alter   Table   dbo.T_ATTENDAMCE   ALTER   column   SGIN_TIME   VARCHAR(50)

--2017-3-16
Alter   Table   T_REPAIR      ADD WEIGHT_OF_FAILURE VARCHAR(64) NULL COMMENT '故障时重量';
Alter   Table   T_REPAIR      ADD IMPUT_VOLTAGE VARCHAR(64) NULL  COMMENT '输入电压';
Alter   Table   T_REPAIR      ADD BREAK_DOWN_VOLTAGE VARCHAR(64) NULL COMMENT '故障电压';
Alter   Table   T_REPAIR ADD SWITCH_FAULT_1     		  VARCHAR(4) NULL COMMENT '开关故障_1';
Alter   Table   T_REPAIR ADD SWITCH_FAULT_2             VARCHAR(4) NULL COMMENT '开关故障_2' ;
Alter   Table   T_REPAIR ADD SWITCH_FAULT_3             VARCHAR(4) NULL  COMMENT '开关故障_3';

Alter   Table   T_ELEVATOR_MONITOR ADD SWITCH_FAULT_1     		  VARCHAR(4) NULL COMMENT '开关故障_1';        
Alter   Table   T_ELEVATOR_MONITOR ADD SWITCH_FAULT_2             VARCHAR(4) NULL  COMMENT '开关故障_2';     
Alter   Table   T_ELEVATOR_MONITOR ADD SWITCH_FAULT_3             VARCHAR(4) NULL   COMMENT '开关故障_3' ;       

--121.42.34.181 add table
--DROP TABLE IF EXISTS `t_sync_index`;
--CREATE TABLE `t_sync_index` (
--  `INDEX_ID` bigint(20) NOT NULL AUTO_INCREMENT,
--  `SYNC_NAME` varchar(32) DEFAULT NULL COMMENT '同步表名',
--  `SYNC_LAST_ID` int(11) DEFAULT NULL COMMENT '同步表ID',
--  `UPDATE_TIMES` varchar(32) DEFAULT NULL COMMENT '数据更新时间',
--  `COMMENT` varchar(32) DEFAULT NULL COMMENT '备注',
--  PRIMARY KEY (`INDEX_ID`)
--) ENGINE=InnoDB AUTO_INCREMENT=27 DEFAULT CHARSET=utf8 COMMENT='数据库同步索引';


--2017-4-8
ALTER TABLE T_BUSINESS_MESSAGE ADD MODULE  VARCHAR(32) NULL COMMENT'来源模块'; 
ALTER TABLE T_BUSINESS_MESSAGE ADD DETAIL  VARCHAR(1024) NULL COMMENT'待办事项详情内容';
ALTER TABLE T_BUSINESS_MESSAGE ADD MSG_TYPE  char(1) NULL COMMENT'待办事项还是消息 0 待办事项   1 消息';

--2017-4-13
ALTER TABLE  T_CONSTRUCT_OPERATION ADD CREATE_BY    VARCHAR(32)  NULL COMMENT '创建人'；

--2017-4-28
ALTER TABLE T_CORP_INFO ADD MAINTENANCES VARCHAR(32) NULL;
ALTER TABLE T_CORP_INFO ADD MAINTENANCES_TEL VARCHAR(16) NULL;
ALTER TABLE T_CORP_INFO ADD CHIEF_ECONOMIST VARCHAR(32) NULL;
ALTER TABLE T_CORP_INFO ADD CHIEF_ECONOMIST_TEL VARCHAR(16) NULL;
ALTER TABLE T_CORP_INFO ADD MATERIAL VARCHAR(32) NULL;
ALTER TABLE T_CORP_INFO ADD MATERIAL_TEL VARCHAR(16) NULL;
ALTER TABLE T_CORP_INFO ADD SAFETY VARCHAR(32) NULL;
ALTER TABLE T_CORP_INFO ADD SAFETY_TEL VARCHAR(16) NULL;

		
CREATE TABLE BM_REPAIR_FAULT (
   ID  BIGINT IDENTITY PRIMARY KEY,
  CODE  VARCHAR(32) NULL,     
  VALUE VARCHAR(32)  NULL 
) 

INSERT INTO BM_REPAIR_FAULT VALUES('0','正常');
INSERT INTO BM_REPAIR_FAULT VALUES('1','逆变单元保护');
INSERT INTO BM_REPAIR_FAULT VALUES('2','硬件过流');
INSERT INTO BM_REPAIR_FAULT VALUES('3','硬件过压');
INSERT INTO BM_REPAIR_FAULT VALUES('4','加速过流');
INSERT INTO BM_REPAIR_FAULT VALUES('5','减速过流');
INSERT INTO BM_REPAIR_FAULT VALUES('6','停机过程过流');
INSERT INTO BM_REPAIR_FAULT VALUES('7','恒速过流');
INSERT INTO BM_REPAIR_FAULT VALUES('8','加速过压');
INSERT INTO BM_REPAIR_FAULT VALUES('9','减速过压');
INSERT INTO BM_REPAIR_FAULT VALUES('10','恒速过压');
INSERT INTO BM_REPAIR_FAULT VALUES('11','停机时过压');
INSERT INTO BM_REPAIR_FAULT VALUES('12','欠压故障');


CREATE TABLE [dbo].[T_ELEVATOR_MONITOR](
	[_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[MONITOR_ADDRESS] [varchar](50) NULL,
	[EQUIPMENT_NUMBER] [varchar](50) NULL,
	[EQUIPMENT_STATUS] [varchar](50) NULL,
	[FAULT] [varchar](50) NULL,
	[FAULT_CURRENT] [varchar](50) NULL,
	[BREAKDOWN_VOLTAGE] [varchar](50) NULL,
	[FAILURE_FREQUENCY] [varchar](50) NULL,
	[WEIGHT_OF_FAILURE] [varchar](50) NULL,
	[FAULT_FLOOR] [varchar](50) NULL,
	[INPUT_VOLTAGE] [varchar](50) NULL,
	[POSITION] [varchar](50) NULL,
	[HOURS] [varchar](50) NULL,
	[MINUTES] [varchar](50) NULL,
	[CREATE_DATE_TIME] [varchar](128) NULL,
	[MONITOR_ID] [bigint] NULL,
	[SWITCH_FAULT_1] [varchar](4) NULL,
	[SWITCH_FAULT_2] [varchar](4) NULL,
	[SWITCH_FAULT_3] [varchar](4) NULL,
 CONSTRAINT [PK_T_ELEVATOR_MONITOR] PRIMARY KEY CLUSTERED 
(
	[_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

--SET IDENTITY_INSERT SYS_CONFIG ON;
--INSERT INTO SYS_CONFIG (CONFIGID, CONFIGKEY, FIELDSET, CONFIGNAME, CONFIGDESC, TYPENAME, DATATYPE, DATAVALUE, DELFLAG)
--VALUES (9, 'equip.redetect', '检测管理下次检测时间提醒', '检测管理下次检测时间提醒', '检测管理下次检测时间提醒', 'TEXT', 1, '30', '1');
--SET IDENTITY_INSERT SYS_CONFIG OFF;

ALTER TABLE T_INSPECT_MANAGE ADD PROJECT_ID int NOT NULL COMMENT '项目ID';

--2017年5月25日15:40:57     
ALTER TABLE APP_USER ALTER COLUMN EMAIL varchar(128) NULL;
ALTER TABLE T_CAR ALTER COLUMN PROPERTY_NAME varchar(64) NULL;
ALTER TABLE T_CAR ALTER COLUMN SEDAN varchar(32) NULL;

ALTER TABLE SYS_CONFIG ALTER COLUMN DATAVALUE VARCHAR(128);
INSERT INTO SYS_CONFIG (CONFIGKEY, FIELDSET, CONFIGNAME, CONFIGDESC, TYPENAME, DATATYPE, DATAVALUE, DELFLAG)
VALUES ('a9_address', 'a9开放注册路径', 'a9开放注册路径', 'a9开放注册路径', 'TEXT', 0, 'http://121.42.34.181:8000/emms/public/external/account/create.do', '0');

--代租管理，增加“整月”字段
ALTER TABLE T_RENT_EQUIP_BRIEF ADD MONTH_TAG varchar(5) NULL;

--设备合同，增加“资产属性”，“建筑面积”字段
ALTER TABLE T_CONTRACT_LEASE ADD ASSETS_PROPERTY VARCHAR(64) NULL;
ALTER TABLE T_CONTRACT_LEASE ADD BUILDING_AREA VARCHAR(12) NULL;

--配货清单,增加   "生产产家","配件类别"
ALTER TABLE T_DISPATCH_ALLOCATE_INIT ADD EQUIPVENDER varchar(30) NULL;

ALTER TABLE T_DISPATCH_ALLOCATE_INIT ADD COMPONCATEGORYNAME varchar(20) NULL;
ALTER TABLE T_COMPONENT ADD TASK_ID BIGINT NULL;
ALTER TABLE T_STORE_HOUSE ADD TASK_ID BIGINT NULL;

ALTER TABLE T_COMPONENT ADD MANUFACTURER VARCHAR(64) NULL;
ALTER TABLE T_COMPONENT ADD IS_MACHINE VARCHAR(64) NULL;
ALTER TABLE T_COMPONENT ADD NO_MACHINE VARCHAR(64) NULL;


--修改周材合同表字段“资产属性”,“工程类别”
ALTER TABLE T_CONTRACT_MATERIALS DROP COLUMN ASSETS_PROPERTY;
ALTER TABLE T_CONTRACT_MATERIALS DROP COLUMN ENGINEERING_TYPE;
ALTER TABLE T_CONTRACT_MATERIALS ADD ASSETS_PROPERTY_NAME VARCHAR(64) NULL;
ALTER TABLE T_CONTRACT_MATERIALS ADD ENGINEERING_TYPE_NAME VARCHAR(64) NULL;

--增加周材品名设置表数据项“丢失赔偿单位”
ALTER TABLE T_MATERIALS_COMMODITY ADD COMPENSATION_UNIT VARCHAR(12) NULL;

ALTER TABLE T_MATERIALS_SPECIFICATIONS ADD COMPENSATION_UNIT VARCHAR(12) NULL;


ALTER TABLE T_COMPONENT ADD STORE_NAME VARCHAR(64) NULL;  --仓库名称

ALTER TABLE T_PRACTI_CERT ADD REGISTRANT_ORGANIZATION VARCHAR(64) NULL;  --注册单位

ALTER TABLE T_PROJECT ADD DEP_ID BIGINT NULL;  --所属部门

ALTER TABLE T_COMPONENT DROP COLUMN YES_FLAG;
ALTER TABLE T_COMPONENT DROP COLUMN NO_FLAG;