package com.knight.app.model;

// Generated 2015-5-29 9:21:52 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.Since;
import com.google.gson.reflect.TypeToken;
import com.knight.core.model.BaseModel;
import com.knight.core.model.ExportModel;
import com.knight.core.table.CodeFieldDeclare;
import com.knight.core.table.PersistantDeclare;
import com.knight.core.util.GsonUtil;
import com.knight.emms.model.AppRepairCostGrid;
import com.knight.emms.model.Equipment;

import lombok.Data;
import lombok.ToString;

/**
 * TAppRepair generated by hbm2java
 */
@Data
@ToString(callSuper = false, doNotUseGetters = true)
@PersistantDeclare(isExportable = true, exportName = "故障报修", sheetName = "故障报修")
public class TAppRepair extends BaseModel  implements ExportModel, Cloneable {

	private static final long serialVersionUID = 1L;
	@Expose
	private Long repid;
	@Expose
	private Equipment equipment;
	@Expose
	private Long equipId;
	@Expose
	private String equipSpec;//设备型号
	@Expose
	private String recordSerial;//设备编号
	@Expose
	private String recordId;//备案编号
	@Expose
	private String exwSerial;
	@Expose
	private String buildingNum;
	@Expose
	private String projName;//项目名称
	@Expose
	private Long projectId;
	@Expose
	private String reportDt;
	@Expose
	private String faultLevel;//故障级别
	@Expose
	private String faultDesc;
	@Expose
	private String procManId;//处理人
	@Expose
	private String procMan;//处理人
	@Expose
	private String location;
	@Expose
	private String disMan;
	@Expose
	private String disManName;//调配人
	@Expose
	private String repairDt;
	@Expose
	private String repScheme;
	@Expose
	private String procResult;
	@Expose
	private String repMan;//维修人
	@Expose
	private String repTimes;	
	@Expose
	private BigDecimal repFee;  //总维修费用
	@Expose
	private String repReason;	
	@Expose
	private String repImage;	
	@Expose
	@CodeFieldDeclare(codeId = "APP_REPAIR_STATUS", valueField = "stateName")
	private String state;
	@Expose
	private String stateName;
	@Expose
	@CodeFieldDeclare(codeId = "APP_REPAIR_PAYMENT_STATE", valueField = "paymentStateName")//付款状态
	private String paymentState;
	@Expose
	private String paymentStateName;
	@Expose
	private String createDt;
	@Expose
	private Long createBy;//申报人ID
	@Expose
	private String hasview;
	@Expose
	private String disDate;	//派工时间
	@Expose
	private String startOffTime; 	//赶往时间
	@Expose
	private String arriveTime;  //到达时间
	@Expose
	@CodeFieldDeclare(codeId = "appRepairType", valueField = "repairTypeName")
	private String repairType; //故障类型
	@Expose
	private String repairTypeName; //故障类型
	@Expose
	private String disRemark;     //备注
	
	@Expose
	private String createByname;//报修人
	@Expose(deserialize = false, serialize = false)
	@Since(value = 2.0)
	private Set<TAppRepairCompon> repairComponSet = new HashSet<TAppRepairCompon>();
	@Expose
    private String weightOfFailure;
	@Expose
    private String inputVoltage;
	@Expose
    private String breakdownVoltage;
	@Expose
	private String switchFault1; 		//开关故障1
	@Expose
	private String switchFault2; 		//开关故障2
	@Expose
	private String switchFault3; 		//开关故障3
	@Expose
	private String equipSerial;         //设备自编号      
	
	
	@Expose
	private String replaceCompon;  //更换配件

	/**维修前照片*/
	@Expose
	private String repairBeforeImage; //维修前照片
	
	@Expose
	private String repairAfterImage; //维修前照片
	
	@Expose
	private String componBeforeImage;//配件更换前
	
	@Expose
	private String componAfterImage;//配件更换后
	
	@Expose
	private String fileAttaches;//其他记录
	private String appRepairCostGrids = "";
	@Expose
	private Long sum;               //临时存放总维修费用
	@Expose
	private Long createByPhone;//申报人联系电话
	@Expose
	private List<String> imgList;
	@Expose
	private List<String> repImgList;
	@Expose
	private List<String> fileAttachesList;
	@Expose
	private List<String> componAfterImageList;
	@Expose
	private List<String> componBeforeImageList;
	@Expose
	private List<String> repairAfterImageList;
	@Expose
	private List<String> repairBeforeList;
	
	
	@Expose(deserialize = false, serialize = false)
	@Since(value = 2.0)
	private Set<AppRepairCostGrid> appRepairCostGridSet = new HashSet<AppRepairCostGrid>();
	// ==============================================================================//
			public void setSubScrapContract() {
				Set<AppRepairCostGrid> appRepairCostGridSet = GsonUtil.fromJson(this.getAppRepairCostGrids(), new TypeToken<Set<AppRepairCostGrid>>() {});
				if (appRepairCostGridSet != null) {
					repFee=BigDecimal.valueOf(0);
					sum=(long) 0;
					for (AppRepairCostGrid p : appRepairCostGridSet) {
						p.setRelateId(repid);
						sum+=p.getAmount();
					}
					repFee=BigDecimal.valueOf(sum);
				}
				this.setAppRepairCostGridSet(appRepairCostGridSet);
			}
}
