package com.knight.app.model;

import lombok.Data;
import lombok.ToString;

import com.google.gson.annotations.Expose;
import com.knight.core.model.BaseModel;

// Generated 2015-5-29 9:21:52 by Hibernate Tools 3.4.0.CR1

/**
 * TFlowCopyChkman generated by hbm2java
 */
@Data
@ToString(callSuper = false, doNotUseGetters = true)
public class TFlowCopyChkman extends BaseModel {

	private static final long serialVersionUID = 1L;
	@Expose
	private Long copid;
	@Expose
	private Long insid;
	@Expose
	private Long userId;
	
	@Expose
	private String userName;
	
	@Expose
	private String hasView;
	
	@Expose
	private TFlowInstance instance;

}
