SET IDENTITY_INSERT APP_USER ON;
INSERT INTO APP_USER (USERID, USERNAME, PASSWORD, DEP_ID, EMAIL, CREATE_TIME, STATUS, FULLNAME, DELFLAG, MOBILE)
VALUES (0, 'system', 'a4ayc/80/OGda4BO/1o/V0etpOqiLx1JwB5S3beHW0s=', -1, 'cxy193435@163.com', '2012-10-01 12:12:12', 1, '系统自动帐户', 1, '12345678901');
INSERT INTO APP_USER (USERID, USERNAME, PASSWORD, DEP_ID, EMAIL, CREATE_TIME, STATUS, FULLNAME, DELFLAG, MOBILE)
VALUES (1, 'admin', 'a4ayc/80/OGda4BO/1o/V0etpOqiLx1JwB5S3beHW0s=', -1, 'cxy193435@163.com', '2012-10-01 12:12:12', 1, '超级管理员', 0, '12345678901');
SET IDENTITY_INSERT APP_USER OFF;

SET IDENTITY_INSERT COMPANY ON;
INSERT INTO COMPANY (COMPANYID, COMPANYNO, COMPANYNAME, COMPANYDESC, LEGALPERSON, SETUP, PHONE, FAX, SITE, LOGO)
VALUES (1, '', '机械内部管理系统', '机械内部管理系统', '', null, '', '', '', '');
SET IDENTITY_INSERT COMPANY OFF;

SET IDENTITY_INSERT DEPARTMENT ON;
INSERT INTO DEPARTMENT (DEP_ID, DEP_SERIAL, DEP_NAME, DEP_DESC, DEP_LEVEL, DEP_TYPE, PARENT_ID, PATH, DELFLAG)
VALUES (-1, '_SUPERDE_DEPARTMENT', '系统默认单位', '系统默认单位', 2, 0, 0, '0.-1.', 0);
SET IDENTITY_INSERT DEPARTMENT OFF;

SET IDENTITY_INSERT SYS_CONFIG ON;
INSERT INTO SYS_CONFIG (CONFIGID, CONFIGKEY, FIELDSET, CONFIGNAME, CONFIGDESC, TYPENAME, DATASTORE, DATATYPE, DATAVALUE, DELFLAG)
VALUES (1, 'codeConfig', '验证码配置', '登陆验证码', '登录时是否需要验证码', 'COMBO', '1:开启验证码;0:屏蔽验证码', 2, '0', '0');
INSERT INTO SYS_CONFIG (CONFIGID, CONFIGKEY, FIELDSET, CONFIGNAME, CONFIGDESC, TYPENAME, DATATYPE, DATAVALUE, DELFLAG)
VALUES (2, 'attachSize', '附件大小配置', '上传文件最大值(KB)', '上传文件大小限制', 'TEXT', 1, '512', '1');
INSERT INTO SYS_CONFIG (CONFIGID, CONFIGKEY, FIELDSET, CONFIGNAME, CONFIGDESC, TYPENAME, DATATYPE, DATAVALUE, DELFLAG)
VALUES (3, 'sms.openurl', '短信服务平台地址', '短信服务平台地址', '短信服务平台地址', 'TEXT', 0, 'http://smsapi.c123.cn/OpenPlatform/OpenApi', '0');
INSERT INTO SYS_CONFIG (CONFIGID, CONFIGKEY, FIELDSET, CONFIGNAME, CONFIGDESC, TYPENAME, DATATYPE, DATAVALUE, DELFLAG)
VALUES (4, 'sms.account', '员工编号', '员工编号', '发送短信的帐号', 'TEXT', 0, '1001', '0');
INSERT INTO SYS_CONFIG (CONFIGID, CONFIGKEY, FIELDSET, CONFIGNAME, CONFIGDESC, TYPENAME, DATATYPE, DATAVALUE, DELFLAG)
VALUES (5, 'sms.enterprise', '企业编号', '企业编号', '发送短信的帐号', 'TEXT', 0, '500008880001', '0');
INSERT INTO SYS_CONFIG (CONFIGID, CONFIGKEY, FIELDSET, CONFIGNAME, CONFIGDESC, TYPENAME, DATATYPE, DATAVALUE, DELFLAG)
VALUES (6, 'sms.authkey', '认证密钥', '认证密钥', '32位认证密钥(大写)', 'TEXT', 0, '87B01469201D6557C2685137EB3B5DEC', '0');
INSERT INTO SYS_CONFIG (CONFIGID, CONFIGKEY, FIELDSET, CONFIGNAME, CONFIGDESC, TYPENAME, DATATYPE, DATAVALUE, DELFLAG)
VALUES (7, 'sms.cgid', '通道组编号', '使用的通道组编号', '在短信平台可以查看可用的通道组', 'TEXT', 1, '80', '0');
INSERT INTO SYS_CONFIG (CONFIGID, CONFIGKEY, FIELDSET, CONFIGNAME, CONFIGDESC, TYPENAME, DATATYPE, DATAVALUE, DELFLAG)
VALUES (8, 'sms.csid', '签名编号', '预设的企业签名编号', '请使用自己企业已通过审核的签名编号', 'TEXT', 1, '101', '0');
INSERT INTO SYS_CONFIG (CONFIGID, CONFIGKEY, FIELDSET, CONFIGNAME, CONFIGDESC, TYPENAME, DATATYPE, DATAVALUE, DELFLAG)
VALUES (9, 'remainddays.cert', '证书到期提醒时间', '证书到期提醒时间', '证书到期提醒时间', 'TEXT', 1, '30', '1');
INSERT INTO SYS_CONFIG (CONFIGID, CONFIGKEY, FIELDSET, CONFIGNAME, CONFIGDESC, TYPENAME, DATATYPE, DATAVALUE, DELFLAG)
VALUES (10, 'remainddays.insure', '保险到期提醒时间', '保险到期提醒时间', '保险到期提醒时间', 'TEXT', 1, '30', '1');
INSERT INTO SYS_CONFIG (CONFIGID, CONFIGKEY, FIELDSET, CONFIGNAME, CONFIGDESC, TYPENAME, DATATYPE, DATAVALUE, DELFLAG)
VALUES (11, 'contract.lease', '租赁合同模版地址', '租赁合同模版地址', '租赁合同模版地址', 'TEXT', 0, '/contract/lease.ftl', '0');
INSERT INTO SYS_CONFIG (CONFIGID, CONFIGKEY, FIELDSET, CONFIGNAME, CONFIGDESC, TYPENAME, DATATYPE, DATAVALUE, DELFLAG)
VALUES (12, 'contract.subcontract', '一体化合同模版地址', '一体化合同模版地址', '一体化合同模版地址', 'TEXT', 0, '/contract/subcontract.ftl', '0');
INSERT INTO SYS_CONFIG (CONFIGID, CONFIGKEY, FIELDSET, CONFIGNAME, CONFIGDESC, TYPENAME, DATATYPE, DATAVALUE, DELFLAG)
VALUES (13, 'companyName', '企业名称', '企业名称', '企业名称', 'TEXT', 0, '企业名称', 0);
INSERT INTO SYS_CONFIG (CONFIGID, CONFIGKEY, FIELDSET, CONFIGNAME, CONFIGDESC, TYPENAME, DATATYPE, DATAVALUE, DELFLAG)
VALUES (14, 'companyType', '企业类型', '企业类型', '企业类型', 'TEXT', 0, '100', 0);
INSERT INTO SYS_CONFIG (CONFIGID, CONFIGKEY, FIELDSET, CONFIGNAME, CONFIGDESC, TYPENAME, DATATYPE, DATAVALUE, DELFLAG)
VALUES (15, 'companyAddress', '企业地址', '企业地址', '企业地址', 'TEXT', 0, '企业地址', 0);
INSERT INTO SYS_CONFIG (CONFIGID, CONFIGKEY, FIELDSET, CONFIGNAME, CONFIGDESC, TYPENAME, DATATYPE, DATAVALUE, DELFLAG)
VALUES (16, 'sitUrl', '服务器地址', '服务器地址', '服务器地址', 'TEXT', 0, 'http://risit.meibu.net:19085/emms', 1);
INSERT INTO SYS_CONFIG (CONFIGID, CONFIGKEY, FIELDSET, CONFIGNAME, CONFIGDESC, TYPENAME, DATASTORE, DATATYPE, DATAVALUE, DELFLAG)
VALUES (17, 'appAccessSwitch', 'APP接入', '用户信息是否同步APP', 'APP接入', 'COMBO', '0:关;1:开', 2, '0', 1);
INSERT INTO SYS_CONFIG (CONFIGID, CONFIGKEY, FIELDSET, CONFIGNAME, CONFIGDESC, TYPENAME, DATATYPE, DATAVALUE, DELFLAG)
VALUES (18, 'appAccessUrl', 'APP接入地址', 'APP接入地址', 'APP接入地址', 'TEXT', 0, 'http://risit.meibu.net:18080/apps/services/SysService', 0);
INSERT INTO SYS_CONFIG (CONFIGKEY, FIELDSET, CONFIGNAME, CONFIGDESC, TYPENAME, DATATYPE, DATAVALUE, DELFLAG)
VALUES ('contract.lease', '租赁合同模版地址', '租赁合同模版地址', '租赁合同模版地址', 'TEXT', 0, '/contract/lease.ftl', '0');
INSERT INTO SYS_CONFIG (CONFIGKEY, FIELDSET, CONFIGNAME, CONFIGDESC, TYPENAME, DATATYPE, DATAVALUE, DELFLAG)
VALUES ('contract.subcontract', '一体化合同模版地址', '一体化合同模版地址', '一体化合同模版地址', 'TEXT', 0, '/contract/subcontract.ftl', '0');
INSERT INTO SYS_CONFIG (CONFIGKEY, FIELDSET, CONFIGNAME, CONFIGDESC, TYPENAME, DATATYPE, DATAVALUE, DELFLAG)
VALUES ('overdue.payment', '催款函模版地址', '催款函模版地址', '催款函模版地址', 'TEXT', 0, '/overdue/payment.ftl', '0');
SET IDENTITY_INSERT SYS_CONFIG OFF;

SET IDENTITY_INSERT APP_ROLE ON;
INSERT INTO APP_ROLE (ROLEID, ROLENAME, ROLEDESC, STATUS, ROLE_TYPE, RIGHTS, ISDEFAULTIN)
VALUES (-1, '超级管理员', '超级管理员,具有所有权限', 1, '0', '__ALL', 0);
SET IDENTITY_INSERT APP_ROLE OFF;

INSERT INTO USER_ROLE (USERID, ROLEID)
VALUES (1, -1);