--2014-02-11
ALTER TABLE T_EQUIPMENT_DETECT ALTER COLUMN DETECT_ENT BIGINT NULL;
ALTER TABLE T_INSURE_EQUIPMENT DROP CONSTRAINT UQ_T_INSURE_EQUIPMENT1;
--2014-02-26
ALTER TABLE T_PURCHASE ALTER COLUMN SUPPLIER_TEL VARCHAR(16) NULL;
CREATE TABLE T_SETTLE_ITEM_BRIEF
(
  SI_BRIEF_ID                BIGINT IDENTITY PRIMARY KEY,
  SETTLE_ID                  BIGINT NOT NULL,                --结算ID
  SETTLE_ITEM_NAME           VARCHAR(64) NOT NULL,           --费用项目
  QUANTITY                   SMALLINT NOT NULL,              --数量
  UNITPRICE                  NUMERIC(12, 2) NOT NULL,        --费用单价
  MEASUREMENT                VARCHAR(16) NOT NULL,           --租金计量单位(表码 BM_MEASUREMENT)
  DEDUCT_RENT                NUMERIC(12, 2) NOT NULL,        --应扣租金
  ITEM_CUMULATE              NUMERIC(12, 2) NOT NULL,        --费用累计
  SUMMARY                    NUMERIC(12, 2) NOT NULL,        --租金累计
  REMARK                     VARCHAR(256) NULL               --备注
);
--2014-03-09
ALTER TABLE T_CORP_INFO ADD CERT_ID BIGINT NULL;
ALTER TABLE T_CORP_CERT ADD DEFAULT_CERT CHAR(1) NOT NULL DEFAULT '0';

ALTER TABLE T_PROJECT ADD PRACTI_ID BIGINT NULL;
ALTER TABLE T_PROJECT ADD PRACTI_NAME VARCHAR(64) NULL;
ALTER TABLE T_PROJECT ADD REQS_DESC VARCHAR(512) NULL;
ALTER TABLE T_PROJECT ADD EXPECT_END_DATE CHAR(10) NULL;
ALTER TABLE T_PROJECT ADD STATUS CHAR(1) NOT NULL DEFAULT '1';
--项目商务记录
CREATE TABLE T_PROJECT_EXPENSE(
  PROJECT_EXPENSE_ID        BIGINT IDENTITY PRIMARY KEY,
  PROJECT_ID                BIGINT NOT NULL,                 --项目ID
  SPEND_DATE                CHAR(10) NULL,                   --发生时间
  DISCRIPTION               VARCHAR(64) NULL,                --内容描述
  STATUS                    VARCHAR(8) NULL,                 --完成状态
  EXPENSE_AMOUNT            NUMERIC(12, 2) NULL,             --发生费用(可选填)
  EXPENSE_DESC              VARCHAR(64) NULL,                --费用说明(可选填)
  REMARK                    VARCHAR(264) NULL                --备注
)

ALTER TABLE BM_COMPONENT_GENERIC ADD NAME VARCHAR(30) NULL;
UPDATE INIT_LOAD_TABLE SET ALIAS_FIELD_NAME = 'NAME', ALIAS_FIELD_LABLE = '类别简称' WHERE TABLE_ALIAS = 'componGeneric';

ALTER TABLE T_COMPONENT ADD CONSUME_FLAG CHAR(1) NOT NULL DEFAULT 0;
ALTER TABLE T_COMPONENT ADD CONSUME_COUNTS SMALLINT NOT NULL DEFAULT 1;
ALTER TABLE T_COMPONENT ADD KNOT_METRIC NUMERIC(12, 2) NULL;
ALTER TABLE T_COMPONENT ADD BRACHIUM NUMERIC(12, 2) NULL;

ALTER TABLE T_DISPATCH_EQUIP DROP COLUMN RECORD_SERIAL;
ALTER TABLE T_DISPATCH_EQUIP DROP COLUMN EQUIP_CATEGORY;
ALTER TABLE T_DISPATCH_EQUIP DROP COLUMN EQUIP_GENERIC;
ALTER TABLE T_DISPATCH_EQUIP DROP COLUMN EQUIP_SPECIFIC;
ALTER TABLE T_DISPATCH_EQUIP DROP COLUMN RECORD_ID;
ALTER TABLE T_DISPATCH_EQUIP DROP COLUMN EXW_SERIAL;
ALTER TABLE T_DISPATCH_EQUIP DROP COLUMN PROPERTY_ENT;
ALTER TABLE T_DISPATCH_EQUIP DROP COLUMN PROPERTY_NAME;

ALTER TABLE T_DISPATCH_COMPON DROP COLUMN COMPON_SERIAL;
ALTER TABLE T_DISPATCH_COMPON DROP COLUMN COMPON_CATEGORY;
ALTER TABLE T_DISPATCH_COMPON DROP COLUMN COMPON_GENERIC;
ALTER TABLE T_DISPATCH_COMPON DROP COLUMN COMPON_SPECIFIC;
ALTER TABLE T_DISPATCH_COMPON ADD COUNTS SMALLINT NOT NULL DEFAULT 1;

ALTER TABLE T_DISPATCH_PRACTI DROP COLUMN PRACTI_NAME;
ALTER TABLE T_DISPATCH_PRACTI DROP COLUMN MOBILE;
ALTER TABLE T_DISPATCH_PRACTI DROP COLUMN STATION;
ALTER TABLE T_DISPATCH_PRACTI DROP COLUMN CORP_ID;
ALTER TABLE T_DISPATCH_PRACTI DROP COLUMN CORP_NAME;
ALTER TABLE T_DISPATCH_PRACTI DROP COLUMN DEP_ID;
ALTER TABLE T_DISPATCH_PRACTI DROP COLUMN DEP_NAME;
ALTER TABLE T_DISPATCH_PRACTI DROP COLUMN KIND_WORK;

ALTER TABLE T_EQUIPMENT_DIARY ADD STORE_ID BIGINT NULL;
ALTER TABLE T_EQUIPMENT_DIARY ADD DISPATCH_ID BIGINT NULL;
EXEC SP_RENAME 'T_EQUIPMENT_DIARY.[DISPATCH_EQUIP_ID]','RELATE_EQUIP_ID','COLUMN';

ALTER TABLE T_COMPONENT_DIARY ADD COUNTS SMALLINT NOT NULL DEFAULT 1;
ALTER TABLE T_COMPONENT_DIARY ADD STORE_ID BIGINT NULL;
ALTER TABLE T_COMPONENT_DIARY ADD DISPATCH_ID BIGINT NULL;
EXEC SP_RENAME 'T_COMPONENT_DIARY.[DISPATCH_COMPON_ID]','RELATE_COMPON_ID','COLUMN';

ALTER TABLE T_PRACTI_DIARY ADD DISPATCH_ID BIGINT NULL;
EXEC SP_RENAME 'T_PRACTI_DIARY.[DISPATCH_PRACTI_ID]','RELATE_PRACTI_ID','COLUMN';

ALTER TABLE T_CONTRACT_LEASE ADD SUBCONTRACT CHAR(1) NOT NULL DEFAULT '0';
ALTER TABLE T_CONTRACT_LEASE ADD ENTERPRISE_SERIAL VARCHAR(32) NULL;
ALTER TABLE T_CONTRACT_LEASE ADD OVERALL_HEIGHT NUMERIC(12, 2) NULL;
ALTER TABLE T_CONTRACT_LEASE ADD BUILDING_QUANTITY INT NULL;
ALTER TABLE T_CONTRACT_LEASE ADD COVER NUMERIC(12, 2) NULL;

ALTER TABLE T_CONTRACT_LEASE ALTER COLUMN CONTRACT_CATEGORY VARCHAR(6) NULL;
ALTER TABLE T_CONTRACT_LEASE ALTER COLUMN SALESMAN_ID BIGINT NULL;
ALTER TABLE T_CONTRACT_LEASE ALTER COLUMN SALESMAN VARCHAR(32) NULL;
ALTER TABLE T_CONTRACT_LEASE ALTER COLUMN PROJECT_NAME VARCHAR(64) NULL;
ALTER TABLE T_CONTRACT_LEASE ALTER COLUMN SIGNING_TIME CHAR(10) NULL;

ALTER TABLE T_CONTRACT_EQUIP ALTER COLUMN RENT_STANDARD NUMERIC(12, 2) NULL;
ALTER TABLE T_CONTRACT_EQUIP ALTER COLUMN MEASUREMENT VARCHAR(16) NULL;
ALTER TABLE T_CONTRACT_EQUIP ADD WALL_ATTACHE_QTY SMALLINT NULL;
ALTER TABLE T_CONTRACT_EQUIP ADD REMARK VARCHAR(256) NULL;
--租赁设备费用
CREATE TABLE T_CONTRACT_EQUIP_OUTLAY (
  CONTRACT_EQUIPOUTLAY_ID    BIGINT IDENTITY PRIMARY KEY,
  CONTRACT_ID                BIGINT NOT NULL,                --租赁合同ID
  EQUIP_ID                   BIGINT NOT NULL,                --租赁设备(设备档案)
  EQUIP_CATEGORY             VARCHAR(12) NOT NULL,           --租赁设备类别(表码 BM_REPERTORY_CATEGORY)
  EQUIP_GENERIC              VARCHAR(6) NOT NULL,            --设备名称(表码 BM_EQUIP_GENERIC)
  EQUIP_SPECIFIC             VARCHAR(6) NOT NULL,            --规格型号(表码 BM_EQUIP_SPECIFIC)
  EQUIP_VENDER               VARCHAR(64) NOT NULL,           --品牌
  QUANTITY                   INT NULL,                       --数量
  EMPLOY_OUTLAY              NUMERIC(12, 2) NULL,            --机械使用费用(元/月/台)
  INSTALL_OUTLAY             NUMERIC(12, 2) NULL,            --安装进场费(元/次/台)
  DISMANTLE_OUTLAY           NUMERIC(12, 2) NULL,            --拆卸退场费(元/次/台)
  MANT_OUTLAY                NUMERIC(12, 2) NULL,            --维护保养费(元/月/台)
  SUMMARY                    NUMERIC(12, 2) NOT NULL         --小计
);
--租赁设备费用
CREATE TABLE T_CONTRACT_EQUIP_COST (
  CONTRACT_EQUIPCOST_ID      BIGINT IDENTITY PRIMARY KEY,
  CONTRACT_ID                BIGINT NOT NULL,                --租赁合同ID
  EQUIP_ID                   BIGINT NOT NULL,                --租赁设备(设备档案)
  EQUIP_CATEGORY             VARCHAR(12) NOT NULL,           --租赁设备类别(表码 BM_REPERTORY_CATEGORY)
  EQUIP_GENERIC              VARCHAR(6) NOT NULL,            --设备名称(表码 BM_EQUIP_GENERIC)
  EQUIP_SPECIFIC             VARCHAR(6) NOT NULL,            --规格型号(表码 BM_EQUIP_SPECIFIC)
  QUANTITY                   INT NULL,                       --数量
  EMBEDDED_COST              NUMERIC(12, 2) NULL,            --机械预埋件(元/套)
  LIFTING_COST               NUMERIC(12, 2) NULL,            --顶升加节费(元/节)
  ANCHOR_COST                NUMERIC(12, 2) NULL,            --锚固费(元/套)
  EXTRA_COST                 NUMERIC(12, 2) NULL,            --特殊按拆设备费
  SUMMARY                    NUMERIC(12, 2) NOT NULL         --小计
);
ALTER TABLE T_CONTRACT_PRACTI_BRIEF ADD END_DATE CHAR(10) NULL;
ALTER TABLE T_CONTRACT_PRACTI_BRIEF ADD SUMMARY NUMERIC(12, 2) NULL;
ALTER TABLE T_CONTRACT_PRACTI_BRIEF ADD REMARK VARCHAR(128) NULL;
ALTER TABLE T_CONTRACT_PRACTI_BRIEF ALTER COLUMN START_DATE CHAR(10) NULL;
ALTER TABLE T_CONTRACT_PRACTI_BRIEF ALTER COLUMN MEASUREMENT VARCHAR(16) NULL;

--检验项目
CREATE TABLE T_VERIFY_ITEM
(
  ITEM_ID                    BIGINT IDENTITY PRIMARY KEY,
  ITEM_NAME                  VARCHAR(128) NOT NULL,          --项目名称
  ITEM_PARENT                BIGINT NULL,                    --父级项目
  VITEM_TYPE                 VARCHAR(4) NOT NULL DEFAULT '0',--项目类型(表码表 VITEM_TYPE)
  PATH                       VARCHAR(256) NULL,              --路径
  LEVEL                      INT NOT NULL,                   --层次
  DEL_FLAG                   CHAR(1) NOT NULL DEFAULT 1      --删除标识(表码 0:删除,1:正常)
);
--检验项目要求
CREATE TABLE T_VERIFY_ITEM_DEMAND
(
  DEMAND_ID                  BIGINT IDENTITY PRIMARY KEY,
  ITEM_ID                    BIGINT NOT NULL,                --检验项目ID
  DEMAND_DES                 VARCHAR(512) NULL               --检验要求
);
CREATE TABLE T_VERIFY_STANDARD
(
  STANDARD_ID                BIGINT IDENTITY PRIMARY KEY,
  RELATE_ID                  BIGINT NOT NULL,                --关联业务
  RELATE_MODULE              VARCHAR(32) NOT NULL,           --关联业务模块
  ITEM_NAME                  VARCHAR(128) NOT NULL,          --检测项目
  PARENT_NAME                VARCHAR(128) NULL,              --检测分类
  LEVEL                      INT NOT NULL,                   --层次
  DEMAND_DES                 VARCHAR(512) NOT NULL,          --检测要求
  STANDARD_RESULT            VARCHAR(32) NULL,               --检测结果(表码值 1:合格,2:不合格)
  REMARK                     VARCHAR(512) NULL,              --检测结论
  SUMMARY                    VARCHAR(512) NULL               --检测摘要
);
--安全协议
CREATE TABLE T_SECURE_PROTOCOL
(
  PROTOCOL_ID                BIGINT IDENTITY PRIMARY KEY,
  PROTOCOL_SERIAL            VARCHAR(64) NOT NULL,           --协议编号(企业简码+AQ+年月日+2位流水号)
  PROVIDED_DATE              CHAR(10) NOT NULL,              --填报日期(默认为当前日期)
  EM_ENT                     BIGINT NOT NULL,                --使用单位(来原合同中的"承租方",仍可手动修改,来源客户档案)
  EM_MODULE                  VARCHAR(32) NOT NULL,           --使用单位模块(企业档案/客户档案)
  EM_ENT_NAME                VARCHAR(64) NOT NULL,           --使用单位名称
  IN_ENT                     BIGINT NOT NULL,                --安装单位(来源合同中的"出租方",仍可手动修改,来源企业信息)
  IN_MODULE                  VARCHAR(32) NOT NULL,           --安装单位模块(企业档案/客户档案)
  IN_ENT_NAME                VARCHAR(64) NOT NULL,           --安装单位名称
  IN_ENT_CERT_NUM            VARCHAR(24) NULL,               --安装资质证书编号
  IN_ENT_TITLE_LEVEL         VARCHAR(6) NULL,                --安装资质等级(表码 BM_CERT_LEVEL)
  PROJECT_ID                 BIGINT NOT NULL,                --项目ID(来源合同中项目信息)
  PROJECT_NAME               VARCHAR(64) NOT NULL,           --项目名称
  ADDRESS                    VARCHAR(256) NOT NULL,          --项目地址
  EQUIP_ID                   BIGINT NULL,                    --关联设备(来源设备档案)
  RECORD_ID                  VARCHAR(24) NULL,               --备案编号
  EQUIP_GENERIC              VARCHAR(6) NOT NULL,            --设备名称(表码 BM_EQUIP_GENERIC)
  FINAL_HEIGHT               VARCHAR(8) NULL,                --最终安装高度(M)
  WALL_ATTACHE_QTY           SMALLINT NULL,                  --附墙道数
  REMARK                     VARCHAR(512) NULL,              --备注
  RELATE_MODULE              VARCHAR(32) NOT NULL,           --模块类型(EQUIP_INSTALL:安装模块,EQUIP_EMPLOY:使用模块)
  DEL_FLAG                   CHAR(1) NOT NULL                --删除标识(表码 0:删除,1:正常)
);
--安拆协议
CREATE TABLE T_INDIS_PROTOCOL
(
  PROTOCOL_ID                BIGINT IDENTITY PRIMARY KEY,
  PROTOCOL_SERIAL            VARCHAR(64) NOT NULL,           --协议编号(企业简码+AZ+年月日+2位流水号)
  PROVIDED_DATE              CHAR(10) NOT NULL,              --填报日期(默认为当前日期)
  EM_ENT                     BIGINT NOT NULL,                --使用单位(来原合同中的"承租方",仍可手动修改,来源客户档案)
  EM_MODULE                  VARCHAR(32) NOT NULL,           --使用单位模块(企业档案/客户档案)
  EM_ENT_NAME                VARCHAR(64) NOT NULL,           --使用单位名称
  IN_ENT                     BIGINT NOT NULL,                --安装单位(来源合同中的"出租方",仍可手动修改,来源企业信息)
  IN_MODULE                  VARCHAR(32) NOT NULL,           --安装单位模块(企业档案/客户档案)
  IN_ENT_NAME                VARCHAR(64) NOT NULL,           --安装单位名称
  IN_ENT_CERT_NUM            VARCHAR(24) NULL,               --安装资质证书编号
  IN_ENT_TITLE_LEVEL         VARCHAR(6) NULL,                --安装资质等级(表码 BM_CERT_LEVEL)
  PROJECT_ID                 BIGINT NOT NULL,                --项目ID(来源合同中项目信息)
  PROJECT_NAME               VARCHAR(64) NOT NULL,           --项目名称
  ADDRESS                    VARCHAR(256) NOT NULL,          --项目地址
  INITIAL_HEIGHT             VARCHAR(8) NULL,                --安装高度
  FINAL_HEIGHT               VARCHAR(8) NULL,                --最终安装高度
  WALL_ATTACHE_QTY           SMALLINT NULL,                  --附墙道数
  REMARK                     VARCHAR(512) NULL,              --备注
  RELATE_MODULE              VARCHAR(32) NOT NULL,           --模块类型(EQUIP_INSTALL:安装模块,EQUIP_EMPLOY:使用模块)
  DEL_FLAG                   CHAR(1) NOT NULL                --删除标识(表码 0:删除,1:正常)
);
--安拆协议设备清单
CREATE TABLE T_INDIS_PROTOCOL_EQUIP
(
  PROTOCOL_EQUIP_ID          BIGINT IDENTITY PRIMARY KEY,
  PROTOCOL_ID                BIGINT NOT NULL,                --安拆协议ID
  SEQ                        SMALLINT NOT NULL,              --序号
  EQUIP_ID                   BIGINT NULL,                    --关联设备(来源合同设备档案)
  EQUIP_GENERIC              VARCHAR(6) NOT NULL,            --设备名称(表码 BM_EQUIP_GENERIC)
  EQUIP_SPECIFIC             VARCHAR(6) NOT NULL,            --规格型号(表码 BM_EQUIP_SPECIFIC)
  RECORD_ID                  VARCHAR(24) NULL,               --备案编号
  EXW_SERIAL                 VARCHAR(24) NULL,               --出厂编号
  EQUIP_VENDER               VARCHAR(128) NOT NULL,          --制造厂家
  QUANTITY                   SMALLINT NOT NULL,              --数量
  INSTALL_AMOUNT             NUMERIC(12, 2) NOT NULL,        --安装总费用(元/台)
  INSTALL_SUMMARY            NUMERIC(12, 2) NOT NULL         --安装费用小计(元)=安装总费用*数量
);
--安拆方案
CREATE TABLE T_INDIS_SCHEME
(
  SCHEME_ID                  BIGINT IDENTITY PRIMARY KEY,
  SCHEME_SERIAL              VARCHAR(64) NOT NULL,           --编号(企业简码+FA+年月日+2位流水号)
  PROVIDED_DATE              CHAR(10) NOT NULL,              --填报日期(默认为当前日期)
  EM_ENT                     BIGINT NOT NULL,                --使用单位(来原合同中的"承租方",仍可手动修改,来源客户档案)
  EM_MODULE                  VARCHAR(32) NOT NULL,           --使用单位模块(企业档案/客户档案)
  EM_ENT_NAME                VARCHAR(64) NOT NULL,           --使用单位名称
  IN_ENT                     BIGINT NOT NULL,                --安装单位(来源合同中的"出租方",仍可手动修改,来源企业信息)
  IN_MODULE                  VARCHAR(32) NOT NULL,           --安装单位模块(企业档案/客户档案)
  IN_ENT_NAME                VARCHAR(64) NOT NULL,           --安装单位名称
  IN_ENT_CERT_NUM            VARCHAR(24) NULL,               --安装资质证书编号
  IN_ENT_TITLE_LEVEL         VARCHAR(6) NULL,                --安装资质等级(表码 BM_CERT_LEVEL)
  PROJECT_ID                 BIGINT NOT NULL,                --项目ID(来源合同中项目信息)
  PROJECT_NAME               VARCHAR(64) NOT NULL,           --项目名称
  ADDRESS                    VARCHAR(256) NOT NULL,          --项目地址
  EQUIP_ID                   BIGINT NULL,                    --关联设备(来源合同设备档案)
  EQUIP_GENERIC              VARCHAR(6) NOT NULL,            --设备名称(表码 BM_EQUIP_GENERIC)
  EQUIP_SPECIFIC             VARCHAR(6) NOT NULL,            --规格型号(表码 BM_EQUIP_SPECIFIC)
  RECORD_ID                  VARCHAR(24) NULL,               --备案编号
  EXW_SERIAL                 VARCHAR(24) NULL,               --出厂编号
  EQUIP_VENDER               VARCHAR(128) NOT NULL,          --制造厂家
  TECHNICAL_DIRECTOR         VARCHAR(32) NULL,               --技术负责人(可选填)
  TECHNICAL_PHONE            VARCHAR(16) NULL,               --电话
  SECURE_DIRECTOR            VARCHAR(32) NULL,               --安全负责人(可选填)
  SECURE_PHONE               VARCHAR(16) NULL,               --电话
  SCHEME_DESIGNER            VARCHAR(32) NULL,               --方案编制人(可选填)
  SCHEME_PHONE               VARCHAR(16) NULL,               --电话
  OVERALL_HEIGHT             NUMERIC(12, 2) NULL,            --建筑高度(M)
  FINAL_HEIGHT               VARCHAR(8) NULL,                --最终安装高度(M)
  REMARK                     VARCHAR(512) NULL,              --备注
  RELATE_MODULE              VARCHAR(32) NOT NULL,           --模块类型(EQUIP_INSTALL:安装模块,EQUIP_EMPLOY:使用模块)
  DEL_FLAG                   CHAR(1) NOT NULL                --删除标识(表码 0:删除,1:正常)
);
--应急预案
CREATE TABLE T_CONTINGENCY_PLAN
(
  CONTINGENCY_ID             BIGINT IDENTITY PRIMARY KEY,
  CONTINGENCY_SERIAL         VARCHAR(64) NOT NULL,           --应急预案编号(企业简码+YJ+年月日+2位流水号)、填报日期(默认为当前日期)
  PROVIDED_DATE              CHAR(10) NOT NULL,              --填报日期(默认为当前日期)
  EM_ENT                     BIGINT NOT NULL,                --使用单位(来原合同中的"承租方",仍可手动修改,来源客户档案)
  EM_MODULE                  VARCHAR(32) NOT NULL,           --使用单位模块(企业档案/客户档案)
  EM_ENT_NAME                VARCHAR(64) NOT NULL,           --使用单位名称
  IN_ENT                     BIGINT NOT NULL,                --安装单位(来源合同中的"出租方",仍可手动修改,来源企业信息)
  IN_MODULE                  VARCHAR(32) NOT NULL,           --安装单位模块(企业档案/客户档案)
  IN_ENT_NAME                VARCHAR(64) NOT NULL,           --安装单位名称
  IN_ENT_CERT_NUM            VARCHAR(24) NULL,               --安装资质证书编号
  IN_ENT_TITLE_LEVEL         VARCHAR(6) NULL,                --安装资质等级(表码 BM_CERT_LEVEL)
  PROJECT_ID                 BIGINT NOT NULL,                --项目ID(来源合同中项目信息)
  PROJECT_NAME               VARCHAR(64) NOT NULL,           --项目名称
  ADDRESS                    VARCHAR(256) NOT NULL,          --项目地址
  EQUIP_ID                   BIGINT NULL,                    --关联设备(来源合同设备档案)
  EQUIP_GENERIC              VARCHAR(6) NOT NULL,            --设备名称(表码 BM_EQUIP_GENERIC)
  EQUIP_SPECIFIC             VARCHAR(6) NOT NULL,            --规格型号(表码 BM_EQUIP_SPECIFIC)
  RECORD_ID                  VARCHAR(24) NULL,               --备案编号
  EXW_SERIAL                 VARCHAR(24) NULL,               --出厂编号
  EQUIP_VENDER               VARCHAR(128) NOT NULL,          --制造厂家
  OVERALL_HEIGHT             NUMERIC(12, 2) NULL,            --建筑高度(M)
  FINAL_HEIGHT               VARCHAR(8) NULL,                --最终安装高度(M)
  CONTINGENCY_PHONE          VARCHAR(16) NULL,               --应急办公电话
  REMARK                     VARCHAR(512) NULL,              --备注
  RELATE_MODULE              VARCHAR(32) NOT NULL,           --模块类型(EQUIP_INSTALL:安装模块,EQUIP_EMPLOY:使用模块)
  DEL_FLAG                   CHAR(1) NOT NULL                --删除标识(表码 0:删除,1:正常)
);
--应急预案人员
CREATE TABLE T_CONTINGENCY_WORKER
(
  WORKER_ID                  BIGINT IDENTITY PRIMARY KEY,
  CONTINGENCY_ID             BIGINT NOT NULL,                --预案ID
  SEQ                        SMALLINT NOT NULL,              --序号
  NAME                       VARCHAR(32) NULL,               --姓名
  DUTIES                     VARCHAR(32) NULL,               --职务
  CONTINGENCY_DUTIES         VARCHAR(32) NULL,               --应急救援职务
  PHONE                      VARCHAR(16) NULL                --电话
);
--安拆前检查
CREATE TABLE T_INDIS_PRECHECK
(
  PRECHECK_ID                BIGINT IDENTITY PRIMARY KEY,
  PRECHECK_SERIAL            VARCHAR(64) NOT NULL,           --编号(企业简码+JC+年月日+2位流水号)
  PROVIDED_DATE              CHAR(10) NOT NULL,              --填报日期(默认为当前日期)
  IN_ENT                     BIGINT NOT NULL,                --安装单位(来源合同中的"出租方",仍可手动修改,来源企业信息)
  IN_MODULE                  VARCHAR(32) NOT NULL,           --安装单位模块(企业档案/客户档案)
  IN_ENT_NAME                VARCHAR(64) NOT NULL,           --安装单位名称
  IN_ENT_CERT_NUM            VARCHAR(24) NULL,               --安装资质证书编号
  IN_ENT_TITLE_LEVEL         VARCHAR(6) NULL,                --安装资质等级(表码 BM_CERT_LEVEL)
  PROJECT_ID                 BIGINT NOT NULL,                --项目ID(来源合同中项目信息)
  PROJECT_NAME               VARCHAR(64) NOT NULL,           --项目名称
  ADDRESS                    VARCHAR(256) NOT NULL,          --项目地址
  EQUIP_ID                   BIGINT NULL,                    --关联设备(来源合同设备档案)
  EQUIP_GENERIC              VARCHAR(6) NOT NULL,            --设备名称(表码 BM_EQUIP_GENERIC)
  EQUIP_SPECIFIC             VARCHAR(6) NOT NULL,            --规格型号(表码 BM_EQUIP_SPECIFIC)
  RECORD_ID                  VARCHAR(24) NULL,               --备案编号
  EXW_SERIAL                 VARCHAR(24) NULL,               --出厂编号
  BUILDING_NUM               VARCHAR(64) NULL,               --楼号
  REMARK                     VARCHAR(512) NULL,              --备注
  RELATE_MODULE              VARCHAR(32) NOT NULL,           --模块类型(EQUIP_INSTALL:安装模块,EQUIP_EMPLOY:使用模块)
  DEL_FLAG                   CHAR(1) NOT NULL                --删除标识(表码 0:删除,1:正常)
);
--基础验收
CREATE TABLE T_INDIS_BASECHECK
(
  BASECHECK_ID               BIGINT IDENTITY PRIMARY KEY,
  BASECHECK_SERIAL           VARCHAR(64) NOT NULL,           --编号(企业简码+YS+年月日+2位流水号)
  PROVIDED_DATE              CHAR(10) NOT NULL,              --填报日期(默认为当前日期)--填报日期(默认为当前日期)
  EM_ENT                     BIGINT NOT NULL,                --使用单位(来原合同中的"承租方",仍可手动修改,来源客户档案)
  EM_MODULE                  VARCHAR(32) NOT NULL,           --使用单位模块(企业档案/客户档案)
  EM_ENT_NAME                VARCHAR(64) NOT NULL,           --使用单位名称
  IN_ENT                     BIGINT NOT NULL,                --安装单位(来源合同中的"出租方",仍可手动修改,来源企业信息)
  IN_MODULE                  VARCHAR(32) NOT NULL,           --安装单位模块(企业档案/客户档案)
  IN_ENT_NAME                VARCHAR(64) NOT NULL,           --安装单位名称
  PROJECT_ID                 BIGINT NOT NULL,                --项目ID(来源合同中项目信息)
  PROJECT_NAME               VARCHAR(64) NOT NULL,           --项目名称
  ADDRESS                    VARCHAR(256) NOT NULL,          --项目地址
  EQUIP_ID                   BIGINT NULL,                    --关联设备(来源合同设备档案)
  EQUIP_GENERIC              VARCHAR(6) NOT NULL,            --设备名称(表码 BM_EQUIP_GENERIC)
  EQUIP_SPECIFIC             VARCHAR(6) NOT NULL,            --规格型号(表码 BM_EQUIP_SPECIFIC)
  RECORD_ID                  VARCHAR(24) NULL,               --备案编号
  EXW_SERIAL                 VARCHAR(24) NULL,               --出厂编号
  BUILDING_NUM               VARCHAR(64) NULL,               --楼号(可选填)
  MANAGER_PROJECT            VARCHAR(32) NULL,               --项目经理
  MANAGER_PHONE              VARCHAR(16) NULL,               --联系电话
  REMARK                     VARCHAR(512) NULL,              --备注
  DEL_FLAG                   CHAR(1) NOT NULL                --删除标识(表码 0:删除,1:正常)
);
--技术交底
CREATE TABLE T_TECHNICAL_DISCLOSURE
(
  DISCLOSURE_ID              BIGINT IDENTITY PRIMARY KEY,
  DISCLOSURE_SERIAL          VARCHAR(64) NOT NULL,           --编号(企业简码+JD+年月日+2位流水号)
  PROJECT_ID                 BIGINT NOT NULL,                --项目ID(来源于安装管理)
  PROJECT_NAME               VARCHAR(64) NOT NULL,           --交底项目
  ERECTING_EQUIPART          VARCHAR(64) NULL,               --起重设备配备
  DELIVERY_EQUIPART          VARCHAR(64) NULL,               --运输设备配备
  ACCEPTANCE_MAN             VARCHAR(64) NULL,               --接受人
  DISCLOSURE_MAN             VARCHAR(64) NULL,               --交底人
  RELEVANCE_MAN              VARCHAR(64) NULL,               --关联人员
  DISCLOSURE_DATE            CHAR(10) NULL,                  --交底日期
  CONTENTS                   VARCHAR(4000) NULL,             --交底内容(注:默认内容参见打印样式表,默认内容仍可编辑,字数控制在2500个)
  REPLENISH_CONTENTS         VARCHAR(4000) NULL,             --其他针对性安全技术交底(同上)
  REMARK                     VARCHAR(512) NULL,              --备注
  RELATE_MODULE              VARCHAR(32) NOT NULL,           --模块类型(EQUIP_INSTALL:安装模块,EQUIP_EMPLOY:使用模块)
  DEL_FLAG                   CHAR(1) NOT NULL                --删除标识(表码 0:删除,1:正常)
);
--隐患上报
CREATE TABLE T_RISK
(
  RISK_ID                    BIGINT IDENTITY PRIMARY KEY,
  RISK_SERIAL                VARCHAR(24) NOT NULL,           --通知编号(企业简码+ZG+年月日+2位流水号)
  RISK_THEME                 VARCHAR(96) NOT NULL,           --通知主题
  INSPECT_DATE               CHAR(10) NOT NULL,              --检查日期
  EQUIP_ID                   BIGINT NOT NULL,                --整改设备(来源设备档案)
  EQUIP_CATEGORY             VARCHAR(12) NOT NULL,           --设备类别(表码 BM_REPERTORY_CATEGORY)
  EQUIP_GENERIC              VARCHAR(6) NOT NULL,            --设备名称(表码 BM_EQUIP_GENERIC)
  EQUIP_SPECIFIC             VARCHAR(6) NOT NULL,            --规格型号(表码 BM_EQUIP_SPECIFIC)
  RECORD_ID                  VARCHAR(24) NULL,               --备案编号
  EXW_SERIAL                 VARCHAR(24) NULL,               --出厂编号
  PROJECT_ID                 BIGINT NOT NULL,                --项目ID(来源项目信息)
  PROJECT_NAME               VARCHAR(64) NOT NULL,           --项目名称
  ADDRESS                    VARCHAR(256) NOT NULL,          --项目地址
  CHECK_DEPARTMENT           VARCHAR(16) NOT NULL,           --检查部门
  CHECK_CUSTOM               BIGINT NOT NULL,                --检查单位ID(来源客户档案)
  CHECK_CUSTOM_NAME          VARCHAR(64) NOT NULL,           --检查单位
  INSPECTOR                  VARCHAR(32) NULL,               --参加检查人
  RECTIFY_ENT                BIGINT NOT NULL,                --整改单位ID(来源企业档案)
  RECTIFY_ENT_NAME           VARCHAR(64) NOT NULL,           --整改单位
  RISK_DESC                  VARCHAR(1024) NOT NULL,         --现场存在的问题
  IMPROVE_PERSON             VARCHAR(16) NULL,               --整改负责人
  IMPROVE_DATE               CHAR(10) NULL,                  --整改日期
  CHECK_PERSON               VARCHAR(16) NULL,               --检查负责人
  CHECK_DATE                 CHAR(10) NULL,                  --检查日期
  REVIEW_OPINION             VARCHAR(1024) NULL,             --复查意见
  REVIEW_PERSON              VARCHAR(16) NULL,               --复查负责人
  REVIEW_DATE                CHAR(10) NULL,                  --复查日期
  STATUS                     CHAR(1) NOT NULL,               --状态(表码 0:未结案,1:已结案<根据事故报告>)
  DEL_FLAG                   CHAR(1) NOT NULL                --删除标识(表码 0:删除,1:正常)
);
--整改反馈
CREATE TABLE T_RISK_REPORT
(
  RISK_REPORT_ID             BIGINT IDENTITY PRIMARY KEY,
  RISK_ID                    BIGINT NOT NULL,
  REPORT_SERIAL              VARCHAR(24) NOT NULL,           --反馈编号(企业简码+FK+年月日+2位流水号)
  CHECK_POSITION             VARCHAR(64) NULL,               --检查部位(由用户手动输入)
  IMPROVE_PERSON             VARCHAR(16) NULL,               --整改负责人
  COMPLETE_DATE              CHAR(10) NULL,                  --完成时间
  IMPROVE_DESC               VARCHAR(1024) NULL,             --整改结果说明(为文本框,字数要求500字以上)
  IMPROVE_RESULT             CHAR(1) NULL,                   --整改结果(表码 0:整改不可行,1:整改可行)
  REMARK                     VARCHAR(1024) NULL,             --其他需要说明的问题(为文本框,字数要求500字以上,可选填)
  DEL_FLAG                   CHAR(1) NOT NULL                --删除标识(表码 0:删除,1:正常)
);
--事故登记
CREATE TABLE T_ACCIDENT
(
  ACCIDENT_ID                BIGINT IDENTITY PRIMARY KEY, 
  ACCIDENT_SERIAL            VARCHAR(24) NOT NULL,           --事故编号(企业简码+SG+年月日+2位流水号)
  ACCIDENT_DATE              CHAR(10) NOT NULL,              --事故发生时间
  EQUIP_ID                   BIGINT NOT NULL,                --事故设备(来源设备档案)
  EQUIP_CATEGORY             VARCHAR(12) NOT NULL,           --设备类别(表码 BM_REPERTORY_CATEGORY)
  EQUIP_GENERIC              VARCHAR(6) NOT NULL,            --设备名称(表码 BM_EQUIP_GENERIC)
  EQUIP_SPECIFIC             VARCHAR(6) NOT NULL,            --规格型号(表码 BM_EQUIP_SPECIFIC)
  RECORD_ID                  VARCHAR(24) NULL,               --备案编号
  EXW_SERIAL                 VARCHAR(24) NULL,               --出厂编号
  RESPONSIBLE_UNIT           VARCHAR(64) NULL,               --事故责任单位 
  PROJECT_ID                 BIGINT NOT NULL,                --项目ID(来源项目信息)
  PROJECT_NAME               VARCHAR(64) NOT NULL,           --项目名称
  ADDRESS                    VARCHAR(256) NOT NULL,          --项目地址
  ACCIDENT_CATEGORY          VARCHAR(64) NOT NULL,           --事故类别
  ACCIDENT_LEVEL             VARCHAR(6) NOT NULL,            --事故级别(表码 ACCIDENT_LEVEL 0:一般事故,1:较大事故,2:重大事故,3:特别重大事故)
  INJURIES                   INT NOT NULL DEFAULT 0,         --受伤人数
  DEATHS                     INT NOT NULL DEFAULT 0,         --死亡人数
  RESPONSIBLE                VARCHAR(16) NOT NULL,           --责任人
  ECONOMIC_LOSSES            VARCHAR(64) NULL,               --经济损失
  ACCIDENT_DESC              VARCHAR(1024) NULL,             --事故概况
  ACCIDENT_REASON            VARCHAR(1024) NULL,             --事故原因
  ACCIDENT_RESULT            VARCHAR(1024) NULL,             --事故处理结果
  EQUIP_REPAIR_DESC          VARCHAR(1024) NULL,             --设备修复情况
  STATUS                     CHAR(1) NOT NULL,               --状态(已结案:根据事故报告、未结案)
  DEL_FLAG                   CHAR(1) NOT NULL                --删除标识(表码 0:删除,1:正常)
);
--事故报告
CREATE TABLE T_ACCIDENT_REPORT
(
  ACCIDENT_REPORT_ID         BIGINT IDENTITY PRIMARY KEY,
  ACCIDENT_ID                BIGINT NOT NULL,                --事故登记
  REPORT_SERIAL              VARCHAR(24) NOT NULL,           --报告编号（企业简码+BG+年月日+2位流水号）
  PROVIDED_DATE              CHAR(10) NOT NULL,              --填报时间
  PROVIDED_UNIT              VARCHAR(64) NOT NULL,           --填报单位 
  PREVENT                    VARCHAR(1024) NULL,             --预防措施
  PARTICIPANTS               VARCHAR(1024) NULL,             --参加事故分析人员
  STATUS                     CHAR(1) NOT NULL,               --状态(已结案:根据事故报告、未结案)
  DEL_FLAG                   CHAR(1) NOT NULL                --删除标识(表码 0:删除,1:正常)
);
--事件类型
CREATE TABLE BM_INCIDENT_TYPE
(
  CODE  VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE VARCHAR(64) NOT NULL
);
--工作备忘录
CREATE TABLE T_MEMO
(
  MEMO_ID                    BIGINT IDENTITY PRIMARY KEY,
  MEMO_SERIAL                VARCHAR(24) NOT NULL,           --事件编号
  MEMO_THEME                 VARCHAR(96) NOT NULL,           --事件主题
  PRACTI_ID                  BIGINT NOT NULL,                --经办人员(来源企业人员档案)
  PRACTI_NAME                VARCHAR(64) NOT NULL,           --经办人员姓名
  INCIDENT_TYPE              VARCHAR(6) NULL,                --事件类型(表码表 BM_INCIDENT_TYPE)
  PROJECT_ID                 BIGINT NULL,                    --项目ID(项目档案)
  PROJECT_NAME               VARCHAR(64) NULL,               --项目名称
  ADDRESS                    VARCHAR(256) NULL,              --项目所属地(省+市+区+街道)
  EQUIP_ID                   BIGINT NULL,                    --关联设备(来源设备档案)
  RECORD_ID                  VARCHAR(24) NULL,               --备案编号
  EXW_SERIAL                 VARCHAR(24)  NULL,              --出厂编号
  CUSTOM_ID                  BIGINT NULL,                    --关联客户(客户档案)
  CUSTOM_NAME                VARCHAR(64) NULL,               --关联客户
  STATUS                     CHAR(1) NOT NULL,               --状态(表码 0:未归档,1:已归档)
  REMARK                     VARCHAR(512) NULL               --备注
);
--工作备忘录工作代理人(可填写多个,来源于员工档案)
CREATE TABLE T_MEMO_DEPUTY
(
  MEMO_DEPUTY_ID             BIGINT IDENTITY PRIMARY KEY,
  MEMO_ID                    BIGINT NOT NULL,                --备忘录ID
  PRACTI_ID                  BIGINT NOT NULL                 --人员档案ID
);
--工作备忘录明细
CREATE TABLE T_MEMO_DETAIL
(
  MEMO_DETAIL_ID             BIGINT IDENTITY PRIMARY KEY,
  MEMO_ID                    BIGINT NOT NULL,                --事件编号
  DEALWITH_DATE              CHAR(10) NOT NULL,              --办理日期(默认为当前时间)
  PLAN_FINISHED_DATE         CHAR(10) NOT NULL,              --计划完成时间
  CONTENTS                   VARCHAR(024) NULL,              --办理内容
  FINISHED                   CHAR(1) NOT NULL,               --完成情况（表码值 0:未完成,1:完成)
  REMARK                     VARCHAR(512) NULL               --备注
);
INSERT INTO INIT_LOAD_TABLE VALUES('incidentType', 'BM_INCIDENT_TYPE', 1, 1, 1, 'CODE', 'VALUE', 1, NULL, NULL, NULL, '事件类型');
--2014-04-22
ALTER TABLE T_ACCIDENT ALTER COLUMN ACCIDENT_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_ACCIDENT ALTER COLUMN EXW_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_ACCIDENT_REPORT ALTER COLUMN REPORT_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_AMOUNT_EQUIP_SHARE ALTER COLUMN RELATE_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_AMOUNT_EQUIP_SHARE ALTER COLUMN RECORD_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_AMOUNT_EQUIP_SHARE ALTER COLUMN EXW_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_AMOUNT_PAYMENT ALTER COLUMN AMOUNT_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_AMOUNT_PAYMENT ALTER COLUMN RELATE_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_AMOUNT_PAYMENT ALTER COLUMN PROJECT_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_AMOUNT_PAYMENT_SHARE ALTER COLUMN RELATE_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_AMOUNT_RECEIVE ALTER COLUMN AMOUNT_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_AMOUNT_RECEIVE ALTER COLUMN RELATE_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_AMOUNT_RECEIVE ALTER COLUMN PROJECT_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_AMOUNT_RECEIVE_SHARE ALTER COLUMN RELATE_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_BORROW ALTER COLUMN BORROW_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_BORROW_COMPONENT ALTER COLUMN COMPON_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_BORROW_EQUIP ALTER COLUMN RECORD_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_COMPONENT ALTER COLUMN COMPON_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_COMPONENT_DIARY ALTER COLUMN COMPON_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_COMPONENT_DIARY ALTER COLUMN RELATE_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_COMPONENT_DIARY ALTER COLUMN PROJECT_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_CONTINGENCY_PLAN ALTER COLUMN CONTINGENCY_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_CONTINGENCY_PLAN ALTER COLUMN EXW_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_CONTRACT_EQUIP ALTER COLUMN RECORD_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_CONTRACT_EQUIP ALTER COLUMN EXW_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_CONTRACT_LEASE ALTER COLUMN CONTRACT_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_CONTRACT_LEASE ALTER COLUMN PROJECT_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_CONTRACT_LEASE ALTER COLUMN ENTERPRISE_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_DEDUCT ALTER COLUMN DEDUCT_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_DEDUCT ALTER COLUMN CONTRACT_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_DISPATCH ALTER COLUMN DISPATCH_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_DISPATCH ALTER COLUMN RELATE_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_DISPATCH ALTER COLUMN PROJECT_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_EQUIPMENT ALTER COLUMN RECORD_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_EQUIPMENT ALTER COLUMN EXW_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_EQUIPMENT_ACTIVATE ALTER COLUMN ACTIVATE_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_EQUIPMENT_ACTIVATE ALTER COLUMN INSTALL_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_EQUIPMENT_ACTIVATE ALTER COLUMN RECORD_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_EQUIPMENT_ACTIVATE ALTER COLUMN EXW_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_EQUIPMENT_ACTIVATE ALTER COLUMN PROJECT_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_EQUIPMENT_DETECT ALTER COLUMN DETECT_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_EQUIPMENT_DETECT ALTER COLUMN RELATE_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_EQUIPMENT_DETECT ALTER COLUMN RECORD_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_EQUIPMENT_DETECT ALTER COLUMN EXW_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_EQUIPMENT_DETECT ALTER COLUMN PROJECT_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_EQUIPMENT_DIARY ALTER COLUMN RECORD_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_EQUIPMENT_DIARY ALTER COLUMN EXW_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_EQUIPMENT_DIARY ALTER COLUMN RELATE_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_EQUIPMENT_DIARY ALTER COLUMN PROJECT_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_EQUIPMENT_DISMANTLE ALTER COLUMN DISMANTLE_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_EQUIPMENT_DISMANTLE ALTER COLUMN RELATE_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_EQUIPMENT_DISMANTLE ALTER COLUMN DISPATCH_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_EQUIPMENT_DISMANTLE ALTER COLUMN RECORD_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_EQUIPMENT_DISMANTLE ALTER COLUMN EXW_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_EQUIPMENT_DISMANTLE ALTER COLUMN PROJECT_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_EQUIPMENT_EMPLOY ALTER COLUMN EMPLOY_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_EQUIPMENT_EMPLOY ALTER COLUMN INSTALL_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_EQUIPMENT_EMPLOY ALTER COLUMN DISPATCH_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_EQUIPMENT_EMPLOY ALTER COLUMN RECORD_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_EQUIPMENT_EMPLOY ALTER COLUMN EXW_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_EQUIPMENT_EMPLOY ALTER COLUMN PROJECT_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_EQUIPMENT_FLOW ALTER COLUMN FLOW_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_EQUIPMENT_INSPECT ALTER COLUMN INSPECT_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_EQUIPMENT_INSPECT ALTER COLUMN RELATE_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_EQUIPMENT_INSPECT ALTER COLUMN RECORD_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_EQUIPMENT_INSPECT ALTER COLUMN EXW_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_EQUIPMENT_INSPECT ALTER COLUMN PROJECT_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_EQUIPMENT_INSTALL ALTER COLUMN INSTALL_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_EQUIPMENT_INSTALL ALTER COLUMN CONTRACT_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_EQUIPMENT_INSTALL ALTER COLUMN DISPATCH_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_EQUIPMENT_INSTALL ALTER COLUMN RECORD_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_EQUIPMENT_INSTALL ALTER COLUMN EXW_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_EQUIPMENT_INSTALL ALTER COLUMN PROJECT_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_EQUIPMENT_MAINT ALTER COLUMN MAINT_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_EQUIPMENT_MAINT ALTER COLUMN RELATE_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_EQUIPMENT_MAINT ALTER COLUMN RECORD_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_EQUIPMENT_MAINT ALTER COLUMN EXW_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_EQUIPMENT_MAINT ALTER COLUMN PROJECT_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_EQUIPMENT_VERIFY ALTER COLUMN VERIFY_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_EQUIPMENT_VERIFY ALTER COLUMN RELATE_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_EQUIPMENT_VERIFY ALTER COLUMN RECORD_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_EQUIPMENT_VERIFY ALTER COLUMN EXW_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_EQUIPMENT_VERIFY ALTER COLUMN PROJECT_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_INDIS_BASECHECK ALTER COLUMN BASECHECK_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_INDIS_BASECHECK ALTER COLUMN EXW_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_INDIS_PRECHECK ALTER COLUMN PRECHECK_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_INDIS_PRECHECK ALTER COLUMN EXW_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_INDIS_PROTOCOL ALTER COLUMN PROTOCOL_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_INDIS_PROTOCOL_EQUIP ALTER COLUMN EXW_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_INDIS_SCHEME ALTER COLUMN SCHEME_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_INDIS_SCHEME ALTER COLUMN EXW_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_INSTALMENT ALTER COLUMN RELATE_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_INSURE_CLAIM ALTER COLUMN INSURE_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_INSURE_EQUIPMENT ALTER COLUMN INSURE_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_INSURE_EQUIPMENT ALTER COLUMN RECORD_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_INSURE_EQUIPMENT ALTER COLUMN EXW_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_INVENTORY ALTER COLUMN INVENTORY_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_INVOICE_COLLECT ALTER COLUMN INVOICE_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_INVOICE_COLLECT ALTER COLUMN RELATE_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_INVOICE_ISSUE ALTER COLUMN INVOICE_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_INVOICE_ISSUE ALTER COLUMN RELATE_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_MEMO ALTER COLUMN MEMO_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_MEMO ALTER COLUMN EXW_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_MONEY_BACK ALTER COLUMN BACK_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_MONEY_BACK ALTER COLUMN LEND_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_MONEY_LEND ALTER COLUMN LEND_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_PICKUP ALTER COLUMN PICKUP_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_PICKUP ALTER COLUMN RELATE_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_PICKUP_COMPONENT ALTER COLUMN COMPON_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_PRACTI_DIARY ALTER COLUMN RELATE_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_PRACTI_DIARY ALTER COLUMN PROJECT_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_PROJECT ALTER COLUMN PROJECT_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_PURCHASE ALTER COLUMN PURCHASE_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_PURCHASE ALTER COLUMN RELATE_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_PURCHASE ALTER COLUMN RECORD_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_RECEIVEMENT ALTER COLUMN RELATE_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_REIMBURSE ALTER COLUMN REIMBURSE_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_REIMBURSE ALTER COLUMN RELATE_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_REIMBURSE ALTER COLUMN RECORD_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_REIMBURSE ALTER COLUMN PROJECT_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_RISK ALTER COLUMN RISK_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_RISK ALTER COLUMN EXW_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_RISK_REPORT ALTER COLUMN REPORT_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_SALARY ALTER COLUMN SALARY_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_SECURE_PROTOCOL ALTER COLUMN PROTOCOL_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_SETTLE_COMPON_BRIEF ALTER COLUMN COMPON_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_SETTLE_CONTRACT ALTER COLUMN SETTLE_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_SETTLE_CONTRACT ALTER COLUMN CONTRACT_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_SETTLE_CONTRACT ALTER COLUMN PROJECT_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_SETTLE_EQUIP_BRIEF ALTER COLUMN RECORD_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_SETTLE_EQUIP_BRIEF ALTER COLUMN EXW_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_STORE_HOUSE ALTER COLUMN STORE_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_STORE_STOCK ALTER COLUMN RECORD_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_STORE_STOCK ALTER COLUMN EXW_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_TECHNICAL_DISCLOSURE ALTER COLUMN DISCLOSURE_SERIAL VARCHAR(64) NOT NULL;
--物流运输
CREATE TABLE T_LOGISTICS_TRANSPORT
(
  TRANSPORT_ID               BIGINT IDENTITY PRIMARY KEY,
  TRANSPORT_SERIAL           VARCHAR(64) NOT NULL,           --物流单号
  TRANSPORT_THEME            VARCHAR(96) NOT NULL,           --物流运输主题
  PROJECT_ID                 BIGINT NOT NULL,                --项目ID(项目档案)
  PROJECT_NAME               VARCHAR(64) NOT NULL,           --项目名称
  ADDRESS                    VARCHAR(256) NOT NULL,          --收货地址(默认为项目地址,仍可修改)
  DELIVERY_MAN               VARCHAR(64) NOT NULL,           --发货人(默认为登陆用户的姓名,仍可修改)
  DELIVERY_DATE              CHAR(10) NOT NULL,              --发货时间
  EXPECTED_ARRIVE_DATE       CHAR(10) NOT NULL,              --预计到达时间
  SIGN_MAN                   VARCHAR(64) NULL,               --签收人
  SIGN_DATE                  CHAR(10) NULL,                  --签收时间
  SIGN_RESULT                VARCHAR(512) NULL,              --签收结果
  BATCH_NUMBER               VARCHAR(32) NULL,               --批次号
  TRANSPORT_AMOUNT           NUMERIC(12, 2) NOT NULL,        --运输费
  DELIVERY_PHONE             VARCHAR(16) NULL,               --发货人联系电话(默认为登陆用户的手机号,仍可修改)
  RECEIVE_MAN                VARCHAR(64) NULL,               --接货人
  RECEIVE_PHONE              VARCHAR(16) NULL,               --接货人联系电话
  MATERIAL_PARK              VARCHAR(256) NULL,              --停放地
  REMARK                     VARCHAR(512) NULL,              --备注
  STATUS                     CHAR(1) NOT NULL,               --状态(表码值 0:发货中-保存后未签收的状态,1:已签收-点了已签收的物流单)
  FUND_STATUS                CHAR(1) NOT NULL,               --款项状态(表码值 0:未付款-初始,2:已付款-付款管理中有关联这条运输数据,且审批通过)
  DEL_FLAG                   CHAR(1) NOT NULL                --删除标识(表码 0:删除,1:正常)
);
--物流运输清单
CREATE TABLE T_LOGISTICS_TRANDETAIL
(
  TRANDETAIL_ID              BIGINT IDENTITY PRIMARY KEY,
  TRANSPORT_ID               BIGINT NOT NULL,                --物流运输ID
  DISPATCH_ID                BIGINT NOT NULL,                --调度信息(只能显示该项目下的调度单)
  DISPATCH_SERIAL            VARCHAR(64) NOT NULL,           --调度单号
  DISPATCH_THEME             VARCHAR(96) NOT NULL,           --调度主题
  CAR_ID                     BIGINT NULL,                    --运输车辆
  LICENSE_PLATE              VARCHAR(16) NOT NULL,           --车号(来源车辆档案,用户也可手动输入)
  DRIVER                     VARCHAR(64) NULL,               --司机(默认车辆档案中信息,仍可修改)
  DRIVER_PHONE               VARCHAR(16) NULL,               --司机联系电话(同前面)
  COMPON_ID                  BIGINT NOT NULL,                --零配件(零配件档案)
  COMPON_CATEGORY            VARCHAR(12) NOT NULL,           --零配件类别(表码 BM_REPERTORY_CATEGORY)
  COMPON_GENERIC             VARCHAR(6) NOT NULL,            --零配件名称(表码 BM_COMPONENT_GENERIC)
  COMPON_SPECIFIC            VARCHAR(6) NOT NULL,            --规格型号(表码 BM_COMPONENT_SPECIFIC)
  COUNTS                     SMALLINT NOT NULL,              --运输数量
  CALCULATE                  VARCHAR(8) NOT NULL,            --计量单位
  REMARK                     VARCHAR(512) NULL               --备注
);
--检测项目类型(内置) vitemType
CREATE TABLE BM_VITEM_TYPE
(
  CODE  VARCHAR(4) NOT NULL PRIMARY KEY,
  VALUE VARCHAR(64) NOT NULL
);
INSERT BM_VITEM_TYPE(CODE, VALUE) VALUES (N'SIS', N'塔吊安装自检');
INSERT BM_VITEM_TYPE(CODE, VALUE) VALUES (N'TIS', N'升降机安装自检');
INSERT BM_VITEM_TYPE(CODE, VALUE) VALUES (N'EV', N'验收管理');
INSERT BM_VITEM_TYPE(CODE, VALUE) VALUES (N'DM', N'例行保养');
INSERT BM_VITEM_TYPE(CODE, VALUE) VALUES (N'JM', N'初级保养');
INSERT BM_VITEM_TYPE(CODE, VALUE) VALUES (N'SM', N'高级保养');

--自检报告
CREATE TABLE T_VERIFY_SELF
(
  SELF_ID                    BIGINT IDENTITY PRIMARY KEY,
  SELF_SERIAL                VARCHAR(64) NOT NULL,           --自检编号(企业简码+ZJ+年月日+2位流水号)
  RELATE_ID                  BIGINT NOT NULL,                --关联业务ID
  RELATE_MODULE              VARCHAR(32) NOT NULL,           --关联业务类型
  PROJECT_ID                 BIGINT NOT NULL,                --所属项目(项目档案)
  PROJECT_NAME               VARCHAR(64) NOT NULL,           --项目名称
  ADDRESS                    VARCHAR(256) NOT NULL,          --项目地址
  EQUIP_ID                   BIGINT NOT NULL,                --安装设备(设备档案)
  EQUIP_CATEGORY             VARCHAR(12) NOT NULL,           --设备类别(表码 BM_REPERTORY_CATEGORY)
  EQUIP_GENERIC              VARCHAR(6) NOT NULL,            --设备名称(表码 BM_EQUIP_GENERIC)
  EQUIP_SPECIFIC             VARCHAR(6) NOT NULL,            --规格型号(表码 BM_EQUIP_SPECIFIC)
  RECORD_ID                  VARCHAR(24) NULL,               --备案编号
  EQUIP_VENDER               VARCHAR(48) NULL,               --制造厂家
  EXW_SERIAL                 VARCHAR(24) NULL,               --出厂编号
  EXW_DATE                   CHAR(10) NULL,                  --出厂日期
  IN_ENT                     BIGINT NOT NULL,                --安装单位(企业档案)
  IN_ENT_NAME                VARCHAR(64) NOT NULL,           --安装单位名称
  IN_ENT_CERT_NUM            VARCHAR(24) NULL,               --安装单位资质证书编号
  IN_ENT_CERT_TYPE           VARCHAR(64) NULL,               --安装单位资质类型
  HEIGHT                     VARCHAR(8) NULL,                --安装高度
  MAX_HEIGHT                 VARCHAR(8) NULL,                --检查高度(可选填)
  INSTALL_MANAGER_ID         BIGINT NULL,                    --安装负责人(来源员工档案)
  INSTALL_MANAGER            VARCHAR(32) NULL,               --安装负责人
  SELF_VERIFY_MAN            VARCHAR(32) NULL,               --检查人(可选填)
  USER_ID                    BIGINT NOT NULL,                --填报用户ID
  USER_NAME                  VARCHAR(64) NOT NULL,           --填报用户姓名
  DEP_ID                     BIGINT NOT NULL,                --填报所属部门
  PROVIDED_DATE              CHAR(10) NOT NULL,              --填报日期
  REMARK                     VARCHAR(512) NULL,              --备注
  VERIFY_TYPE                CHAR(1) NULL,                   --检测类型(表码 T:塔式类型,S:升降机类型)
  DEL_FLAG                   CHAR(1) NOT NULL                --删除标识(表码 0:删除,1:正常)
);
ALTER TABLE T_EQUIPMENT_INSTALL ADD VERIFY_TYPE CHAR(1) NULL;
SELECT * FROM T_EQUIPMENT_INSTALL SET VERIFY_TYPE = EQUIP_GENERIC;

ALTER TABLE T_COMPONENT ADD EQUIP_ID BIGINT NULL;
DROP TABLE T_EQUIP_COMPON;

ALTER TABLE T_EQUIPMENT_DIARY ADD FLOW_ID BIGINT NULL;
UPDATE ED SET ED.FLOW_ID = EF.FLOW_ID FROM T_EQUIPMENT_DIARY ED, T_EQUIPMENT_FLOW EF WHERE ED.EQUIP_DIARY_ID = EF.EQUIP_DIARY_ID;
ALTER TABLE T_EQUIPMENT_DIARY ADD STATUS CHAR(1) NOT NULL DEFAULT '1';

ALTER TABLE T_COMPONENT_DIARY ADD FLOW_ID BIGINT NULL;
UPDATE CD SET CD.FLOW_ID = EF.FLOW_ID FROM T_COMPONENT_DIARY CD, T_EQUIPMENT_FLOW EF WHERE CD.RELATE_ID = EF.INSTALL_ID AND CD.RELATE_MODULE = 'EQUIP_INSTALL';
UPDATE CD SET CD.FLOW_ID = EF.FLOW_ID FROM T_COMPONENT_DIARY CD, T_EQUIPMENT_FLOW EF WHERE CD.RELATE_ID = EF.EMPLOY_ID AND CD.RELATE_MODULE = 'EQUIP_EMPLOY';
UPDATE CD SET CD.FLOW_ID = EF.FLOW_ID FROM T_COMPONENT_DIARY CD, T_EQUIPMENT_FLOW EF WHERE CD.RELATE_ID = EF.DISMANTLE_ID AND CD.RELATE_MODULE = 'EQUIP_DISMANTLE';
ALTER TABLE T_COMPONENT_DIARY ADD ACCEPT_COUNTS SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE T_COMPONENT_DIARY ADD CALCULATE VARCHAR(8) NOT NULL DEFAULT '件';
ALTER TABLE T_COMPONENT_DIARY ADD STATUS CHAR(1) NOT NULL DEFAULT '1';
--2014-05-21
ALTER TABLE T_EQUIPMENT ADD BUSINESS_STATUS CHAR(1) NOT NULL DEFAULT '0';
--2014-05-22
ALTER TABLE T_EQUIPMENT_INSTALL ADD MANAGER_TEL VARCHAR(16) NULL;
ALTER TABLE T_EQUIPMENT_INSTALL ADD KNOT_COUNTS SMALLINT NULL;
ALTER TABLE T_EQUIPMENT_INSTALL ADD WALL_ATTACHE_QTY SMALLINT NULL;

ALTER TABLE T_EQUIPMENT_EMPLOY ADD MANAGER_TEL VARCHAR(16) NULL;
ALTER TABLE T_EQUIPMENT_EMPLOY ADD INSTALL_HEIGHT VARCHAR(8) NULL;
ALTER TABLE T_EQUIPMENT_EMPLOY ADD KNOT_COUNTS SMALLINT NULL;
ALTER TABLE T_EQUIPMENT_EMPLOY ADD WALL_ATTACHE_QTY SMALLINT NULL;

ALTER TABLE T_INSURE_EQUIPMENT ADD PROJECT_ID BIGINT NULL;

ALTER TABLE T_PICKUP_COMPONENT ADD RETURN_STORE_ID BIGINT NULL;
ALTER TABLE T_PICKUP_COMPONENT ADD RETURN_STORE_NAME VARCHAR(64) NULL;

ALTER TABLE T_BORROW_COMPONENT ADD RETURN_STORE_ID BIGINT NULL;
ALTER TABLE T_BORROW_COMPONENT ADD RETURN_STORE_NAME VARCHAR(64) NULL;
ALTER TABLE T_BORROW_EQUIP ADD RETURN_STORE_ID BIGINT NULL;
ALTER TABLE T_BORROW_EQUIP ADD RETURN_STORE_NAME VARCHAR(64) NULL;
--2014-05-23
ALTER TABLE T_AMOUNT_RECEIVE ALTER COLUMN VOUCHER VARCHAR(32) NULL;
ALTER TABLE T_EQUIPMENT_DIARY ADD BUILDING_NUM VARCHAR(64) NULL;
ALTER TABLE T_SETTLE_EQUIP_BRIEF ADD BUILDING_NUM VARCHAR(64) NULL;
--2014-05-25
ALTER TABLE T_SECURE_PROTOCOL ADD CONTRACT_ID BIGINT NOT NULL DEFAULT 1;
ALTER TABLE T_INDIS_PROTOCOL ADD CONTRACT_ID BIGINT NOT NULL DEFAULT 1;
ALTER TABLE T_INDIS_SCHEMA ADD CONTRACT_ID BIGINT NOT NULL DEFAULT 1;
ALTER TABLE T_CONTINGENCY_PLAN ADD CONTRACT_ID BIGINT NOT NULL DEFAULT 1;
ALTER TABLE T_INDIS_PRECHECK ADD CONTRACT_ID BIGINT NOT NULL DEFAULT 1;
ALTER TABLE T_INDIS_BASECHECK ADD CONTRACT_ID BIGINT NOT NULL DEFAULT 1;
--2014-05-26
ALTER TABLE T_EQUIPMENT_INSTALL ADD BRACHIUM NUMERIC(12, 2) NULL;
--2014-05-31
ALTER TABLE T_EQUIPMENT_DIARY ADD PROVINCE CHAR(6) NULL;
ALTER TABLE T_EQUIPMENT_DIARY ADD CITY CHAR(6) NULL;
ALTER TABLE T_EQUIPMENT_DIARY ADD COUNTY CHAR(6) NULL;
ALTER TABLE T_EQUIPMENT_DIARY ADD STREET VARCHAR(128) NULL;
UPDATE ED SET ED.PROVINCE = P.PROVINCE, ED.CITY = P.CITY, ED.COUNTY = P.COUNTY, ED.STREET = P.STREET FROM T_EQUIPMENT_DIARY ED, T_PROJECT P WHERE ED.PROJECT_ID = P.PROJECT_ID;

ALTER TABLE T_TECHNICAL_DISCLOSURE ADD DISCLOSURE_ITEM VARCHAR(64) NULL;

ALTER TABLE T_RISK ALTER COLUMN RISK_DESC VARCHAR(4000) NOT NULL;
ALTER TABLE T_RISK ALTER COLUMN REVIEW_OPINION VARCHAR(4000) NULL;
ALTER TABLE T_RISK_REPORT ALTER COLUMN IMPROVE_DESC VARCHAR(4000) NULL;
ALTER TABLE T_RISK_REPORT ALTER COLUMN REMARK VARCHAR(4000) NULL;
--20140604
EXEC SP_RENAME 'T_LOGISTICS_TRANDETAIL.[COMPON_DIARY_ID]','DISPATCH_COMPON_ID','COLUMN';
UPDATE LT SET LT.DISPATCH_COMPON_ID = CD.RELATE_COMPON_ID FROM T_LOGISTICS_TRANDETAIL LT, T_COMPONENT_DIARY CD WHERE LT.DISPATCH_COMPON_ID = CD.COMPON_DIARY_ID;
ALTER TABLE T_LOGISTICS_TRANSPORT ADD PROJECT_SERIAL VARCHAR(64) NOT NULL DEFAULT '0';
UPDATE LT SET LT.PROJECT_SERIAL = P.PROJECT_SERIAL FROM T_LOGISTICS_TRANSPORT LT, T_PROJECT P WHERE LT.PROJECT_ID = P.PROJECT_ID;
--20140616
ALTER TABLE T_COMPONENT ALTER COLUMN RFID_CODE VARCHAR(64) NULL;
ALTER TABLE T_EQUIPMENT ALTER COLUMN RFID_CODE VARCHAR(64) NULL;

ALTER TABLE T_EQUIPMENT_DIARY ADD RFID_CODE VARCHAR(64) NULL;
ALTER TABLE T_COMPONENT_DIARY ADD RFID_CODE VARCHAR(64) NULL;
--2014-06-30
ALTER TABLE T_EQUIPMENT ADD MONITOR_SERIAL VARCHAR(32) NULL;
--2014-07-03
ALTER TABLE T_COMPONENT ADD DIMENSIONS VARCHAR(64) NULL;

ALTER TABLE T_COMPONENT ALTER COLUMN COMPON_SPECIFIC VARCHAR(6) NULL;
ALTER TABLE T_SETTLE_COMPON_BRIEF ALTER COLUMN COMPON_SPECIFIC_NAME VARCHAR(64) NULL;
ALTER TABLE T_COMPONENT_DIARY ALTER COLUMN COMPON_SPECIFIC VARCHAR(6) NULL;
ALTER TABLE T_PICKUP_COMPONENT ALTER COLUMN COMPON_SPECIFIC VARCHAR(6) NULL;
--2014-07-04
ALTER TABLE T_COMPONENT_DIARY ADD DIMENSIONS VARCHAR(64) NULL;
GO
ALTER TABLE T_LOGISTICS_TRANSPORT ADD PROJECT_SERIAL VARCHAR(64) NOT NULL DEFAULT '0';
GO
UPDATE LT SET LT.PROJECT_SERIAL = P.PROJECT_SERIAL FROM T_LOGISTICS_TRANSPORT LT, T_PROJECT P WHERE LT.PROJECT_ID = P.PROJECT_ID;
GO
ALTER TABLE T_EQUIPMENT_INSPECT_DETAIL ADD DETAIL_PEPOLES VARCHAR(256) NULL;
GO
--2014-07-11
DELETE FROM BM_RELATE_MODULE;
GO
INSERT INTO BM_RELATE_MODULE VALUES('CORP', '??????');
INSERT INTO BM_RELATE_MODULE VALUES('CUSTOMER', '??????');
INSERT INTO BM_RELATE_MODULE VALUES('EQUIP', '?豸???');
INSERT INTO BM_RELATE_MODULE VALUES('CONTRACT_LEASE', '??????');
INSERT INTO BM_RELATE_MODULE VALUES('SETTLE_CONTRACT', '???????');
INSERT INTO BM_RELATE_MODULE VALUES('DISPATCH', '???????');
INSERT INTO BM_RELATE_MODULE VALUES('PICKUP', '???????');
INSERT INTO BM_RELATE_MODULE VALUES('PURCHASE', '??????');
INSERT INTO BM_RELATE_MODULE VALUES('BORROW', '???????');
INSERT INTO BM_RELATE_MODULE VALUES('EQUIP_INSTALL', '???????');
INSERT INTO BM_RELATE_MODULE VALUES('EQUIP_EMPLOY', '??ù???');
INSERT INTO BM_RELATE_MODULE VALUES('EQUIP_DISMANTLE', '??ж????');
INSERT INTO BM_RELATE_MODULE VALUES('EQUIP_WAREHOUSE', '??????');
INSERT INTO BM_RELATE_MODULE VALUES('EQUIP_INSPECT', '??????');
INSERT INTO BM_RELATE_MODULE VALUES('EQUIP_MAINT', '???????');
INSERT INTO BM_RELATE_MODULE VALUES('EQUIP_HITCH', '???????');
GO
--2014-07-21
--?????λ faultLocation
CREATE TABLE BM_FAULT_LOCATION
(
  CODE  VARCHAR(6) NOT NULL PRIMARY KEY,
  VALUE VARCHAR(64) NOT NULL
);
INSERT INTO INIT_LOAD_TABLE VALUES('faultLocation', 'BM_FAULT_LOCATION', 1, 1, 1, 'CODE', 'VALUE', 0, NULL, NULL, NULL, '?????λ');
ALTER TABLE T_EQUIPMENT_REPAIR DROP COLUMN COMPON_ID;
ALTER TABLE T_EQUIPMENT_REPAIR ADD FAULT_LOCATION VARCHAR(6) NULL;
INSERT INTO BM_FAULT_LOCATION VALUES('0', '?????');

ALTER TABLE T_INSURE_EQUIPMENT ALTER COLUMN INSURE_PROGRAM VARCHAR(96) NULL;
ALTER TABLE T_COMPONENT ADD PARACHUTE_FLAG CHAR(1) NOT NULL DEFAULT '0';
ALTER TABLE T_COMPONENT ADD PARACHUTE_CHECK_DATE CHAR(10) NULL;
--2014-08-17
UPDATE C SET C.COMPON_SERIAL = LEFT(C.COMPON_SERIAL, 9) + '000' + RIGHT(C.COMPON_SERIAL, 3) FROM T_COMPONENT C;
UPDATE C SET C.COMPON_SERIAL = LEFT(C.COMPON_SERIAL, 9) + '000' + RIGHT(C.COMPON_SERIAL, 3) FROM T_SETTLE_COMPON_BRIEF C;
UPDATE C SET C.COMPON_SERIAL = LEFT(C.COMPON_SERIAL, 9) + '000' + RIGHT(C.COMPON_SERIAL, 3) FROM T_COMPONENT_DIARY C;
UPDATE C SET C.COMPON_SERIAL = LEFT(C.COMPON_SERIAL, 9) + '000' + RIGHT(C.COMPON_SERIAL, 3) FROM T_PICKUP_COMPONENT C;
UPDATE C SET C.COMPON_SERIAL = LEFT(C.COMPON_SERIAL, 9) + '000' + RIGHT(C.COMPON_SERIAL, 3) FROM T_BORROW_COMPONENT C;
--2014-10-02
ALTER TABLE T_EQUIPMENT_DIARY ADD BUSINESS_ID BIGINT NULL;
ALTER TABLE T_EQUIPMENT_DIARY ADD BUSINESS_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_EQUIPMENT_DIARY ADD BUSINESS_THEME VARCHAR(96) NULL;
ALTER TABLE T_EQUIPMENT_DIARY ADD BUSINESS_MODULE VARCHAR(32) NULL;
ALTER TABLE T_EQUIPMENT_DIARY ADD BUSINESS_EQUIP_ID BIGINT NULL;
ALTER TABLE T_EQUIPMENT_DIARY ALTER COLUMN RELATE_ID BIGINT NULL;
ALTER TABLE T_EQUIPMENT_DIARY ALTER COLUMN RELATE_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_EQUIPMENT_DIARY ALTER COLUMN RELATE_THEME VARCHAR(96) NULL;
ALTER TABLE T_EQUIPMENT_DIARY ALTER COLUMN RELATE_MODULE VARCHAR(32) NULL;
UPDATE ED SET ED.BUSINESS_ID = ED.RELATE_ID, ED.BUSINESS_SERIAL = ED.RELATE_SERIAL, ED.BUSINESS_THEME = ED.RELATE_THEME, ED.BUSINESS_MODULE = ED.RELATE_MODULE, ED.BUSINESS_EQUIP_ID = ED.RELATE_EQUIP_ID, ED.RELATE_ID = NULL, ED.RELATE_SERIAL = NULL, ED.RELATE_THEME = NULL, ED.RELATE_MODULE = NULL FROM T_EQUIPMENT_DIARY ED WHERE ED.RELATE_MODULE = 'DISPATCH';
UPDATE ED SET ED.BUSINESS_ID = ED.RELATE_ID, ED.BUSINESS_SERIAL = ED.RELATE_SERIAL, ED.BUSINESS_THEME = ED.RELATE_THEME, ED.BUSINESS_MODULE = ED.RELATE_MODULE, ED.BUSINESS_EQUIP_ID = ED.RELATE_EQUIP_ID, ED.RELATE_ID = NULL, ED.RELATE_SERIAL = NULL, ED.RELATE_THEME = NULL, ED.RELATE_MODULE = NULL FROM T_EQUIPMENT_DIARY ED WHERE ED.RELATE_MODULE = 'BORROW';
UPDATE ED SET ED.BUSINESS_ID = D.DISPATCH_ID, ED.BUSINESS_SERIAL = D.DISPATCH_SERIAL, ED.BUSINESS_THEME = D.DISPATCH_THEME, ED.BUSINESS_MODULE = 'DISPATCH', ED.BUSINESS_EQUIP_ID = ED.RELATE_EQUIP_ID FROM T_EQUIPMENT_DIARY ED, T_DISPATCH D WHERE ED.DISPATCH_ID = D.DISPATCH_ID;
ALTER TABLE T_EQUIPMENT_DIARY ALTER COLUMN BUSINESS_ID BIGINT NOT NULL;
ALTER TABLE T_EQUIPMENT_DIARY ALTER COLUMN BUSINESS_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_EQUIPMENT_DIARY ALTER COLUMN BUSINESS_THEME VARCHAR(96) NULL;
ALTER TABLE T_EQUIPMENT_DIARY ALTER COLUMN BUSINESS_MODULE VARCHAR(32) NOT NULL;
ALTER TABLE T_EQUIPMENT_DIARY ALTER COLUMN BUSINESS_EQUIP_ID BIGINT NOT NULL;
ALTER TABLE T_EQUIPMENT_DIARY DROP COLUMN DISPATCH_ID;
ALTER TABLE T_EQUIPMENT_DIARY DROP COLUMN RELATE_EQUIP_ID;

ALTER TABLE T_COMPONENT_DIARY ADD BUSINESS_ID BIGINT NULL;
ALTER TABLE T_COMPONENT_DIARY ADD BUSINESS_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_COMPONENT_DIARY ADD BUSINESS_THEME VARCHAR(96) NULL;
ALTER TABLE T_COMPONENT_DIARY ADD BUSINESS_MODULE VARCHAR(32) NULL;
ALTER TABLE T_COMPONENT_DIARY ADD BUSINESS_COMPON_ID BIGINT NULL;
ALTER TABLE T_COMPONENT_DIARY ALTER COLUMN RELATE_ID BIGINT NULL;
ALTER TABLE T_COMPONENT_DIARY ALTER COLUMN RELATE_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_COMPONENT_DIARY ALTER COLUMN RELATE_THEME VARCHAR(96) NULL;
ALTER TABLE T_COMPONENT_DIARY ALTER COLUMN RELATE_MODULE VARCHAR(32) NULL;
UPDATE CD SET CD.BUSINESS_ID = CD.RELATE_ID, CD.BUSINESS_SERIAL = CD.RELATE_SERIAL, CD.BUSINESS_THEME = CD.RELATE_THEME, CD.BUSINESS_MODULE = CD.RELATE_MODULE, CD.BUSINESS_COMPON_ID = CD.RELATE_COMPON_ID, CD.RELATE_ID = NULL, CD.RELATE_SERIAL = NULL, CD.RELATE_THEME = NULL, CD.RELATE_MODULE = NULL FROM T_COMPONENT_DIARY CD WHERE CD.RELATE_MODULE = 'BORROW';
UPDATE CD SET CD.BUSINESS_ID = CD.RELATE_ID, CD.BUSINESS_SERIAL = CD.RELATE_SERIAL, CD.BUSINESS_THEME = CD.RELATE_THEME, CD.BUSINESS_MODULE = CD.RELATE_MODULE, CD.BUSINESS_COMPON_ID = CD.RELATE_COMPON_ID, CD.RELATE_ID = NULL, CD.RELATE_SERIAL = NULL, CD.RELATE_THEME = NULL, CD.RELATE_MODULE = NULL FROM T_COMPONENT_DIARY CD WHERE CD.RELATE_MODULE = 'PICKUP';
UPDATE CD SET CD.BUSINESS_ID = D.DISPATCH_ID, CD.BUSINESS_SERIAL = D.DISPATCH_SERIAL, CD.BUSINESS_THEME = D.DISPATCH_THEME, CD.BUSINESS_MODULE = 'DISPATCH', CD.BUSINESS_COMPON_ID = CD.RELATE_COMPON_ID FROM T_COMPONENT_DIARY CD, T_DISPATCH D WHERE CD.DISPATCH_ID = D.DISPATCH_ID;
ALTER TABLE T_COMPONENT_DIARY ALTER COLUMN BUSINESS_ID BIGINT NOT NULL;
ALTER TABLE T_COMPONENT_DIARY ALTER COLUMN BUSINESS_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_COMPONENT_DIARY ALTER COLUMN BUSINESS_THEME VARCHAR(96) NULL;
ALTER TABLE T_COMPONENT_DIARY ALTER COLUMN BUSINESS_MODULE VARCHAR(32) NOT NULL;
ALTER TABLE T_COMPONENT_DIARY ALTER COLUMN BUSINESS_COMPON_ID BIGINT NOT NULL;
ALTER TABLE T_COMPONENT_DIARY DROP COLUMN DISPATCH_ID;
ALTER TABLE T_COMPONENT_DIARY DROP COLUMN RELATE_COMPON_ID;

ALTER TABLE T_PRACTI_DIARY ADD FLOW_ID BIGINT NULL;
ALTER TABLE T_PRACTI_DIARY ADD BUSINESS_ID BIGINT NULL;
ALTER TABLE T_PRACTI_DIARY ADD BUSINESS_SERIAL VARCHAR(64) NULL;
ALTER TABLE T_PRACTI_DIARY ADD BUSINESS_THEME VARCHAR(96) NULL;
ALTER TABLE T_PRACTI_DIARY ADD BUSINESS_MODULE VARCHAR(32) NULL;
ALTER TABLE T_PRACTI_DIARY ADD BUSINESS_PRACTI_ID BIGINT NULL;
UPDATE PD SET PD.BUSINESS_ID = D.DISPATCH_ID, PD.BUSINESS_SERIAL = D.DISPATCH_SERIAL, PD.BUSINESS_THEME = D.DISPATCH_THEME, PD.BUSINESS_MODULE = 'DISPATCH', PD.BUSINESS_PRACTI_ID = PD.RELATE_PRACTI_ID FROM T_PRACTI_DIARY PD, T_DISPATCH D WHERE PD.DISPATCH_ID = D.DISPATCH_ID;
UPDATE PD SET PD.FLOW_ID = CD.FLOW_ID FROM  T_PRACTI_DIARY PD, T_COMPONENT_DIARY CD WHERE PD.RELATE_ID = CD.RELATE_ID AND PD.RELATE_MODULE = CD.RELATE_MODULE;
ALTER TABLE T_PRACTI_DIARY ALTER COLUMN BUSINESS_ID BIGINT NOT NULL;
ALTER TABLE T_PRACTI_DIARY ALTER COLUMN BUSINESS_SERIAL VARCHAR(64) NOT NULL;
ALTER TABLE T_PRACTI_DIARY ALTER COLUMN BUSINESS_THEME VARCHAR(96) NULL;
ALTER TABLE T_PRACTI_DIARY ALTER COLUMN BUSINESS_MODULE VARCHAR(32) NOT NULL;
ALTER TABLE T_PRACTI_DIARY ALTER COLUMN BUSINESS_PRACTI_ID BIGINT NOT NULL;
ALTER TABLE T_PRACTI_DIARY DROP COLUMN DISPATCH_ID;
ALTER TABLE T_PRACTI_DIARY DROP COLUMN RELATE_PRACTI_ID;

ALTER TABLE T_EQUIPMENT_INSTALL ALTER COLUMN INSTALL_HEIGHT NUMERIC(12, 2) NULL;
ALTER TABLE T_SUPPLIER ADD SUPPLIER_LINKER_ID BIGINT NULL;
ALTER TABLE T_SUPPLIER ADD SUPPLIER_ACCOUNT_ID BIGINT NULL;
ALTER TABLE T_SUPPLIER_LINKER ALTER COLUMN SUPPLIER_ID BIGINT NULL;
ALTER TABLE T_SUPPLIER_ACCOUNT ALTER COLUMN SUPPLIER_ID BIGINT NULL;

ALTER TABLE T_CUSTOMER ADD CUSTOMER_LINKER_ID BIGINT NULL;
ALTER TABLE T_CUSTOMER ADD CUSTOMER_ACCOUNT_ID BIGINT NULL;
ALTER TABLE T_CUSTOMER_LINKER ALTER COLUMN CUSTOMER_ID BIGINT NULL;
ALTER TABLE T_CUSTOMER_ACCOUNT ALTER COLUMN CUSTOMER_ID BIGINT NULL;

--物流回场
CREATE TABLE T_LOGISTICS_BACKSPORT
(
  BACKSPORT_ID               BIGINT IDENTITY PRIMARY KEY,
  BACKSPORT_SERIAL           VARCHAR(64) NOT NULL,           --物流单号
  BACKSPORT_THEME            VARCHAR(96) NOT NULL,           --物流运输主题
  BATCH_NUMBER               VARCHAR(32) NULL,               --批次号
  DELIVERY_DATE              CHAR(10) NOT NULL,              --发货时间
  EXPECTED_ARRIVE_DATE       CHAR(10) NOT NULL,              --预计到达时间
  DELIVERY_MAN               VARCHAR(64) NOT NULL,           --发货人(默认为登陆用户的姓名,仍可修改)
  DELIVERY_PHONE             VARCHAR(16) NULL,               --发货人联系电话(默认为登陆用户的手机号,仍可修改)
  RECEIVE_MAN                VARCHAR(64) NULL,               --接货人
  RECEIVE_PHONE              VARCHAR(16) NULL,               --接货人联系电话
  MATERIAL_PARK              VARCHAR(256) NULL,              --停放地
  BACKSPORT_AMOUNT           NUMERIC(12, 2) NOT NULL,        --运输费
  PROJECT_ID                 BIGINT NOT NULL,                --项目ID(项目档案)
  PROJECT_SERIAL             VARCHAR(64) NOT NULL,           --项目编号
  PROJECT_NAME               VARCHAR(64) NOT NULL,           --项目名称
  ADDRESS                    VARCHAR(256) NOT NULL,          --收货地址(默认为项目地址,仍可修改)
  SIGN_MAN                   VARCHAR(64) NULL,               --签收人
  SIGN_DATE                  CHAR(10) NULL,                  --签收时间
  SIGN_RESULT                VARCHAR(512) NULL,              --签收结果
  REMARK                     VARCHAR(512) NULL,              --备注
  STATUS                     CHAR(1) NOT NULL,               --状态(表码值 0:发货中-保存后未签收的状态,1:已签收-点了已签收的物流单)
  FUND_STATUS                CHAR(1) NOT NULL,               --款项状态(表码值 0:待付款-初始,2:已付款-付款管理中有关联这条运输数据,且审批通过)
  DEL_FLAG                   CHAR(1) NOT NULL                --删除标识(表码值 0:删除,1:正常)
);
--物流回场清单
CREATE TABLE T_LOGISTICS_BACKDETAIL
(
  BACKDETAIL_ID              BIGINT IDENTITY PRIMARY KEY,
  BACKSPORT_ID               BIGINT NOT NULL,                --物流运输ID
  CAR_ID                     BIGINT NULL,                    --运输车辆
  LICENSE_PLATE              VARCHAR(16) NOT NULL,           --车号(来源车辆档案,用户也可手动输入)
  DRIVER                     VARCHAR(64) NULL,               --司机(默认车辆档案中信息,仍可修改)
  DRIVER_PHONE               VARCHAR(16) NULL,               --司机联系电话(同前面)
  COMPON_DIARY_ID            BIGINT NOT NULL,                --零配件调配ID
  COUNTS                     SMALLINT NOT NULL,              --运输数量
  REMARK                     VARCHAR(512) NULL               --备注
);
ALTER TABLE T_PROJECT DROP COLUMN CT_CUSTOM_LINKER_ID;
ALTER TABLE T_PROJECT DROP COLUMN UN_CUSTOM_LINKER_ID;
ALTER TABLE T_PROJECT DROP COLUMN SUP_CUSTOM_LINKER_ID;
ALTER TABLE T_PURCHASE DROP COLUMN SUPPLIER_LINKER_ID;
UPDATE FILE_ATTACH SET DEPEND_NAME = 'EQUIPMENT' WHERE DEPEND_NAME = 'EQUIP';
UPDATE APP_USER_EXTEND SET FOREIGN_MODULE = 'PRACTITIONER' WHERE FOREIGN_MODULE = 'PRACTI';

ALTER TABLE T_EQUIPMENT_INSPECT ADD REMARK VARCHAR(256) NULL;
ALTER TABLE APP_USER ADD LONGITUDE VARCHAR(16) NULL;
ALTER TABLE APP_USER ADD LATITUDE VARCHAR(16) NULL;
ALTER TABLE APP_USER ADD UPDATE_TIME DATETIME NULL;
--内置代码词典
CREATE TABLE BM_BUILTIN_STORAGE
(
  ALIAS VARCHAR(64) NOT NULL,
  CODE  VARCHAR(6) NOT NULL,
  VALUE VARCHAR(64) NOT NULL,
  NAME  VARCHAR(30) NOT NULL
);
INSERT INTO BM_BUILTIN_STORAGE VALUES('EQUIP_BUSINESS_STATUS', '0', '待用', NULL);
INSERT INTO BM_BUILTIN_STORAGE VALUES('EQUIP_BUSINESS_STATUS', '1', '合同', NULL);
INSERT INTO BM_BUILTIN_STORAGE VALUES('EQUIP_BUSINESS_STATUS', '2', '调度', NULL);
INSERT INTO BM_BUILTIN_STORAGE VALUES('EQUIP_BUSINESS_STATUS', '3', '安装', NULL);
INSERT INTO BM_BUILTIN_STORAGE VALUES('EQUIP_BUSINESS_STATUS', '4', '检测', NULL);
INSERT INTO BM_BUILTIN_STORAGE VALUES('EQUIP_BUSINESS_STATUS', '5', '验收', NULL);
INSERT INTO BM_BUILTIN_STORAGE VALUES('EQUIP_BUSINESS_STATUS', '6', '启用', NULL);
INSERT INTO BM_BUILTIN_STORAGE VALUES('EQUIP_BUSINESS_STATUS', '7', '报停', NULL);
INSERT INTO BM_BUILTIN_STORAGE VALUES('EQUIP_BUSINESS_STATUS', '8', '使用', NULL);
INSERT INTO BM_BUILTIN_STORAGE VALUES('EQUIP_BUSINESS_STATUS', '9', '拆卸', NULL);
INSERT INTO BM_BUILTIN_STORAGE VALUES('EQUIP_BUSINESS_STATUS', 'A', '入库', NULL);

ALTER TABLE T_EQUIPMENT_INSTALL ADD FILE_ATTACHES VARCHAR(1024) NULL;
ALTER TABLE T_EQUIPMENT_DISMANTLE ADD FILE_ATTACHES VARCHAR(1024) NULL;
ALTER TABLE T_EQUIPMENT_INSPECT ADD FILE_ATTACHES VARCHAR(1024) NULL;
--评论
CREATE TABLE T_REVIEW
(
  REVIEW_ID                  BIGINT IDENTITY PRIMARY KEY,
  RELATE_ID                  BIGINT NULL,                    --关联业务
  RELATE_MODULE              VARCHAR(32) NULL,               --关联业务模块
  CONTENT                    VARCHAR(1024) NOT NULL,         --评论内容
  REVIEW_TIME                SMALLDATETIME NOT NULL,         --评论时间
  PARENT_ID                  BIGINT NULL,                    --回复评论ID
  USER_ID                    BIGINT NOT NULL,                --评论人员(默认当前用户)
  USER_NAME                  VARCHAR(64) NOT NULL            --评论人员
);
--点赞
CREATE TABLE T_PRAISE
(
  Praise_ID                  BIGINT IDENTITY PRIMARY KEY,
  RELATE_ID                  BIGINT NULL,                    --关联业务
  RELATE_MODULE              VARCHAR(32) NULL,               --关联业务模块
  PRAISE_TIME                SMALLDATETIME NOT NULL,         --点赞时间
  USER_ID                    BIGINT NOT NULL,                --点赞人员(默认当前用户)
  USER_NAME                  VARCHAR(64) NOT NULL            --点赞人员
);
ALTER TABLE T_EQUIPMENT_INSTALL ADD LONGITUDE VARCHAR(16) NULL;
ALTER TABLE T_EQUIPMENT_INSTALL ADD LATITUDE VARCHAR(16) NULL;
ALTER TABLE T_EQUIPMENT_DISMANTLE ADD LONGITUDE VARCHAR(16) NULL;
ALTER TABLE T_EQUIPMENT_DISMANTLE ADD LATITUDE VARCHAR(16) NULL;
ALTER TABLE T_EQUIPMENT_INSPECT ADD LONGITUDE VARCHAR(16) NULL;
ALTER TABLE T_EQUIPMENT_INSPECT ADD LATITUDE VARCHAR(16) NULL;
--安装管理
CREATE TABLE T_INSTALL_MANAGE
(
  INSTALL_ID                 BIGINT IDENTITY PRIMARY KEY,
  RECORD_ID                  VARCHAR(24) NULL,               --备案编号
  PROJECT_NAME               VARCHAR(64) NULL,               --项目名称
  STARTIN_DATE               SMALLDATETIME NOT NULL,         --进场日期
  ENDIN_DATE                 SMALLDATETIME NOT NULL,         --退场日期
  WALL_ATTACHE_QTY           SMALLINT NULL,                  --本次附墙数
  BRACHIUM                   NUMERIC(12, 2) NULL,            --臂长
  INSTALL_HEIGHT             NUMERIC(12, 2) NULL,            --安装高度
  LONGITUDE                  VARCHAR(16) NULL,               --经度
  LATITUDE                   VARCHAR(16) NULL,               --纬度
  USER_ID                    BIGINT NOT NULL,                --登记人ID
  USER_NAME                  VARCHAR(64) NOT NULL,           --登记人
  PROVIDED_DATE              CHAR(10) NOT NULL,              --登记时间
  FILE_ATTACHES              VARCHAR(1024) NULL              --附件信息ID  
);
--拆卸管理
CREATE TABLE T_DISMANTLE_MANAGE
(
  DISMANTLE_ID               BIGINT IDENTITY PRIMARY KEY,
  RECORD_ID                  VARCHAR(24) NULL,               --备案编号
  PROJECT_NAME               VARCHAR(64) NULL,               --项目名称
  STARTDIS_DATE              SMALLDATETIME NOT NULL,         --实际进场时间(格式:年月日时,例如:2013年6月25日10时)
  ENDDIS_DATE                SMALLDATETIME NOT NULL,         --实际退场时间(单位:年月日时)
  DISMANTLE_HEIGHT           VARCHAR(8) NULL,                --拆卸高度
  LONGITUDE                  VARCHAR(16) NULL,               --经度
  LATITUDE                   VARCHAR(16) NULL,               --纬度
  USER_ID                    BIGINT NOT NULL,                --登记人ID
  USER_NAME                  VARCHAR(64) NOT NULL,           --登记人
  PROVIDED_DATE              CHAR(10) NOT NULL,              --登记时间
  FILE_ATTACHES              VARCHAR(1024) NULL              --附件信息ID  
);
--安全巡检 InspectManage
CREATE TABLE T_INSPECT_MANAGE
(
  INSPECT_ID                 BIGINT IDENTITY PRIMARY KEY,
  PROJECT_NAME               VARCHAR(64) NULL,               --项目名称
  INSPECT_DATE               DATETIME NULL,                  --实际巡检时间(实际巡检时间)
  INSPECT_PEPOLES            VARCHAR(128) NULL,              --巡检人员
  INSPECT_RESULT             VARCHAR(6) NULL,                --整机巡检结果(表码 BM_INSPECT_RESULT)
  REMARK                     VARCHAR(256) NULL,              --备注
  LONGITUDE                  VARCHAR(16) NULL,               --经度
  LATITUDE                   VARCHAR(16) NULL,               --纬度
  USER_ID                    BIGINT NOT NULL,                --登记人ID
  USER_NAME                  VARCHAR(64) NOT NULL,           --登记人
  PROVIDED_DATE              CHAR(10) NOT NULL,              --登记时间
  FILE_ATTACHES              VARCHAR(1024) NULL              --附件信息ID  
);
ALTER TABLE T_COMPONENT ALTER COLUMN SCRAP_DATE SMALLDATETIME NULL;
ALTER TABLE T_PURCHASE ALTER COLUMN LINKER VARCHAR(32) NULL;
ALTER TABLE T_PURCHASE ALTER COLUMN LINKER_TEL VARCHAR(16) NULL;
ALTER TABLE T_PRACTI_CERT ADD CONTRACT_DATE CHAR(10) NULL;
INSERT INTO SYS_CONFIG(CONFIGID, CONFIGNAME, CONFIGDESC, FIELDSET, TYPENAME, DATASTORE, DATATYPE, DATAVALUE, DELFLAG)
VALUES ('companyName', '企业名称', '企业名称', '企业名称', 'TEXT', NULL, 0,	'企业名称', 0);
INSERT INTO SYS_CONFIG(CONFIGID, CONFIGNAME, CONFIGDESC, FIELDSET, TYPENAME, DATASTORE, DATATYPE, DATAVALUE, DELFLAG)
VALUES ('companyType', '企业类型', '企业类型', '企业类型', 'TEXT', NULL, 0, '100', 0);
INSERT INTO SYS_CONFIG(CONFIGID, CONFIGNAME, CONFIGDESC, FIELDSET, TYPENAME, DATASTORE, DATATYPE, DATAVALUE, DELFLAG)
VALUES ('companyAddress', '企业地址', '企业地址', '企业地址', 'TEXT', NULL, 0, '企业地址', 0);
INSERT INTO SYS_CONFIG(CONFIGID, CONFIGNAME, CONFIGDESC, FIELDSET, TYPENAME, DATASTORE, DATATYPE, DATAVALUE, DELFLAG)
VALUES ('sitUrl', '服务器地址', '服务器地址', '服务器地址', 'TEXT', NULL, 0, 'http://risit.meibu.net:19085/emms', 1);
INSERT INTO SYS_CONFIG(CONFIGID, CONFIGNAME, CONFIGDESC, FIELDSET, TYPENAME, DATASTORE, DATATYPE, DATAVALUE, DELFLAG)
VALUES ('appAccessSwitch', 'APP接入', '用户信息是否同步APP', 'APP接入', 'COMBO', '0:关;1:开', 2, '0', 1);
INSERT INTO SYS_CONFIG(CONFIGID, CONFIGNAME, CONFIGDESC, FIELDSET, TYPENAME, DATASTORE, DATATYPE, DATAVALUE, DELFLAG)
VALUES ('appAccessUrl', 'APP接入地址', 'APP接入地址', 'APP接入地址', 'TEXT', NULL, 0, 'http://risit.meibu.net:18080/apps/services/SysService', 0);
GO
--2014-11-28
ALTER TABLE T_CONTRACT_EQUIP ALTER COLUMN CONTRACT_ID BIGINT NULL;
--2014-12-04
ALTER TABLE T_INSURE_EQUIPMENT ALTER COLUMN INSURANCE_COMPANY VARCHAR(64) NULL;
--2014-12-17
ALTER TABLE SYSTEM_LOG ALTER COLUMN REMARK TEXT NULL;

ALTER TABLE T_COMPONENT ALTER COLUMN DEPRECIATE_RATE NUMERIC(5, 2) NOT NULL;
ALTER TABLE T_COMPONENT ALTER COLUMN TOTAL_RATE NUMERIC(5, 2) NOT NULL;
ALTER TABLE T_EQUIPMENT ALTER COLUMN DEPRECIATE_RATE NUMERIC(5, 2) NOT NULL;
ALTER TABLE T_EQUIPMENT ALTER COLUMN TOTAL_RATE NUMERIC(5, 2) NOT NULL;

--2015-01-25
INSERT INTO SYS_CONFIG (CONFIGKEY, FIELDSET, CONFIGNAME, CONFIGDESC, TYPENAME, DATATYPE, DATAVALUE, DELFLAG)
VALUES ('contract.lease', '租赁合同模版地址', '租赁合同模版地址', '租赁合同模版地址', 'TEXT', 0, '/contract/lease.ftl', '0');
INSERT INTO SYS_CONFIG (CONFIGKEY, FIELDSET, CONFIGNAME, CONFIGDESC, TYPENAME, DATATYPE, DATAVALUE, DELFLAG)
VALUES ('contract.subcontract', '一体化合同模版地址', '一体化合同模版地址', '一体化合同模版地址', 'TEXT', 0, '/contract/subcontract.ftl', '0');
--2015-01-30
ALTER TABLE T_INSTALL_MANAGE ADD ADDRESS VARCHAR(128) NULL;
ALTER TABLE T_INSPECT_MANAGE ADD ADDRESS VARCHAR(128) NULL;
ALTER TABLE T_DISMANTLE_MANAGE ADD ADDRESS VARCHAR(128) NULL;
ALTER TABLE T_EQUIPMENT_INSTALL ADD ADDRESS VARCHAR(128) NULL;
ALTER TABLE T_EQUIPMENT_INSPECT ADD ADDRESS VARCHAR(128) NULL;
ALTER TABLE T_EQUIPMENT_DISMANTLE ADD ADDRESS VARCHAR(128) NULL;









