package com.knight.app.model;

import lombok.Data;
import lombok.ToString;

import com.google.gson.annotations.Expose;
import com.knight.core.model.BaseModel;

// Generated 2015-5-29 9:21:52 by Hibernate Tools 3.4.0.CR1

/**
 * TAppDispatchDetail generated by hbm2java
 */
@Data
@ToString(callSuper = false, doNotUseGetters = true)
public class TAppComponDispatchDetail extends BaseModel {

	private static final long serialVersionUID = 1L;
	@Expose
	private Long compDeid;
	@Expose
	private Long disid;
	@Expose
	private Long compId;
	@Expose
	private String compName;
	@Expose
	private String compSpec;
	@Expose
	private String dimensions;
	@Expose
	private Long stockNum;
	@Expose
	private Long disNum;
	@Expose
	private Long logisticNum;
	@Expose
	private String componSerial;

}
