package com.knight.app.model;

// Generated 2015-5-29 9:21:52 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import com.knight.emms.constant.Status;
import com.knight.emms.core.BusinessModel;
import com.knight.emms.core.model.SerialNumberStrategy;
import com.knight.emms.model.DispatchEquip;

import lombok.Data;
import lombok.ToString;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.Since;
import com.google.gson.reflect.TypeToken;
import com.knight.core.model.BaseModel;
import com.knight.core.model.ExportModel;
import com.knight.core.table.CodeFieldDeclare;
import com.knight.core.table.PersistantDeclare;
import com.knight.core.util.GsonUtil;

/**
 * TAppDispatch generated by hbm2java
 */
@Data
@ToString(callSuper = false, doNotUseGetters = true)
@PersistantDeclare(isExportable = true, exportName = "现场调度", sheetName = "现场调度")
@SerialNumberStrategy(name = "dispatchSerial", strategy = "DD{yyyyMMdd}", maxseq = 99)
public class TAppDispatch extends BusinessModel implements ExportModel, Cloneable {
	
	private static final long serialVersionUID = 1L;
	@Expose
	private Long disid;
    @Expose
    private String dispatchSerial;
	@Expose
	private String disDate;
	@Expose
	private Long projId;
	@Expose
	private String projName;
	@Expose
	@CodeFieldDeclare(codeId = "DISPATCH_TYPE", valueField = "disTypeName")
	private String disType;
	@Expose
	private String disTypeName;
	@Expose
	private String dispatcher;
	@Expose
	private String remark;
	@Expose
	private String createDt;
	@Expose
	private Long createBy;
	@Expose
	private String createByName;
	@Expose
	private Long contractId;
	@Expose
	private Long sendId;
	@Expose
	private String sendWarehouseName;
	@Expose
	private String sendWarehouseAddress;
	@Expose
	private String sendWarehouseType;
	@Expose
	private Long receiveId;
	@Expose
	private String receiveWarehouseName;
	@Expose
	private String receiveWarehouseAddress;
	@Expose
	private String receWarehouseType;
	@Expose
	@CodeFieldDeclare(codeId = "APP_DISPATCH_STATUS",valueField = "statusName")
	private String status;
	@Expose
	private String statusName;
	@Expose
	private String fileAttaches;
	@Expose
	private String transportUnit;
	
	/**
	 * 已装车次数
	 * */
	@Expose
	private Integer logisticsTimes;

	
	@Expose(deserialize = false, serialize = false)
	@Since(value = 2.0)
	private Set<TAppComponDispatchDetail> dispComponDetailSet = new HashSet<TAppComponDispatchDetail>();

	private String dispComponDetails = "";

	@Expose(deserialize = false, serialize = false)
	@Since(value = 2.0)
	private Set<TAppEquipDispatchDetail> dispEquipDetailSet = new HashSet<TAppEquipDispatchDetail>();

	private String dispEquipDetails = "";
	
	public void setSubTAppDispatch() {
		Set<TAppComponDispatchDetail> disComponDetailSet = GsonUtil.fromJson(this.dispComponDetails, new TypeToken<Set<TAppComponDispatchDetail>>() {});
		if (disComponDetailSet != null) {
			this.setDispComponDetailSet(disComponDetailSet);
		}
        Set<TAppEquipDispatchDetail> disEquipDetailSet = GsonUtil.fromJson(this.dispEquipDetails,new TypeToken<Set<TAppEquipDispatchDetail>>(){});
        if(disEquipDetailSet !=null){
            this.setDispEquipDetailSet(disEquipDetailSet);
        }
	}


    @Override
    public void setModelSerial(String serial) {
        this.dispatchSerial = serial;
    }
}
