package com.knight.app.model;

// Generated 2015-5-28 17:11:39 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import lombok.Data;
import lombok.ToString;

import com.google.gson.annotations.Expose;
import com.knight.core.model.BaseModel;
import com.knight.core.model.ExportModel;
import com.knight.core.table.PersistantDeclare;

/**
 * TFlowInstanceProcess generated by hbm2java
 */

@Data
@ToString(callSuper = false, doNotUseGetters = true)
public class TFlowInstanceProcess extends BaseModel{

	private static final long serialVersionUID = 1L;

	@Expose
	private Long pid;
	@Expose
	private Long insid;
	@Expose
	private Long nodeid;
	@Expose
	private Long chkUserid;
	@Expose
	private String chkUserName;
	@Expose
	private String chkDate;
	@Expose
	private String chkResult;	
	@Expose
	private String chkOpinion;
	
	@Expose
	private TFlowInstance instance;
}
