package com.knight.app.model;

import java.util.HashSet;
import java.util.Set;

import lombok.Data;
import lombok.ToString;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.Since;
import com.knight.core.model.BaseModel;

// Generated 2015-5-28 17:11:39 by Hibernate Tools 3.4.0.CR1

/**
 * TFlowNode generated by hbm2java
 */

@Data
@ToString(callSuper = false, doNotUseGetters = true)
public class TFlowNode extends BaseModel {

	private static final long serialVersionUID = 1L;
	@Expose	
	private Long nid;
	@Expose	
	private Long flowId;
	@Expose	
	private Long seq;
	@Expose	
	private String nodeName;
	@Expose	
	private Long chkRoleid;
	@Expose	
	private Long chkUserid;
	@Expose
	private String chkRoleName;
	@Expose	
	private String chkName;		

}
