package com.knight.app.model;

// Generated 2015-5-28 17:11:39 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import lombok.Data;
import lombok.ToString;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.Since;
import com.google.gson.reflect.TypeToken;
import com.knight.core.model.BaseModel;
import com.knight.core.model.ExportModel;
import com.knight.core.table.CodeFieldDeclare;
import com.knight.core.table.PersistantDeclare;
import com.knight.core.util.GsonUtil;
import com.knight.emms.model.CorpAccount;

/**
 * TFlowDefine generated by hbm2java
 */
@Data
@ToString(callSuper = false, doNotUseGetters = true)
@PersistantDeclare(isExportable = true, exportName = "流程制定", sheetName = "流程制定")
public class TFlowDefine extends BaseModel  implements ExportModel, Cloneable {

	private static final long serialVersionUID = 1L;
	@Expose
	private Long flowid;
	@Expose
	private String flowName;
	@Expose
	private String createDt;
	@Expose
	private Long createBy;
	@Expose
	private String createByName;
	
	@Expose
	@CodeFieldDeclare(codeId = "RELATE_MODULE_FLOW", valueField = "relateModuleName")
	private String relateModule;
	
	@Expose
	private String relateModuleName;
	
	@Expose
	private Integer delFlag;
	
	@Expose(deserialize = false, serialize = false)
	@Since(value = 2.0)
	private Set<TFlowNode> nodeSet = new HashSet<TFlowNode>();
	@Expose
	private String nodes;
	
	public void setSubNodes() {
		Set<TFlowNode> fnodeset = GsonUtil.fromJson(this.getNodes(), new TypeToken<Set<TFlowNode>>() {});
		if (fnodeset != null) {
			for (TFlowNode node : fnodeset) {
				node.setFlowId(this.getFlowid());
			}
			this.setNodeSet(fnodeset);
		}
	}

}
