<p style="font: bold 28px/28px &quot;&quot;; margin: 0px; padding: 10px 0px 0px; text-align: center; color: rgb(0, 0, 0); text-transform: none; text-indent: 0px; letter-spacing: normal; word-spacing: 0px; white-space: normal; font-size-adjust: none; font-stretch: normal; -webkit-text-stroke-width: 0px;">
    <span style="font-family: 宋体,SimSun;">催 款 函</span>
</p>
<p style="font: 16px/28px &quot;&quot;; margin: 0px; padding: 15px 15px 0px 0px; text-align: right; color: rgb(0, 0, 0); text-transform: none; text-indent: 0px; letter-spacing: normal; word-spacing: 0px; white-space: normal; font-size-adjust: none; font-stretch: normal; -webkit-text-stroke-width: 0px;">
    <span style="font-family: 宋体,SimSun;">编号:<strong>${overduePayment.overduePaymentSerial}</strong></span>
</p>
<p style="font: 14px/28px &quot;&quot;; margin: 0px; padding: 0px; text-align: left; color: rgb(0, 0, 0); text-transform: none; text-indent: 2em; letter-spacing: normal; word-spacing: 0px; white-space: normal; font-size-adjust: none; font-stretch: normal; -webkit-text-stroke-width: 0px;">
    <span style="font-family: 宋体,SimSun; text-decoration: underline;">${overduePayment.customerName}</span><span style="font-family: 宋体,SimSun; text-decoration: none;">：</span><span style="font-family: 宋体,SimSun;">&nbsp;</span>
</p>
<p style="font: 14px/28px &quot;&quot;; margin: 0px; padding: 0px; text-align: left; color: rgb(0, 0, 0); text-transform: none; text-indent: 2em; letter-spacing: normal; word-spacing: 0px; white-space: normal; font-size-adjust: none; font-stretch: normal; -webkit-text-stroke-width: 0px;" class="indt2">
    <span style="font-family: 宋体,SimSun;">因贵司拖欠账款一事，为敦促贵司尽快付款，避免塔机厂家停机影响生产，造成严重后果。我司特致函如下：&nbsp;&nbsp;</span>
</p>
<p style="font: 14px/28px &quot;&quot;; margin: 0px; padding: 0px; text-align: left; color: rgb(0, 0, 0); text-transform: none; text-indent: 2em; letter-spacing: normal; word-spacing: 0px; white-space: normal; font-size-adjust: none; font-stretch: normal; -webkit-text-stroke-width: 0px;" class="indt2">
    <span style="font-family: 宋体,SimSun;">贵司从<span style="font-family: 宋体,SimSun; text-decoration: underline;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>年<span style="font-family: 宋体,SimSun; text-decoration: underline;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>月<span style="font-family: 宋体,SimSun; text-decoration: underline;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>日起租用我司建机设备，我司负责安排塔机进场,并组织安装生产作业。至<span style="font-family: 宋体,SimSun; text-decoration: underline;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>年<span style="font-family: 宋体,SimSun; text-decoration: underline;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>月<span style="font-family: 宋体,SimSun; text-decoration: underline;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>日，租赁期间共发生租赁费用人民币<span style="font-family: 宋体,SimSun; text-decoration: underline;">&nbsp;&nbsp;&nbsp;&nbsp;</span>元（大写：<span style="font-family: 宋体,SimSun; text-decoration: underline;">X&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XX&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XX</span>）。依照与贵司签订的编号为<strong><span style="font-family: 宋体,SimSun; text-decoration: underline;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></strong><span style="font-family: 宋体,SimSun; text-decoration: underline;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;的</span>合同约定，贵司须按照与我司规定的租金结算方式、每期租金额度和还款期限按时足额还款，直至租金结清为止。&nbsp;贵司一直以经济困难拖延还款，我司虽给予贵司宽限期，但贵司至今未能足额支付租金。我司现通知贵司：&nbsp;若贵司在&nbsp;&nbsp;年&nbsp;月&nbsp;日前仍未支付拖欠租金，我司将进行远程停机。未避免停机影响贵方正常的生产经营，请按约定还款。&nbsp;</span>
</p>
<p style="font: 14px/28px &quot;&quot;; margin: 0px; padding: 0px; text-align: left; color: rgb(0, 0, 0); text-transform: none; text-indent: 2em; letter-spacing: normal; word-spacing: 0px; white-space: normal; font-size-adjust: none; font-stretch: normal; -webkit-text-stroke-width: 0px;" class="indt2">
    <span style="font-family: 宋体,SimSun;">据我国《合同法》第六十条规定:“当事人应当按照约定全面履行自己的义务。”故贵司的欠款行为已经明显违反法律规定和双方约定。因考虑到和贵司的友好合作关系，现发函催告，请贵司在收到此函后将上述逾期款项付至我司账户开户行：<span style="font-family: 宋体,SimSun; text-decoration: underline;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>；收款单位：<span style="font-family: 宋体,SimSun; text-decoration: underline;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>；账号：<span style="font-family: 宋体,SimSun; text-decoration: underline;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>,否则因厂家停机造成的一切损失均由贵司负责，同时，我司保留通过法律途径向贵司追究违约责任权利。<br/></span>
</p>
<p style="font: 14px/28px &quot;&quot;; margin: 0px; padding: 0px; text-align: left; color: rgb(0, 0, 0); text-transform: none; text-indent: 2em; letter-spacing: normal; word-spacing: 0px; white-space: normal; font-size-adjust: none; font-stretch: normal; -webkit-text-stroke-width: 0px;" class="indt2">
    <span style="font-family: 宋体,SimSun;">顺颂商祺!</span>
</p>
<p style="font: 14px/28px &quot;&quot;; margin: 0px; padding: 0px 20px 0px 0px; height: 30px; text-align: right; color: rgb(0, 0, 0); text-transform: none; text-indent: 0px; letter-spacing: normal; word-spacing: 0px; white-space: normal; font-size-adjust: none; font-stretch: normal; -webkit-text-stroke-width: 0px;">
    <span style="font-family: 宋体,SimSun;">${overduePayment.corpName}</span>
</p>
<p style="font: 14px/28px &quot;&quot;; margin: 0px; padding: 0px 20px 0px 0px; height: 30px; text-align: right; color: rgb(0, 0, 0); text-transform: none; text-indent: 0px; letter-spacing: normal; word-spacing: 0px; white-space: normal; font-size-adjust: none; font-stretch: normal; -webkit-text-stroke-width: 0px;">
    <span style="font-family: 宋体,SimSun;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;年&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;月&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;日</span>
</p>
<p>
    &nbsp;
</p>